#!/usr/bin/env python3
"""Inject src/*.js into index.html between their marker comments.
Run after editing any of them: python3 tools/build.py (and node tools/fill-build.js first after editing data/fill/)."""
import pathlib, re
root = pathlib.Path(__file__).resolve().parent.parent
html = (root / 'index.html').read_text()
for name, anchor in [('cat-fill', 'const CATALOGUES = ['),
                     ('portrait', '// ================= Apple Box — World Core UI ================='),
                     ('figure', '// ================= Apple Box — World Core UI ================='),
                     ('real-looks', '// ================= Apple Box — World Core UI ================='),
                     ('home', '// ================= Apple Box — World Core UI ================='),
                     ('career-sim', '// ================= Apple Box — World Core UI ================='),
                     ('career-depth', '// ================= Apple Box — World Core UI ================='),
                     ('life', '// ================= Apple Box — World Core UI ================='),
                     ('life-scenes', '// ================= Apple Box — World Core UI ================='),
                     ('life-scenes-more', '// ================= Apple Box — World Core UI ================='),
                     ('life-scenes-third', '// ================= Apple Box — World Core UI ================='),
                     ('life-voice', '// ================= Apple Box — World Core UI ================='),
                     ('life-city', '// ================= Apple Box — World Core UI ================='),
                     ('life-scenes-low', '// ================= Apple Box — World Core UI ================='),
                     ('life-scenes-exec', '// ================= Apple Box — World Core UI ================='),
                     ('life-social', '// ================= Apple Box — World Core UI ================='),
                     ('life-world', '// ================= Apple Box — World Core UI ================='),
                     ('fiction', '// ================= Apple Box — World Core UI ================='),
                     ('trivia', '// ================= Apple Box — World Core UI ================='),
                     ('life-deals', '// ================= Apple Box — World Core UI ================='),
                     ('gea', '// ================= Apple Box — World Core UI ================='),
                     ('press', '// ================= Apple Box — World Core UI ================='),
                     ('companies', '// ================= Apple Box — World Core UI ================='),
                     ('life-phone', '// ================= Apple Box — World Core UI ================='),
                     ('computer', '// ================= Apple Box — World Core UI ================='),
                     ('city-plus', '// ================= Apple Box — World Core UI ================='),
                     ('strategy', '// ================= Apple Box — World Core UI ================='),
                     ('industry', '// ================= Apple Box — World Core UI ================='),
                     ('media', '// ================= Apple Box — World Core UI ================='),
                     ('computer2', '// ================= Apple Box — World Core UI ================='),
                     ('media-industry', '// ================= Apple Box — World Core UI ================='),
                     ('clippings', '// ================= Apple Box — World Core UI ================='),
                     ('mentor', '// ================= Apple Box — World Core UI ================='),
                     ('corrections', '// ================= Apple Box — World Core UI ================='),
                     ('cinema', '// ================= Apple Box — World Core UI ================='),
                     ('convo', '// ================= Apple Box — World Core UI ================='),
                     ('situations', '// ================= Apple Box — World Core UI ================='),
                     ('jobboard', '// ================= Apple Box — World Core UI ================='),
                     ('schools', '// ================= Apple Box — World Core UI ================='),
                     ('awardbodies', '// ================= Apple Box — World Core UI ================='),
                     ('corporate', '// ================= Apple Box — World Core UI ================='),
                     ('standing', '// ================= Apple Box — World Core UI ================='),
                     ('starmeter', '// ================= Apple Box — World Core UI ================='),
                     ('hub', '// ================= Apple Box — World Core UI ================='),
                     ('codex', '// ================= Apple Box — World Core UI ================='),
                     ('autopilot', '// ================= Apple Box — World Core UI ================='),
                     ('market', '// ================= Apple Box — World Core UI ================='),
                     ('festivals', '// ================= Apple Box — World Core UI ================='),
                     ('messaging', '// ================= Apple Box — World Core UI ================='),
                     ('depth', '// ================= Apple Box — World Core UI ================='),
                     ('late-game', '// ================= Apple Box — World Core UI ================='),
                     ('chatter', '// ================= Apple Box — World Core UI ================='),
                     ('os', '// ================= Apple Box — World Core UI ================='),
                     ('archive2', '// ================= Apple Box — World Core UI ================='),
                     ('companywork', '// ================= Apple Box — World Core UI ================='),
                     ('awards2', '// ================= Apple Box — World Core UI ================='),
                     ('trailer2', '// ================= Apple Box — World Core UI ================='),
                     ('stories', '// ================= Apple Box — World Core UI ================='),
                     ('story1', '// ================= Apple Box — World Core UI ================='),
                     ('story2', '// ================= Apple Box — World Core UI ================='),
                     ('story3', '// ================= Apple Box — World Core UI ================='),
                     ('story4', '// ================= Apple Box — World Core UI ================='),
                     ('story5', '// ================= Apple Box — World Core UI ================='),
                     ('story6', '// ================= Apple Box — World Core UI ================='),
                     ('story7', '// ================= Apple Box — World Core UI ================='),
                     ('story8', '// ================= Apple Box — World Core UI ================='),
                     ('story9', '// ================= Apple Box — World Core UI ================='),
                     ('story10', '// ================= Apple Box — World Core UI ================='),
                     ('story11', '// ================= Apple Box — World Core UI ================='),
                     ('story12', '// ================= Apple Box — World Core UI ================='),
                     ('story13', '// ================= Apple Box — World Core UI ================='),
                     ('story14', '// ================= Apple Box — World Core UI ================='),
                     ('story15', '// ================= Apple Box — World Core UI ================='),
                     ('story16', '// ================= Apple Box — World Core UI ================='),
                     ('story17', '// ================= Apple Box — World Core UI ================='),
                     ('story18', '// ================= Apple Box — World Core UI ================='),
                     ('story19', '// ================= Apple Box — World Core UI ================='),
                     ('story20', '// ================= Apple Box — World Core UI ================='),
                     ('story21', '// ================= Apple Box — World Core UI ================='),
                     ('story22', '// ================= Apple Box — World Core UI ================='),
                     ('story23', '// ================= Apple Box — World Core UI ================='),
                     ('story24', '// ================= Apple Box — World Core UI ================='),
                     ('story25', '// ================= Apple Box — World Core UI ================='),
                     ('story26', '// ================= Apple Box — World Core UI ================='),
                     ('story27', '// ================= Apple Box — World Core UI ================='),
                     ('story28', '// ================= Apple Box — World Core UI ================='),
                     ('story29', '// ================= Apple Box — World Core UI ================='),
                     ('story30', '// ================= Apple Box — World Core UI ================='),
                     ('story31', '// ================= Apple Box — World Core UI ================='),
                     ('story32', '// ================= Apple Box — World Core UI ================='),
                     ('story33', '// ================= Apple Box — World Core UI ================='),
                     ('story34', '// ================= Apple Box — World Core UI ================='),
                     ('story35', '// ================= Apple Box — World Core UI ================='),
                     ('story36', '// ================= Apple Box — World Core UI ================='),
                     ('story37', '// ================= Apple Box — World Core UI ================='),
                     ('story38', '// ================= Apple Box — World Core UI ================='),
                     ('story39', '// ================= Apple Box — World Core UI ================='),
                     ('story40', '// ================= Apple Box — World Core UI ================='),
                     ('story41', '// ================= Apple Box — World Core UI ================='),
                     ('story42', '// ================= Apple Box — World Core UI ================='),
                     ('story43', '// ================= Apple Box — World Core UI ================='),
                     ('story44', '// ================= Apple Box — World Core UI ================='),
                     ('story45', '// ================= Apple Box — World Core UI ================='),
                     ('story46', '// ================= Apple Box — World Core UI ================='),
                     ('staff', '// ================= Apple Box — World Core UI ================='),
                     ('curric1', '// ================= Apple Box — World Core UI ================='),
                     ('curric2', '// ================= Apple Box — World Core UI ================='),
                     ('curric3', '// ================= Apple Box — World Core UI ================='),
                     ('curric4', '// ================= Apple Box — World Core UI ================='),
                     ('curric5', '// ================= Apple Box — World Core UI ================='),
                     ('curric6', '// ================= Apple Box — World Core UI ================='),
                     ('curric7', '// ================= Apple Box — World Core UI ================='),
                     ('curric8', '// ================= Apple Box — World Core UI ================='),
                     ('curric9', '// ================= Apple Box — World Core UI ================='),
                     ('numbers', '// ================= Apple Box — World Core UI ================='),
                     ('awards3', '// ================= Apple Box — World Core UI ================='),
                     ('careers', '// ================= Apple Box — World Core UI ================='),
                     ('curriculum', '// ================= Apple Box — World Core UI ================='),
                     ('campaign', '// ================= Apple Box — World Core UI ================='),
                     ('cohort', '// ================= Apple Box — World Core UI ================='),
                     ('competitions', '// ================= Apple Box — World Core UI ================='),
                     ('consequence', '// ================= Apple Box — World Core UI ================='),
                     ('job-tasks', '// ================= Apple Box — World Core UI ================='),
                     ('feed', '// ================= Apple Box — World Core UI ================='),
                     ('life-story', '// ================= Apple Box — World Core UI ================='),
                     ('critics', '// ================= Apple Box — World Core UI ================='),
                     ('finance', '// ================= Apple Box — World Core UI ================='),
                     ('osfold', '// ================= Apple Box — World Core UI ================='),
                     ('shop2', '// ================= Apple Box — World Core UI ================='),
                     ('charts2', '// ================= Apple Box — World Core UI ================='),
                     ('amb2', '// ================= Apple Box — World Core UI ================='),
                     ('boards', '// ================= Apple Box — World Core UI ================='),
                     ('trivia2', '// ================= Apple Box — World Core UI ================='),
                     ('shorts', '// ================= Apple Box — World Core UI ================='),
                     ('tv', '// ================= Apple Box — World Core UI ================='),
                     ('tv2', '// ================= Apple Box — World Core UI ================='),
                     ('legacy', '// ================= Apple Box — World Core UI ================='),
                     ('market2', '// ================= Apple Box — World Core UI ================='),
                     ('reel2', '// ================= Apple Box — World Core UI ================='),
                     ('financing', '// ================= Apple Box — World Core UI ================='),
                     ('saves', '// ================= Apple Box — World Core UI ================='),
                     ('correspond', '// ================= Apple Box — World Core UI ================='),
                     ('weather', '// ================= Apple Box — World Core UI ================='),
                     ('clapgram', '// ================= Apple Box — World Core UI ================='),
                     ('tv3', '// ================= Apple Box — World Core UI ================='),
                     ('finance2', '// ================= Apple Box — World Core UI ================='),
                     ('creative', '// ================= Apple Box — World Core UI ================='),
                     ('roger2', '// ================= Apple Box — World Core UI ================='),
                     ('work2', '// ================= Apple Box — World Core UI ================='),
                     ('mine', '// ================= Apple Box — World Core UI ================='),
                     ('decide', '// ================= Apple Box — World Core UI ================='),
                     ('diary2', '// ================= Apple Box — World Core UI ================='),
                     ('make2', '// ================= Apple Box — World Core UI ================='),
                     ('make3', '// ================= Apple Box — World Core UI ================='),
                     ('body', '// ================= Apple Box — World Core UI ================='),
                     ('tone', '// ================= Apple Box — World Core UI ================='),
                     ('msgfix', '// ================= Apple Box — World Core UI ================='),
                     ('market3', '// ================= Apple Box — World Core UI ================='),
                     ('arcs', '// ================= Apple Box — World Core UI ================='),
                     ('variety', '// ================= Apple Box — World Core UI ================='),
                     ('party2', '// ================= Apple Box — World Core UI ================='),
                     ('dreams', '// ================= Apple Box — World Core UI ================='),
                     ('gigs', '// ================= Apple Box — World Core UI ================='),
                     ('dealroom', '// ================= Apple Box — World Core UI ================='),
                     ('paths', '// ================= Apple Box — World Core UI ================='),
                     ('art', '// ================= Apple Box — World Core UI ================='),
                     ('works2', '// ================= Apple Box — World Core UI ================='),
                     ('bank2', '// ================= Apple Box — World Core UI ================='),
                     ('contests2', '// ================= Apple Box — World Core UI ================='),
                     ('career-ui', '// ---------- render & routing ----------')]:
    body = (root / 'src' / f'{name}.js').read_text().rstrip() + '\n'
    block = f'// <{name}>\n{body}// </{name}>\n'
    pat = re.compile(rf'// <{name}>\n.*?// </{name}>\n', re.S)
    if pat.search(html):
        html = pat.sub(lambda m: block, html)
    else:
        assert anchor in html, anchor
        html = html.replace(anchor, block + anchor, 1)
(root / 'index.html').write_text(html)
print('built', len(html), 'bytes')
