// ---------------- Cinema: stills you can read, and trailers that play like trailers ----------------
// A still is a composed frame: a real place (a diner, a saloon, a starship bridge), the film's actual cast drawn with
// their own skin, hair and clothes, a time of day that is never mud-dark, props for the genre and the era, and a grade
// on top. Every frame says what it shows. The trailer cuts the same frames into a moving teaser: slow push-ins and
// pans, things moving inside the frame, text laid over footage, a montage that speeds up, a title slam and a score.
// Nothing here rolls the world's dice: every choice comes from a hash of the film.
const CW = 320, CH = 180;
const SC_SETTINGS = {
  diner: 'at the diner', apartment: 'in the apartment', office: 'at the office', street: 'on the street', car: 'in the car', rooftop: 'on the rooftop',
  westtown: 'on Main Street', saloon: 'in the saloon', desert: 'out in the desert', forest: 'in the woods', beach: 'on the beach', mountains: 'up in the mountains',
  bridge: 'on the bridge of the ship', planet: 'on the surface', castle: 'in the great hall', battlefield: 'at the front', stage: 'on stage', ballroom: 'at the ball',
  classroom: 'in the classroom', hospital: 'at the hospital', interrogation: 'in the interrogation room', courtroom: 'in court', haunted: 'in the old house',
  kitchen: 'in the kitchen', dojo: 'in the dojo', skyline: 'above the city', ring: 'in the ring', lab: 'in the lab', train: 'on the night train', wedding: 'at the wedding',
  interview: 'in front of the camera', toon: 'in the cartoon town', club: 'at the club', alley: 'in the alley'
};
const GENRE_SETTINGS = {
  Western: ['westtown', 'saloon', 'desert', 'westtown'], 'Sci-fi': ['bridge', 'planet', 'lab', 'bridge'], Horror: ['haunted', 'forest', 'hospital', 'haunted'], War: ['battlefield', 'forest', 'train', 'battlefield'],
  Fantasy: ['castle', 'forest', 'mountains', 'castle'], Musical: ['stage', 'ballroom', 'street', 'club'], 'Martial arts': ['dojo', 'street', 'mountains', 'dojo'], Superhero: ['skyline', 'rooftop', 'lab', 'street'],
  Action: ['street', 'car', 'rooftop', 'alley', 'train'], Crime: ['alley', 'interrogation', 'car', 'diner', 'courtroom'], Thriller: ['apartment', 'alley', 'office', 'car', 'rooftop'],
  Romance: ['beach', 'ballroom', 'diner', 'apartment', 'wedding'], Comedy: ['kitchen', 'office', 'diner', 'wedding', 'apartment'], Documentary: ['interview', 'street', 'mountains', 'interview'],
  Animation: ['toon', 'toon', 'toon'], Period: ['ballroom', 'castle', 'street', 'courtroom'], Drama: ['apartment', 'kitchen', 'hospital', 'diner', 'classroom', 'courtroom']
};
// what people do in a frame, by genre (two people; one person)
const SC_VERBS = {
  Western: [['face each other down', 'ride in', 'share a bottle'], ['waits for the noon train', 'scans the horizon', 'rides into town']],
  'Sci-fi': [['watch the readings climb', 'argue over the course', 'find the signal'], ['stares out at the stars', 'runs the final check', 'steps out first']],
  Horror: [['hear something upstairs', 'hold their breath', 'find the door open'], ['turns slowly toward the sound', 'follows the light', 'is not alone']],
  War: [['wait for the whistle', 'share the last cigarette', 'drag a friend to cover'], ['keeps watch', 'writes a letter home', 'goes over the top']],
  Fantasy: [['swear an oath', 'study the old map', 'face the throne'], ['raises the sword', 'reads the prophecy', 'crosses the threshold']],
  Musical: [['dance the big number', 'sing the duet', 'rehearse the finale'], ['hits the high note', 'takes the spotlight', 'dances alone']],
  'Martial arts': [['square off', 'train at dawn', 'bow before the fight'], ['practises the forms', 'meditates', 'takes on ten men']],
  Superhero: [['suit up', 'stand back to back', 'face the villain'], ['soars over the city', 'lands hard', 'looks down at the streets']],
  Action: [['run for it', 'take cover', 'jump the gap'], ['sprints for the exit', 'braces for impact', 'walks away from the blast']],
  Crime: [['make the deal', 'trade accusations', 'count the money'], ['lights a cigarette', 'waits in the shadows', 'reads the file again']],
  Thriller: [['whisper about the plan', 'realise they\'re being watched', 'argue in low voices'], ['checks over a shoulder', 'reads the message twice', 'watches the window']],
  Romance: [['almost kiss', 'laugh at the same moment', 'say goodbye'], ['waits, hoping', 'reads the letter', 'looks back once']],
  Comedy: [['realise it was the wrong house', 'try to explain', 'hide behind the curtain'], ['makes it worse', 'pretends nothing happened', 'is about to sneeze']],
  Documentary: [['remember how it began', 'disagree on camera', 'look at the old photos'], ['tells the story', 'looks into the lens', 'goes back to where it happened']],
  Animation: [['go on an adventure', 'sing about it', 'make a plan'], ['has an idea', 'sets off', 'meets a friend']],
  Drama: [['have the conversation they\'ve avoided', 'sit in silence', 'finally tell the truth'], ['holds it together', 'makes the call', 'remembers']],
  Period: [['exchange a glance', 'trade polite threats', 'dance the last waltz'], ['reads the letter again', 'waits to be announced', 'stands at the window']]
};
function scPal(f, r, tod) {
  const sky = [['#7FB5E6', '#CFE6F7'], ['#F29E6B', '#FBD8A0'], ['#5D5E9E', '#E39A8A'], ['#22325A', '#4C6A9C']][tod];
  return { skyT: sky[0], skyB: sky[1], tod, night: tod === 3, sun: ['#FFF4CC', '#FFD27A', '#FFB38A', '#F2F0E6'][tod] };
}
function lighten(c, t) { return mixC(c, '#FFFFFF', t); }
function darken(c, t) { return mixC(c, '#000000', t); }
// ---- people in frame: the film's real cast, with their own colouring ----
function scLook(id, r) {
  if (id !== undefined && P(id)) { const L = Object.assign(defaultLook(), migrateLook(Object.assign({}, lookOf(P(id))))), age = S.year - P(id).born; return { skin: LOOK.skin.opts[L.skin], hair: L.hair, hc: mixHex(LOOK.hairColor.opts[L.hairColor], '#D9D6D0', clamp((age - 44) / 26, 0, .85)), cloth: LOOK.colour.opts[L.colour], g: P(id).g, beard: L.facial >= 4 && L.facial <= 5, glasses: L.glasses > 0 && L.glasses !== 7 }; }
  const skins = LOOK.skin.opts, cols = LOOK.colour.opts, hcs = LOOK.hairColor.opts;
  return { skin: skins[Math.floor(r() * skins.length)], hair: Math.floor(r() * 10), hc: hcs[Math.floor(r() * 7)], cloth: cols[Math.floor(r() * cols.length)], g: r() < .5 ? 'F' : 'M' };
}
// a full figure: x at the feet, gy the ground line, h the height
function actor(x, gy, h, L, o = {}) {
  const s = h / 100, face = o.face || 1, top = gy - h, hr = 9 * s, hx = x, hy = top + hr + 1;
  const cloth = o.costume === 'space' ? '#D9DDE3' : o.costume === 'armor' ? '#8C9096' : o.costume === 'uniform' ? '#5C6A3E' : o.costume === 'gi' ? '#F2EFE6' : o.costume === 'robe' ? mixC(L.cloth, '#3A1E5C', .4) : L.cloth;
  const legs = o.costume === 'gi' ? '#F2EFE6' : o.costume === 'space' ? '#C5CAD2' : darken(cloth, .35), shoe = '#2A221C', skin = L.skin, rim = o.rim || null;
  const out = [], walk = o.pose === 'walk' || o.pose === 'run', sit = o.pose === 'sit';
  const hip = sit ? gy - 30 * s : gy - 44 * s, sh = top + 22 * s;
  // legs
  if (sit) out.push(`<path d="M${x - 6 * s} ${hip} h${16 * face * s} v${28 * s} M${x + 2 * s} ${hip} h${16 * face * s} v${28 * s}" stroke="${legs}" stroke-width="${7 * s}" fill="none" stroke-linecap="round"/>`);
  else if (walk) out.push(`<path d="M${x} ${hip} l${-9 * s} ${44 * s} M${x} ${hip} l${11 * s} ${44 * s}" stroke="${legs}" stroke-width="${7 * s}" stroke-linecap="round"/>`);
  else out.push(`<path d="M${x - 4 * s} ${hip} v${44 * s} M${x + 4 * s} ${hip} v${44 * s}" stroke="${legs}" stroke-width="${7 * s}" stroke-linecap="round"/>`);
  if (!sit) out.push(`<ellipse cx="${x - 4 * s + (walk ? -5 * s : 0)}" cy="${gy}" rx="${5 * s}" ry="${2.2 * s}" fill="${shoe}"/><ellipse cx="${x + 4 * s + (walk ? 7 * s : 0)}" cy="${gy}" rx="${5 * s}" ry="${2.2 * s}" fill="${shoe}"/>`);
  // body: a dress flares, everything else is a jacket
  if (L.g === 'F' && o.costume !== 'space' && o.costume !== 'armor' && o.costume !== 'uniform' && o.costume !== 'gi' && (o.dress || (L.hair >= 7))) out.push(`<path d="M${x - 9 * s} ${sh} L${x + 9 * s} ${sh} L${x + 17 * s} ${hip + 22 * s} L${x - 17 * s} ${hip + 22 * s}Z" fill="${cloth}"/>`);
  else out.push(`<path d="M${x - 11 * s} ${sh + 3 * s} Q${x} ${sh - 3 * s} ${x + 11 * s} ${sh + 3 * s} L${x + 10 * s} ${hip + 3 * s} L${x - 10 * s} ${hip + 3 * s}Z" fill="${cloth}"/>`);
  if (o.costume === 'suit') out.push(`<path d="M${x} ${sh} l${-4 * s} ${10 * s} l${4 * s} ${14 * s} l${4 * s} ${-14 * s}Z" fill="#F2EFE6"/><path d="M${x} ${sh + 4 * s} v${16 * s}" stroke="#7A2E2E" stroke-width="${2.2 * s}"/>`);
  if (o.costume === 'armor') out.push(`<path d="M${x - 10 * s} ${sh + 6 * s} h${20 * s}" stroke="#C9CDD2" stroke-width="${2 * s}"/>`);
  if (o.costume === 'gi') out.push(`<path d="M${x - 10 * s} ${hip} h${20 * s}" stroke="#1E1E1E" stroke-width="${3 * s}"/>`);
  if (o.cape) out.push(`<path d="M${x - 10 * s} ${sh + 2 * s} Q${x - 26 * face * s} ${hip} ${x - 30 * face * s} ${gy - 6 * s} L${x - 8 * face * s} ${hip}Z" fill="${o.cape}" opacity=".95"/>`);
  // arms by pose
  const ax = x + 10 * face * s, ay = sh + 5 * s, arm = (dx, dy) => `<path d="M${ax} ${ay} l${dx * s} ${dy * s}" stroke="${cloth}" stroke-width="${6 * s}" stroke-linecap="round"/><circle cx="${ax + dx * s}" cy="${ay + dy * s}" r="${3 * s}" fill="${skin}"/>`, back = `<path d="M${x - 10 * face * s} ${ay} l${-3 * face * s} ${22 * s}" stroke="${darken(cloth, .12)}" stroke-width="${6 * s}" stroke-linecap="round"/><circle cx="${x - 13 * face * s}" cy="${ay + 22 * s}" r="${3 * s}" fill="${skin}"/>`;
  out.unshift(back);
  if (o.pose === 'point') out.push(arm(22 * face, -6)); else if (o.pose === 'raise') out.push(arm(8 * face, -26)); else if (o.pose === 'reach') out.push(arm(20 * face, 4)); else if (o.pose === 'run') out.push(arm(16 * face, -10)); else out.push(arm(3 * face, 22));
  // props in hand
  const hx2 = ax + (o.pose === 'point' ? 22 * face : o.pose === 'raise' ? 8 * face : o.pose === 'reach' ? 20 * face : 3 * face) * s, hy2 = ay + (o.pose === 'point' ? -6 : o.pose === 'raise' ? -26 : o.pose === 'reach' ? 4 : 22) * s;
  const prop = { gun: `<path d="M${hx2} ${hy2} h${9 * face * s} v${-3 * s} h${-9 * face * s}Z" fill="#222"/>`, sword: `<path d="M${hx2} ${hy2} l${4 * face * s} ${-34 * s}" stroke="#D8DCE2" stroke-width="${2.4 * s}"/><path d="M${hx2 - 4 * s} ${hy2 - 2 * s} h${8 * s}" stroke="#8A6B2E" stroke-width="${2.5 * s}"/>`, mic: `<path d="M${hx2} ${hy2} l${2 * face * s} ${-9 * s}" stroke="#333" stroke-width="${2 * s}"/><circle cx="${hx2 + 2 * face * s}" cy="${hy2 - 11 * s}" r="${3 * s}" fill="#555"/>`, lantern: `<rect x="${hx2 - 3 * s}" y="${hy2}" width="${6 * s}" height="${8 * s}" fill="#FFD27A" stroke="#5A4A2E"/><circle cx="${hx2}" cy="${hy2 + 4 * s}" r="${18 * s}" fill="#FFD27A" opacity=".18"/>`, phone: `<rect x="${hx2 - 2 * s}" y="${hy2 - 6 * s}" width="${4 * s}" height="${7 * s}" fill="#1E1E1E"/>`, flowers: `<circle cx="${hx2}" cy="${hy2 - 5 * s}" r="${4 * s}" fill="#E8553E"/><circle cx="${hx2 + 3 * s}" cy="${hy2 - 8 * s}" r="${3 * s}" fill="#F4B400"/>`, glass: `<path d="M${hx2 - 2 * s} ${hy2 - 8 * s} h${4 * s} l${-1 * s} ${6 * s} h${-2 * s}Z" fill="#F2E8CF" opacity=".9"/>`, book: `<rect x="${hx2 - 4 * s}" y="${hy2 - 4 * s}" width="${8 * s}" height="${6 * s}" fill="#7A2E2E"/>`, torch: `<path d="M${hx2} ${hy2} l0 ${-12 * s}" stroke="#5A3A21" stroke-width="${2.5 * s}"/><path d="M${hx2} ${hy2 - 12 * s} q${-4 * s} ${-6 * s} 0 ${-12 * s} q${4 * s} ${6 * s} 0 ${12 * s}" fill="#F4A13A"/><circle cx="${hx2}" cy="${hy2 - 16 * s}" r="${22 * s}" fill="#F4A13A" opacity=".15"/>` }[o.prop];
  if (prop) out.push(prop);
  // neck, head, hair, face
  out.push(`<rect x="${hx - 3 * s}" y="${hy + 6 * s}" width="${6 * s}" height="${6 * s}" fill="${darken(skin, .12)}"/><ellipse cx="${hx}" cy="${hy}" rx="${hr * .86}" ry="${hr}" fill="${skin}"/>`);
  const hc = L.hc, H = L.hair;
  if (o.costume === 'space' && o.helmet) out.push(`<circle cx="${hx}" cy="${hy}" r="${hr * 1.5}" fill="#BFE3F2" opacity=".35" stroke="#E6EAF0" stroke-width="${1.5 * s}"/>`);
  else if (H === 6) out.push(`<circle cx="${hx}" cy="${hy - 4 * s}" r="${hr * 1.15}" fill="${hc}"/><ellipse cx="${hx}" cy="${hy + 1 * s}" rx="${hr * .8}" ry="${hr * .8}" fill="${skin}"/>`);
  else if (H >= 7) out.push(`<path d="M${hx - hr} ${hy + (H === 7 ? 5 : 14) * s} Q${hx - hr * 1.1} ${hy - hr * 1.3} ${hx} ${hy - hr * 1.08} Q${hx + hr * 1.1} ${hy - hr * 1.3} ${hx + hr} ${hy + (H === 7 ? 5 : 14) * s} L${hx + hr * .7} ${hy - 2 * s} L${hx - hr * .7} ${hy - 2 * s}Z" fill="${hc}"/>`);
  else if (H >= 1) out.push(`<path d="M${hx - hr * .9} ${hy - 1 * s} Q${hx - hr} ${hy - hr * 1.2} ${hx} ${hy - hr * 1.08} Q${hx + hr} ${hy - hr * 1.2} ${hx + hr * .9} ${hy - 1 * s} Q${hx} ${hy - hr * .55} ${hx - hr * .9} ${hy - 1 * s}Z" fill="${hc}"/>`);
  out.push(`<circle cx="${hx + (face * 2.4 - 3) * s}" cy="${hy}" r="${1.1 * s}" fill="#2A221C"/><circle cx="${hx + (face * 2.4 + 3) * s}" cy="${hy}" r="${1.1 * s}" fill="#2A221C"/><path d="M${hx + (face * 2 - 2) * s} ${hy + 4.5 * s} q${2 * s} ${1.2 * s} ${4 * s} 0" stroke="${darken(skin, .4)}" stroke-width="${.8 * s}" fill="none"/>`);
  if (L.beard) out.push(`<path d="M${hx - hr * .75} ${hy + 1 * s} Q${hx} ${hy + hr * 1.5} ${hx + hr * .75} ${hy + 1 * s} Q${hx} ${hy + hr * .8} ${hx - hr * .75} ${hy + 1 * s}Z" fill="${hc}" opacity=".9"/>`);
  if (L.glasses) out.push(`<path d="M${hx + (face * 2.4 - 6) * s} ${hy} h${5 * s} m${2 * s} 0 h${5 * s}" stroke="#222" stroke-width="${.9 * s}"/>`);
  const hat = { cowboy: `<ellipse cx="${hx}" cy="${hy - hr * .7}" rx="${hr * 1.6}" ry="${hr * .32}" fill="#6B4A2B"/><path d="M${hx - hr * .75} ${hy - hr * .7} Q${hx - hr * .6} ${hy - hr * 1.7} ${hx} ${hy - hr * 1.5} Q${hx + hr * .6} ${hy - hr * 1.7} ${hx + hr * .75} ${hy - hr * .7}Z" fill="#7C5A35"/>`, helmet: `<path d="M${hx - hr * 1.15} ${hy - 1 * s} Q${hx} ${hy - hr * 2} ${hx + hr * 1.15} ${hy - 1 * s}Z" fill="#5C6A3E"/>`, crown: `<path d="M${hx - hr * .8} ${hy - hr * .8} l${hr * .3} ${-hr * .7} l${hr * .25} ${hr * .45} l${hr * .25} ${-hr * .6} l${hr * .25} ${hr * .6} l${hr * .25} ${-hr * .45} l${hr * .3} ${hr * .7}Z" fill="#E3B23C"/>`, fedora: `<ellipse cx="${hx}" cy="${hy - hr * .7}" rx="${hr * 1.35}" ry="${hr * .25}" fill="#2B2B2B"/><path d="M${hx - hr * .75} ${hy - hr * .7} L${hx - hr * .6} ${hy - hr * 1.5} L${hx + hr * .6} ${hy - hr * 1.5} L${hx + hr * .75} ${hy - hr * .7}Z" fill="#3A3A3A"/>`, tophat: `<ellipse cx="${hx}" cy="${hy - hr * .7}" rx="${hr * 1.2}" ry="${hr * .22}" fill="#1E1E1E"/><rect x="${hx - hr * .65}" y="${hy - hr * 2.2}" width="${hr * 1.3}" height="${hr * 1.5}" fill="#1E1E1E"/>`, band: `<path d="M${hx - hr * .85} ${hy - hr * .55} h${hr * 1.7}" stroke="#C62828" stroke-width="${2.2 * s}"/>`, hood: `<path d="M${hx - hr * 1.2} ${hy + hr} Q${hx - hr * 1.4} ${hy - hr * 1.6} ${hx} ${hy - hr * 1.5} Q${hx + hr * 1.4} ${hy - hr * 1.6} ${hx + hr * 1.2} ${hy + hr}" fill="${darken(cloth, .3)}"/>` }[o.hat];
  if (hat) out.push(hat);
  if (rim) out.push(`<ellipse cx="${hx + face * hr * .5}" cy="${hy}" rx="${hr * .3}" ry="${hr * .8}" fill="${rim}" opacity=".35"/>`);
  return `<g class="act">${out.join('')}</g>`;
}
// ---- the places ----
function skyRect(T, id) { return `<defs><linearGradient id="${id}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${T.skyT}"/><stop offset="1" stop-color="${T.skyB}"/></linearGradient></defs><rect width="${CW}" height="${CH}" fill="url(#${id})"/>`; }
function celestial(T, r, x = 60 + r() * 200) { return T.night ? `<circle cx="${x}" cy="${26 + r() * 16}" r="9" fill="#F2F0E6"/><circle cx="${x + 4}" cy="${24 + r() * 4}" r="8" fill="${T.skyT}" opacity=".35"/>${Array.from({ length: 22 }, () => `<circle cx="${r() * CW}" cy="${r() * 70}" r="${.5 + r() * .8}" fill="#fff" opacity="${.4 + r() * .6}"/>`).join('')}` : `<circle cx="${x}" cy="${T.tod === 0 ? 28 : 64}" r="${T.tod === 0 ? 13 : 18}" fill="${T.sun}" opacity=".95"/>`; }
function win(x, y, w, h, T, frame = '#5A4A3A') { return `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${T.night ? '#2E4570' : T.skyB}" stroke="${frame}" stroke-width="3"/>${T.night ? `<circle cx="${x + w * .7}" cy="${y + h * .3}" r="4" fill="#F2F0E6"/>` : ''}<path d="M${x + w / 2} ${y} v${h} M${x} ${y + h / 2} h${w}" stroke="${frame}" stroke-width="2"/>`; }
function lampGlow(x, y, c = '#FFD98A', r = 40) { return `<circle cx="${x}" cy="${y}" r="${r}" fill="${c}" opacity=".18"/><circle cx="${x}" cy="${y}" r="${r * .45}" fill="${c}" opacity=".25"/>`; }
function oldCar(x, y, c, era, face = 1) {
  return era < 1960 ? `<g><path d="M${x} ${y} h${60} v-10 q-6 -12 -16 -12 h-20 q-10 0 -14 10 h-10 q-4 0 -4 6Z" fill="${c}"/><circle cx="${x + 12}" cy="${y}" r="6" fill="#222"/><circle cx="${x + 48}" cy="${y}" r="6" fill="#222"/></g>`
    : `<g><path d="M${x} ${y} h${70} v-9 q0 -5 -6 -6 l-12 -2 l-10 -10 h-22 l-12 10 h-6 q-2 0 -2 4Z" fill="${c}"/><path d="M${x + 22} ${y - 25} l-9 9 h33 l-7 -9Z" fill="#BFD8F2" opacity=".8"/><circle cx="${x + 14}" cy="${y}" r="6" fill="#222"/><circle cx="${x + 56}" cy="${y}" r="6" fill="#222"/>${face ? `<circle cx="${x + 68}" cy="${y - 8}" r="2" fill="#FFE9A8"/>` : ''}</g>`;
}
// each setting: draws the place and returns { bg, gy (ground line), fg, anim (moving layer for trailers), slots }
const SC_DRAW = {
  diner: (T, r, P0) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#E9D8B4"/><rect y="14" width="${CW}" height="18" fill="#B23A3A"/><text x="160" y="27" text-anchor="middle" font-family="Barlow Condensed, sans-serif" font-weight="700" font-size="13" fill="#FFF6E0" letter-spacing="3">${esc(P0.sign || 'EAT · OPEN ALL NIGHT')}</text>${win(20, 34, 90, 54, T, '#C9C2B4')}${win(126, 34, 90, 54, T, '#C9C2B4')}<rect x="232" y="30" width="70" height="40" fill="#F2E8CF" stroke="#8A6B2E"/><text x="267" y="44" text-anchor="middle" font-size="7" font-family="Barlow, sans-serif" fill="#7A2E2E">PIE 35¢</text><text x="267" y="56" text-anchor="middle" font-size="7" font-family="Barlow, sans-serif" fill="#7A2E2E">COFFEE 10¢</text><rect y="112" width="${CW}" height="68" fill="#D9D2C6"/>${Array.from({ length: 16 }, (_, i) => `<rect x="${i * 20}" y="${112 + (i % 2) * 0}" width="10" height="68" fill="#2B2B2B" opacity=".08"/>`).join('')}<rect x="0" y="98" width="${CW}" height="16" fill="#C8553D"/><rect x="0" y="96" width="${CW}" height="4" fill="#E8E4DA"/>${[40, 100, 160, 220, 280].map(x => `<rect x="${x - 2}" y="114" width="4" height="22" fill="#9A9A9A"/><ellipse cx="${x}" cy="114" rx="9" ry="3" fill="#B23A3A"/>`).join('')}<path d="M60 92 q4 -6 8 0" stroke="#fff" opacity=".6" fill="none"/><rect x="56" y="90" width="10" height="7" fill="#F2F0E6"/>`, gy: 168 }),
  apartment: (T, r) => ({ bg: `<rect width="${CW}" height="${CH}" fill="${T.night ? '#B9A88E' : '#E6D8C0'}"/>${win(190, 26, 92, 74, T, '#F2EFE6')}${Array.from({ length: 5 }, (_, i) => `<rect x="${196 + i * 18}" y="${70 - (i % 3) * 10}" width="12" height="${30 + (i % 3) * 10}" fill="${T.night ? '#1C2A44' : '#8FA6BF'}" opacity=".7"/>`).join('')}<rect x="20" y="30" width="60" height="80" fill="#7A5236"/>${Array.from({ length: 12 }, (_, i) => `<rect x="${24 + (i % 6) * 9}" y="${34 + Math.floor(i / 6) * 38}" width="7" height="${28 + r() * 6}" fill="${['#C8553D', '#2C4F7C', '#2E5A3A', '#E3B23C', '#5B3A6E'][i % 5]}"/>`).join('')}<rect x="100" y="40" width="40" height="30" fill="#F2E8CF" stroke="#8A6B2E" stroke-width="3"/><path d="M106 64 l10 -12 l8 8 l6 -6 l6 10Z" fill="#5E7C78"/><rect y="136" width="${CW}" height="44" fill="#9A7650"/><ellipse cx="160" cy="160" rx="110" ry="14" fill="#7A2E2E" opacity=".55"/><path d="M96 136 h130 v-26 q0 -8 -8 -8 h-114 q-8 0 -8 8Z" fill="#5E7C78"/><rect x="244" y="88" width="3" height="48" fill="#3A3A3A"/><path d="M234 88 h24 l-6 -14 h-12Z" fill="#F2E8CF"/>${T.night ? lampGlow(246, 82) : ''}`, gy: 168 }),
  office: (T, r, P0) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#DCE2E6"/>${Array.from({ length: 3 }, (_, i) => `${win(20 + i * 100, 20, 80, 60, T, '#B9C2CA')}${Array.from({ length: 8 }, (_, k) => `<rect x="${20 + i * 100}" y="${22 + k * 7}" width="80" height="2" fill="#B9C2CA" opacity=".8"/>`).join('')}`).join('')}<rect y="118" width="${CW}" height="62" fill="#8E9AA4"/>${[30, 190].map(x => `<rect x="${x}" y="104" width="100" height="8" fill="#6B4A2B"/><rect x="${x + 6}" y="112" width="4" height="28" fill="#4A3A2A"/><rect x="${x + 90}" y="112" width="4" height="28" fill="#4A3A2A"/>${P0.era < 1980 ? `<rect x="${x + 34}" y="92" width="30" height="12" rx="2" fill="#3A3A3A"/><rect x="${x + 38}" y="84" width="22" height="9" fill="#F2F0E6"/>` : `<rect x="${x + 34}" y="78" width="34" height="24" fill="#222"/><rect x="${x + 36}" y="80" width="30" height="20" fill="#5579A8"/><rect x="${x + 48}" y="102" width="6" height="3" fill="#222"/>`}`).join('')}<rect x="146" y="70" width="16" height="40" fill="#BFE3F2" opacity=".8"/><rect x="146" y="110" width="16" height="10" fill="#E6EAF0"/>`, gy: 170 }),
  street: (T, r, P0) => { const bld = Array.from({ length: 7 }, (_, i) => { const h = 70 + r() * 70, x = i * 48 - 8, col = ['#B9765A', '#C9A27A', '#8C9AA6', '#A86E5E', '#D2B48C', '#7E8C74'][i % 6]; return `<rect x="${x}" y="${CH - 40 - h}" width="46" height="${h}" fill="${T.night ? darken(col, .35) : col}"/>${Array.from({ length: Math.floor(h / 20) * 3 }, (_, k) => `<rect x="${x + 6 + (k % 3) * 13}" y="${CH - 34 - h + Math.floor(k / 3) * 20}" width="8" height="11" fill="${T.night ? (r() < .6 ? '#FFE09A' : '#2E3A55') : '#DCEBF5'}"/>`).join('')}<rect x="${x + 4}" y="${CH - 58}" width="38" height="6" fill="${['#C62828', '#2E5A3A', '#2C4F7C'][i % 3]}"/>`; }).join(''); return { bg: `${skyRect(T, 'st' + P0.uid)}${celestial(T, r)}${bld}<rect y="${CH - 40}" width="${CW}" height="12" fill="#B9B5AE"/><rect y="${CH - 28}" width="${CW}" height="28" fill="#5A5A5E"/>${Array.from({ length: 8 }, (_, i) => `<rect x="${i * 44}" y="${CH - 14}" width="22" height="2" fill="#F2EFE6" opacity=".7"/>`).join('')}<rect x="250" y="${CH - 96}" width="3" height="56" fill="#2B2B2B"/><circle cx="251" cy="${CH - 98}" r="5" fill="${T.night ? '#FFE09A' : '#DDD'}"/>${T.night ? lampGlow(251, CH - 98) : ''}`, gy: CH - 30, anim: `<g>${oldCar(-80, CH - 8, ['#C62828', '#2C4F7C', '#E3B23C'][Math.floor(r() * 3)], P0.era)}<animateTransform attributeName="transform" type="translate" from="0 0" to="480 0" dur="5s" repeatCount="indefinite"/></g>` }; },
  car: (T, r, P0) => ({ bg: `${skyRect(T, 'cr' + P0.uid)}${celestial(T, r)}<g class="road">${Array.from({ length: 10 }, (_, i) => `<rect x="${i * 40}" y="${60 + r() * 20}" width="${10 + r() * 30}" height="${40}" fill="${T.night ? '#1C2A44' : '#7E9A6E'}" opacity=".8"/>`).join('')}</g><rect y="98" width="${CW}" height="20" fill="#6B6B70"/><path d="M0 0 h${CW} v34 h-40 l-30 70 h-180 l-30 -70 h-40Z" fill="#2B2B30"/><path d="M0 104 h${CW} v76 h-${CW}Z" fill="#3A3A40"/><circle cx="96" cy="150" r="22" fill="none" stroke="#1E1E22" stroke-width="7"/><rect x="200" y="122" width="60" height="14" rx="3" fill="#1E1E22"/>${Array.from({ length: 3 }, (_, i) => `<circle cx="${212 + i * 18}" cy="129" r="3" fill="${T.night ? '#7FE0A0' : '#9A9A9A'}"/>`).join('')}<rect x="146" y="38" width="32" height="10" rx="2" fill="#1E1E22"/>`, gy: 186, slots: [110, 214], sit: 1, anim: `<g>${Array.from({ length: 6 }, (_, i) => `<rect x="${i * 70}" y="104" width="30" height="3" fill="#F2EFE6" opacity=".7"/>`).join('')}<animateTransform attributeName="transform" type="translate" from="0 0" to="-140 0" dur="1.2s" repeatCount="indefinite"/></g>` }),
  rooftop: (T, r, P0) => ({ bg: `${skyRect(T, 'rf' + P0.uid)}${celestial(T, r, 260)}${Array.from({ length: 14 }, (_, i) => { const h = 30 + r() * 70; return `<rect x="${i * 24 - 4}" y="${120 - h}" width="22" height="${h + 10}" fill="${T.night ? '#1C2A44' : '#8FA6BF'}"/>${T.night ? Array.from({ length: 4 }, (_, k) => `<rect x="${i * 24 + 3 + (k % 2) * 8}" y="${124 - h + Math.floor(k / 2) * 12}" width="4" height="5" fill="#FFE09A" opacity="${r() < .6 ? .9 : .2}"/>`).join('') : ''}`; }).join('')}<rect y="122" width="${CW}" height="58" fill="#7A6E66"/><rect y="118" width="${CW}" height="6" fill="#9A8E86"/><path d="M262 122 v-40 h28 v40 M260 82 q16 -16 32 0" stroke="#5A4A3A" stroke-width="3" fill="#8A6B4A"/>`, gy: 166 }),
  westtown: (T, r, P0) => ({ bg: `${skyRect(T, 'wt' + P0.uid)}${celestial(T, r, 250)}<path d="M0 100 L40 70 L70 70 L90 100 M200 100 L230 62 L280 62 L310 100" fill="#C9875A"/>${['SALOON', 'BANK', 'HOTEL', 'GENERAL STORE'].map((n, i) => `<rect x="${i * 82}" y="${50 + (i % 2) * 8}" width="74" height="${70 - (i % 2) * 8}" fill="${['#8C5A35', '#A0693E', '#7A4A2B', '#94643E'][i]}"/><rect x="${i * 82}" y="${50 + (i % 2) * 8}" width="74" height="10" fill="#5A3A21"/><text x="${i * 82 + 37}" y="${58 + (i % 2) * 8}" text-anchor="middle" font-size="7" font-family="Barlow Condensed, sans-serif" font-weight="700" fill="#F2E8CF" letter-spacing="1">${n}</text><rect x="${i * 82 + 26}" y="96" width="22" height="24" fill="#3A2618"/>${win(i * 82 + 6, 70, 14, 14, T, '#5A3A21')}`).join('')}<rect y="120" width="${CW}" height="60" fill="#D8B27E"/><path d="M0 132 Q160 126 320 136" stroke="#C49A62" stroke-width="5" fill="none"/><rect x="250" y="112" width="40" height="3" fill="#5A3A21"/><rect x="252" y="112" width="3" height="14" fill="#5A3A21"/><rect x="285" y="112" width="3" height="14" fill="#5A3A21"/>`, gy: 166, hat: 'cowboy', anim: `<g opacity=".5">${Array.from({ length: 3 }, (_, i) => `<circle cx="${40 + i * 120}" cy="150" r="${6 + i * 2}" fill="#E6C99A"/>`).join('')}<animateTransform attributeName="transform" type="translate" from="-40 0" to="80 -6" dur="6s" repeatCount="indefinite"/></g>` }),
  saloon: (T, r) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#8A5A35"/>${Array.from({ length: 16 }, (_, i) => `<rect x="${i * 20}" y="0" width="1.5" height="110" fill="#5A3A21" opacity=".6"/>`).join('')}<rect x="20" y="30" width="200" height="6" fill="#5A3A21"/>${Array.from({ length: 18 }, (_, i) => `<rect x="${26 + i * 11}" y="${16 + (i % 3) * 2}" width="5" height="${14 - (i % 3) * 2}" rx="1" fill="${['#2E5A3A', '#7A2E2E', '#C48A4A', '#5579A8'][i % 4]}"/>`).join('')}<rect x="236" y="20" width="70" height="44" fill="#F2E8CF" opacity=".85"/><text x="271" y="38" text-anchor="middle" font-size="8" font-family="Barlow Condensed, sans-serif" font-weight="700" fill="#5A3A21">WANTED</text><circle cx="271" cy="50" r="7" fill="#C9A27A"/><rect x="0" y="100" width="240" height="16" fill="#5A3A21"/><rect x="0" y="116" width="240" height="40" fill="#6B4A2B"/><rect y="150" width="${CW}" height="30" fill="#A87A4E"/><path d="M160 8 v10" stroke="#3A2618"/><g>${Array.from({ length: 5 }, (_, i) => `<circle cx="${148 + i * 6}" cy="20" r="2.5" fill="#FFE09A"/>`).join('')}</g>${lampGlow(160, 20, '#FFD27A', 60)}<rect x="96" y="92" width="8" height="10" fill="#C48A4A" opacity=".8"/>`, gy: 170, hat: 'cowboy' }),
  desert: (T, r, P0) => ({ bg: `${skyRect(T, 'ds' + P0.uid)}${celestial(T, r)}<path d="M20 120 v-40 h50 v40 M220 120 v-56 h44 v56" fill="#B5653C"/><path d="M0 120 Q80 110 160 118 T320 114 V180 H0Z" fill="#E0B07A"/>${Array.from({ length: 4 }, (_, i) => `<g transform="translate(${30 + i * 80 + r() * 20} ${132 + r() * 20})"><rect x="-3" y="-26" width="6" height="26" rx="3" fill="#4E7A3E"/><rect x="-11" y="-18" width="5" height="10" rx="2.5" fill="#4E7A3E"/><rect x="6" y="-22" width="5" height="12" rx="2.5" fill="#4E7A3E"/></g>`).join('')}`, gy: 172, hat: 'cowboy', anim: `<g opacity=".35"><path d="M-40 150 q20 -6 40 0 t40 0" stroke="#F2E8CF" fill="none" stroke-width="2"/><animateTransform attributeName="transform" type="translate" from="0 0" to="400 0" dur="7s" repeatCount="indefinite"/></g>` }),
  forest: (T, r, P0) => ({ bg: `${skyRect(T, 'fo' + P0.uid)}${celestial(T, r)}${[0, 1, 2].map(k => Array.from({ length: 12 }, (_, i) => { const x = i * 30 + r() * 20 - 10 + k * 8, h = 70 + r() * 50 + k * 20, c = [T.night ? '#2E4A3E' : '#7FA36E', T.night ? '#24402F' : '#5E8A50', T.night ? '#1A3324' : '#3E6B3A'][k]; return `<rect x="${x - 2}" y="${150 - h * .3}" width="5" height="${h * .3 + 10}" fill="#5A3A21"/><path d="M${x} ${150 - h} l${16 + k * 3} ${h * .72} h${-32 - k * 6}Z" fill="${c}"/>`; }).join('')).join('')}<rect y="150" width="${CW}" height="30" fill="${T.night ? '#2A3A2A' : '#6E8A50'}"/><path d="M120 180 Q150 160 170 150 Q190 160 220 180Z" fill="#B9A07A" opacity=".7"/><rect width="${CW}" height="${CH}" fill="#F2F0E6" opacity="${T.night ? .06 : .12}"/>`, gy: 172, anim: T.night ? `<g>${Array.from({ length: 12 }, () => `<circle cx="${r() * CW}" cy="${80 + r() * 80}" r="1.4" fill="#E6F28A"><animate attributeName="opacity" values="0;1;0" dur="${1.5 + r() * 2}s" repeatCount="indefinite"/></circle>`).join('')}</g>` : `<rect width="${CW}" height="${CH}" fill="#FFFFFF" opacity=".08"><animate attributeName="opacity" values=".04;.14;.04" dur="5s" repeatCount="indefinite"/></rect>` }),
  beach: (T, r, P0) => ({ bg: `${skyRect(T, 'bc' + P0.uid)}${celestial(T, r, 230)}<rect y="92" width="${CW}" height="40" fill="${T.night ? '#2A4A7A' : '#3F8FBF'}"/><rect y="92" width="${CW}" height="3" fill="#BFE3F2" opacity=".6"/><rect y="128" width="${CW}" height="52" fill="#EAD7A6"/><path d="M250 128 v-38" stroke="#5A3A21" stroke-width="2"/><path d="M226 92 q24 -24 48 0Z" fill="#E8553E"/><path d="M226 92 q12 -24 24 0 q12 -24 24 0" fill="#FFF6E0" opacity=".6"/><path d="M20 70 q4 -4 8 0 q4 -4 8 0" stroke="#2B2B2B" fill="none"/><path d="M60 58 q3 -3 6 0 q3 -3 6 0" stroke="#2B2B2B" fill="none"/>`, gy: 170, anim: `<g>${Array.from({ length: 6 }, (_, i) => `<path d="M${i * 70 - 60} ${126} q18 -6 36 0" stroke="#FFFFFF" stroke-width="2" fill="none" opacity=".8"/>`).join('')}<animateTransform attributeName="transform" type="translate" values="0 0;24 -2;0 0" dur="4s" repeatCount="indefinite"/></g>` }),
  mountains: (T, r, P0) => ({ bg: `${skyRect(T, 'mt' + P0.uid)}${celestial(T, r)}<path d="M0 120 L70 40 L120 90 L170 30 L240 100 L280 60 L320 96 V180 H0Z" fill="${T.night ? '#3E4E6E' : '#7E8CA6'}"/><path d="M58 54 L70 40 L82 54 L76 52 L70 58 L64 52Z M158 44 L170 30 L182 44 L176 42 L170 48 L164 42Z" fill="#F2F4F8"/><path d="M0 140 Q100 120 200 138 T320 132 V180 H0Z" fill="${T.night ? '#2A3A2A' : '#5E8A50'}"/>${Array.from({ length: 10 }, (_, i) => `<path d="M${i * 34 + 6} 150 l8 -24 l8 24Z" fill="${T.night ? '#1A3324' : '#2E5A3A'}"/>`).join('')}`, gy: 172, anim: `<g opacity=".7"><ellipse cx="60" cy="54" rx="40" ry="8" fill="#FFFFFF"/><ellipse cx="240" cy="40" rx="32" ry="6" fill="#FFFFFF"/><animateTransform attributeName="transform" type="translate" from="-30 0" to="40 0" dur="9s" repeatCount="indefinite"/></g>` }),
  bridge: (T, r, P0) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#2A3442"/><path d="M40 14 h240 l20 60 h-280Z" fill="#0E1426"/>${Array.from({ length: 40 }, () => `<circle cx="${50 + r() * 220}" cy="${18 + r() * 52}" r="${.5 + r()}" fill="#fff"/>`).join('')}<circle cx="${110 + r() * 100}" cy="44" r="18" fill="${['#C8553D', '#3F8FBF', '#E3B23C', '#7E5AA6'][Math.floor(r() * 4)]}"/><path d="M40 14 h240 l20 60 h-280Z" fill="none" stroke="#8A97AA" stroke-width="4"/><rect y="104" width="${CW}" height="76" fill="#3A4656"/>${[30, 200].map(x => `<rect x="${x}" y="96" width="90" height="22" rx="4" fill="#4A5868"/>${Array.from({ length: 10 }, (_, i) => `<rect x="${x + 6 + i * 8}" y="${101 + (i % 2) * 7}" width="5" height="4" fill="${['#7FE0A0', '#F4B400', '#E8553E', '#5AC8FA'][i % 4]}"/>`).join('')}`).join('')}<path d="M150 150 h30 v-30 q-15 -10 -30 0Z" fill="#5A6878"/>`, gy: 172, costume: 'space', anim: `<g>${Array.from({ length: 10 }, (_, i) => `<rect x="${36 + (i % 5) * 8 + (i > 4 ? 170 : 0)}" y="${101 + (i % 2) * 7}" width="5" height="4" fill="#FFFFFF"><animate attributeName="opacity" values="0;.9;0" dur="${.8 + (i % 4) * .4}s" repeatCount="indefinite"/></rect>`).join('')}</g>` }),
  planet: (T, r, P0) => { const sk = ['#3A2A5C', '#5C2A3A', '#1E4A5C'][Math.floor(r() * 3)]; return { bg: `<rect width="${CW}" height="${CH}" fill="${sk}"/><circle cx="70" cy="40" r="22" fill="#E3B23C" opacity=".9"/><circle cx="250" cy="30" r="10" fill="#BFE3F2"/>${Array.from({ length: 30 }, () => `<circle cx="${r() * CW}" cy="${r() * 80}" r=".8" fill="#fff"/>`).join('')}<path d="M0 120 L40 96 L80 118 L130 84 L190 120 L240 92 L320 122 V180 H0Z" fill="${mixC(sk, '#C8553D', .5)}"/><path d="M0 150 Q160 130 320 150 V180 H0Z" fill="${mixC(sk, '#E3B23C', .45)}"/><rect x="230" y="136" width="40" height="14" rx="3" fill="#D9DDE3"/><circle cx="238" cy="152" r="5" fill="#555"/><circle cx="262" cy="152" r="5" fill="#555"/>`, gy: 172, costume: 'space', helmet: 1 }; },
  castle: (T, r) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#8C8478"/>${[40, 120, 200, 280].map(x => `<path d="M${x - 30} 130 V40 Q${x} 6 ${x + 30} 40 V130" fill="none" stroke="#6B645A" stroke-width="8"/>`).join('')}${Array.from({ length: 30 }, (_, i) => `<rect x="${(i % 10) * 32 + (Math.floor(i / 10) % 2) * 16}" y="${Math.floor(i / 10) * 18 + 70}" width="30" height="16" fill="none" stroke="#7A7268" stroke-width=".8"/>`).join('')}${[70, 250].map(x => `<rect x="${x - 10}" y="20" width="20" height="56" fill="${['#7A2E2E', '#2C4F7C'][x > 100 ? 1 : 0]}"/><path d="M${x - 10} 76 l10 -8 l10 8" fill="#8C8478"/><rect x="${x - 2}" y="${84}" width="4" height="12" fill="#5A3A21"/><path d="M${x} 84 q-5 -7 0 -14 q5 7 0 14" fill="#F4A13A"/>${lampGlow(x, 80, '#F4A13A', 34)}`).join('')}<path d="M140 130 v-50 q20 -18 40 0 v50Z" fill="#7A2E2E"/><rect x="144" y="70" width="32" height="12" fill="#E3B23C"/><rect y="130" width="${CW}" height="50" fill="#6B645A"/><path d="M150 180 L160 130 L170 180Z" fill="#7A2E2E" opacity=".7"/>`, gy: 172, costume: 'robe' }),
  battlefield: (T, r, P0) => ({ bg: `${skyRect(T, 'bf' + P0.uid)}<rect width="${CW}" height="${CH}" fill="#9A9A86" opacity=".35"/><path d="M0 110 Q60 100 120 108 T240 104 T320 110 V180 H0Z" fill="#6E6A50"/><path d="M200 104 h50 l6 -10 h-20 v-6 h30 v4 h-8 l4 12 h10 v10 h-72Z" fill="#4A4A3A"/>${Array.from({ length: 16 }, (_, i) => `<path d="M${i * 20} 128 l6 -6 l6 6 l6 -6" stroke="#3A3A2E" fill="none"/>`).join('')}<rect y="134" width="${CW}" height="46" fill="#5A4E3A"/>${Array.from({ length: 10 }, (_, i) => `<rect x="${i * 32}" y="130" width="28" height="8" rx="2" fill="#8C7A5A"/>`).join('')}`, gy: 172, costume: 'uniform', hat: 'helmet', anim: `<g><circle cx="${80 + r() * 160}" cy="40" r="4" fill="#FFE09A"><animate attributeName="cy" values="60;20;70" dur="3s" repeatCount="indefinite"/><animate attributeName="opacity" values="0;1;0" dur="3s" repeatCount="indefinite"/></circle><g opacity=".5"><ellipse cx="60" cy="96" rx="40" ry="14" fill="#C9C2B4"/><animateTransform attributeName="transform" type="translate" from="0 0" to="60 -10" dur="6s" repeatCount="indefinite"/></g></g>` }),
  stage: (T, r) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#3A1E2E"/><path d="M0 0 h50 q-10 70 0 140 h-50Z M320 0 h-50 q10 70 0 140 h50Z" fill="#B23A3A"/><path d="M0 0 h${CW} v18 q-160 14 -${CW} 0Z" fill="#9A2E2E"/><rect y="138" width="${CW}" height="12" fill="#8A6B4A"/><rect y="150" width="${CW}" height="30" fill="#2A1E26"/>${Array.from({ length: 22 }, (_, i) => `<circle cx="${i * 15 + 6}" cy="${170 + (i % 2) * 4}" r="7" fill="#1A1218"/>`).join('')}${Array.from({ length: 10 }, (_, i) => `<circle cx="${20 + i * 31}" cy="140" r="2" fill="#FFE09A"/>`).join('')}`, gy: 140, anim: `<g><path d="M80 0 L40 140 L120 140Z" fill="#FFF6E0" opacity=".22"><animateTransform attributeName="transform" type="rotate" values="-8 80 0;8 80 0;-8 80 0" dur="4s" repeatCount="indefinite"/></path><path d="M240 0 L200 140 L280 140Z" fill="#FFF6E0" opacity=".22"><animateTransform attributeName="transform" type="rotate" values="8 240 0;-8 240 0;8 240 0" dur="4s" repeatCount="indefinite"/></path></g>` }),
  ballroom: (T, r) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#E8D8B0"/>${[60, 160, 260].map(x => `<rect x="${x - 26}" y="10" width="52" height="96" rx="26" fill="${T.night ? '#2E4570' : '#BFD8F2'}" stroke="#C9A24A" stroke-width="3"/>`).join('')}${[110, 210].map(x => `<path d="M${x} 0 v14" stroke="#C9A24A"/><path d="M${x - 16} 14 h32 l-6 10 h-20Z" fill="#E3B23C"/>${Array.from({ length: 5 }, (_, i) => `<circle cx="${x - 12 + i * 6}" cy="26" r="1.8" fill="#FFF6E0"/>`).join('')}${lampGlow(x, 22, '#FFE9A8', 40)}`).join('')}<rect y="122" width="${CW}" height="58" fill="#C9A27A"/>${Array.from({ length: 8 }, (_, i) => `<path d="M${i * 40} 122 l40 58" stroke="#A8865F" opacity=".5"/>`).join('')}`, gy: 166, dress: 1, costume: 'suit' }),
  classroom: (T, r) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#E6E0CC"/><rect x="40" y="22" width="180" height="70" fill="#2E4A3A" stroke="#8A6B4A" stroke-width="5"/><path d="M56 40 q20 -8 40 0 M60 56 h70 M60 70 h40 l10 -8 l10 8" stroke="#F2F0E6" fill="none" stroke-width="1.5"/><text x="170" y="48" font-size="10" font-family="Barlow, sans-serif" fill="#F2F0E6">E = mc²</text>${win(240, 24, 60, 60, T, '#C9C2B4')}<rect y="128" width="${CW}" height="52" fill="#B59A7A"/>${[40, 140, 240].map(x => `<rect x="${x}" y="120" width="56" height="6" fill="#8A6B4A"/><rect x="${x + 4}" y="126" width="3" height="20" fill="#555"/><rect x="${x + 49}" y="126" width="3" height="20" fill="#555"/>`).join('')}`, gy: 168 }),
  hospital: (T, r) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#E6EEF0"/>${win(220, 24, 76, 60, T, '#DDE5E8')}<rect x="30" y="94" width="150" height="14" rx="4" fill="#F2F4F8"/><rect x="30" y="84" width="40" height="12" rx="4" fill="#FFFFFF"/><rect x="32" y="108" width="4" height="30" fill="#9AA6AE"/><rect x="174" y="108" width="4" height="30" fill="#9AA6AE"/><rect x="190" y="40" width="34" height="26" rx="2" fill="#2A3442"/><path d="M194 54 h6 l3 -8 l4 14 l3 -6 h10" stroke="#7FE0A0" fill="none" stroke-width="1.5"/><rect y="140" width="${CW}" height="40" fill="#C9D3D6"/><path d="M0 0 v130 M0 4 h12" stroke="#9AA6AE"/><path d="M8 4 q6 60 0 120 q8 -60 16 -120Z" fill="#BFE3F2" opacity=".7"/>`, gy: 172, anim: `<path d="M194 54 h6 l3 -8 l4 14 l3 -6 h10" stroke="#B9FFD0" fill="none" stroke-width="2" stroke-dasharray="40 200"><animate attributeName="stroke-dashoffset" from="240" to="0" dur="1.4s" repeatCount="indefinite"/></path>` }),
  interrogation: (T, r) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#9AA09A"/><rect x="200" y="24" width="100" height="60" fill="#2A3036" stroke="#5A605A" stroke-width="4"/><path d="M210 34 l30 40" stroke="#FFFFFF" opacity=".15" stroke-width="10"/><path d="M160 0 v24" stroke="#2B2B2B"/><path d="M146 24 h28 l-4 -10 h-20Z" fill="#3A3A3A"/><path d="M146 24 L90 150 L230 150 L174 24Z" fill="#FFF6D0" opacity=".22"/><rect x="96" y="112" width="128" height="8" fill="#5A5A5E"/><rect x="104" y="120" width="4" height="34" fill="#3A3A3E"/><rect x="212" y="120" width="4" height="34" fill="#3A3A3E"/><rect y="150" width="${CW}" height="30" fill="#7A807A"/><rect x="150" y="106" width="20" height="6" fill="#F2F0E6"/>`, gy: 172, anim: `<path d="M146 24 L90 150 L230 150 L174 24Z" fill="#FFF6D0" opacity=".1"><animate attributeName="opacity" values=".06;.16;.1;.18;.06" dur="2.6s" repeatCount="indefinite"/></path>` }),
  courtroom: (T, r) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#C9A27A"/>${Array.from({ length: 10 }, (_, i) => `<rect x="${i * 32}" y="0" width="30" height="110" fill="#B5895E" stroke="#8A6B4A"/>`).join('')}<rect x="110" y="40" width="100" height="56" fill="#6B4A2B"/><rect x="104" y="34" width="112" height="8" fill="#5A3A21"/><circle cx="160" cy="18" r="12" fill="#E3B23C" opacity=".8"/><path d="M30 20 v70" stroke="#5A3A21" stroke-width="2"/><rect x="31" y="20" width="22" height="14" fill="#2C4F7C"/><rect y="110" width="${CW}" height="70" fill="#8A6B4A"/><rect x="0" y="116" width="${CW}" height="6" fill="#6B4A2B"/>`, gy: 170, costume: 'suit' }),
  haunted: (T, r) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#5A5E6E"/>${win(200, 18, 60, 80, Object.assign({}, T, { night: true }), '#3A3A44')}<path d="M0 180 L90 60 h30 L30 180Z" fill="#4A4A56"/>${Array.from({ length: 8 }, (_, i) => `<rect x="${12 + i * 11}" y="${170 - i * 14}" width="30" height="4" fill="#3A3A44"/>`).join('')}${[140, 172].map((x, i) => `<rect x="${x}" y="30" width="24" height="32" fill="#3A2E28" stroke="#C9A24A" stroke-width="2"/><circle cx="${x + 12}" cy="42" r="6" fill="#8A7A6A"/>`).join('')}<rect y="150" width="${CW}" height="30" fill="#3E3A44"/><path d="M286 110 v-20 m-6 0 h12" stroke="#C9A24A" stroke-width="2"/>${[280, 286, 292].map(x => `<rect x="${x - 1}" y="84" width="2" height="6" fill="#F2F0E6"/><path d="M${x} 84 q-2 -4 0 -7 q2 3 0 7" fill="#F4A13A"/>`).join('')}${lampGlow(286, 80, '#F4A13A', 40)}<path d="M200 18 L170 160 L260 160 L260 18Z" fill="#BFD8F2" opacity=".12"/>`, gy: 172, anim: `<g><path d="M120 70 q14 -20 28 0 v34 l-5 -5 l-5 5 l-4 -5 l-5 5 l-4 -5 l-5 5Z" fill="#F2F4F8" opacity="0"><animate attributeName="opacity" values="0;0;.55;0;0" dur="5s" repeatCount="indefinite"/></path><rect width="${CW}" height="${CH}" fill="#000"><animate attributeName="opacity" values="0;0;.35;0;0;.2;0" dur="3.5s" repeatCount="indefinite"/></rect></g>` }),
  kitchen: (T, r) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#F2E8D0"/>${Array.from({ length: 4 }, (_, i) => `<rect x="${20 + i * 46}" y="16" width="42" height="40" fill="#5E8A7A" stroke="#4A6E62"/><circle cx="${36 + i * 46}" cy="44" r="2" fill="#E3B23C"/>`).join('')}${win(220, 18, 70, 54, T, '#FFFFFF')}<rect x="20" y="96" width="290" height="10" fill="#E6E0CC"/><rect x="20" y="106" width="290" height="44" fill="#5E8A7A"/><rect x="70" y="80" width="26" height="16" rx="3" fill="#7A2E2E"/><path d="M76 78 q4 -10 8 0 M84 76 q4 -10 8 0" stroke="#FFFFFF" opacity=".6" fill="none"/><rect x="250" y="60" width="0" height="0"/><rect y="150" width="${CW}" height="30" fill="#D9C9A8"/>${Array.from({ length: 10 }, (_, i) => `<rect x="${i * 32}" y="150" width="16" height="30" fill="#C9B998" opacity=".6"/>`).join('')}`, gy: 172, anim: `<g opacity=".7"><path d="M78 76 q4 -10 0 -18 q-4 -8 0 -16" stroke="#FFFFFF" fill="none" stroke-width="2"/><animateTransform attributeName="transform" type="translate" values="0 0;2 -6;0 -12" dur="2s" repeatCount="indefinite"/><animate attributeName="opacity" values=".7;0" dur="2s" repeatCount="indefinite"/></g>` }),
  dojo: (T, r) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#E8DCC0"/>${Array.from({ length: 6 }, (_, i) => `<rect x="${i * 56}" y="0" width="6" height="130" fill="#6B4A2B"/>${Array.from({ length: 3 }, (_, k) => `<rect x="${i * 56 + 10}" y="${10 + k * 36}" width="40" height="30" fill="#F6EEDC" stroke="#C9B48A"/>`).join('')}`).join('')}<rect x="120" y="14" width="80" height="54" fill="#F6EEDC"/><path d="M150 22 q10 6 0 16 q-10 10 4 22 M168 24 v34 M176 34 q-6 10 4 16" stroke="#1E1E1E" stroke-width="3" fill="none"/><circle cx="186" cy="56" r="4" fill="#C62828"/><rect y="130" width="${CW}" height="50" fill="#C9A27A"/>${Array.from({ length: 8 }, (_, i) => `<rect x="${i * 40}" y="130" width="40" height="50" fill="none" stroke="#A8865F"/>`).join('')}`, gy: 170, costume: 'gi', hat: 'band' }),
  skyline: (T, r, P0) => ({ bg: `${skyRect(T, 'sk' + P0.uid)}${celestial(T, r, 270)}${Array.from({ length: 12 }, (_, i) => { const h = 50 + r() * 100, x = i * 28 - 6; return `<rect x="${x}" y="${CH - h}" width="24" height="${h}" fill="${T.night ? '#1C2A44' : '#6E86A6'}"/>${Array.from({ length: Math.floor(h / 14) * 2 }, (_, k) => `<rect x="${x + 4 + (k % 2) * 9}" y="${CH - h + 6 + Math.floor(k / 2) * 14}" width="5" height="7" fill="${T.night ? (r() < .6 ? '#FFE09A' : '#2E3A55') : '#BFD8F2'}"/>`).join('')}`; }).join('')}`, gy: 110, fly: 1, anim: `<g opacity=".8">${Array.from({ length: 6 }, (_, i) => `<path d="M${-40 - i * 30} ${40 + i * 10} h30" stroke="#FFFFFF" stroke-width="1.5"/>`).join('')}<animateTransform attributeName="transform" type="translate" from="0 0" to="420 0" dur="1.6s" repeatCount="indefinite"/></g>` }),
  ring: (T, r) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#1E2430"/>${Array.from({ length: 30 }, (_, i) => `<circle cx="${(i % 15) * 22 + 6}" cy="${60 + Math.floor(i / 15) * 16}" r="7" fill="#2E3644"/>`).join('')}<path d="M80 0 L40 120 L280 120 L240 0Z" fill="#FFF6E0" opacity=".12"/><rect y="120" width="${CW}" height="60" fill="#3F6EA6"/><rect y="118" width="${CW}" height="4" fill="#F2F0E6"/>${[94, 104, 114].map((y, i) => `<path d="M0 ${y} h${CW}" stroke="${['#C62828', '#F2F0E6', '#2C4F7C'][i]}" stroke-width="2.5"/>`).join('')}<rect x="12" y="84" width="8" height="40" fill="#C9C2B4"/><rect x="300" y="84" width="8" height="40" fill="#C9C2B4"/>`, gy: 166, anim: `<g>${Array.from({ length: 8 }, () => `<circle cx="${r() * CW}" cy="${54 + r() * 30}" r="3" fill="#FFFFFF" opacity="0"><animate attributeName="opacity" values="0;0;1;0" dur="${2 + r() * 2}s" repeatCount="indefinite"/></circle>`).join('')}</g>` }),
  lab: (T, r) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#D6E2E6"/>${[20, 100, 180].map(x => `<rect x="${x}" y="22" width="64" height="44" rx="3" fill="#1E2A38"/><path d="M${x + 6} ${52} q10 -16 20 -4 t20 -8 t14 6" stroke="#5AC8FA" fill="none"/>${Array.from({ length: 3 }, (_, i) => `<rect x="${x + 6}" y="${28 + i * 6}" width="${16 + r() * 30}" height="2" fill="#7FE0A0"/>`).join('')}`).join('')}<rect x="20" y="100" width="280" height="10" fill="#9AA6AE"/>${[50, 90, 130, 240].map((x, i) => `<path d="M${x - 6} 100 l2 -16 h8 l2 16Z" fill="${['#7FE0A0', '#E8553E', '#5AC8FA', '#F4B400'][i]}" opacity=".8"/><rect x="${x - 3}" y="78" width="6" height="8" fill="#C9D3D6"/>`).join('')}<rect x="262" y="40" width="40" height="60" rx="4" fill="#5A6878"/><circle cx="282" cy="60" r="10" fill="#5AC8FA" opacity=".6"/><rect y="140" width="${CW}" height="40" fill="#B9C6CC"/>`, gy: 172, anim: `<circle cx="282" cy="60" r="10" fill="#B9F0FF"><animate attributeName="r" values="6;14;6" dur="2s" repeatCount="indefinite"/><animate attributeName="opacity" values=".8;.2;.8" dur="2s" repeatCount="indefinite"/></circle>` }),
  train: (T, r, P0) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#7A4A35"/>${[20, 120, 220].map(x => `<rect x="${x}" y="24" width="80" height="58" rx="8" fill="${T.night ? '#1C2A44' : T.skyB}"/>`).join('')}<rect y="110" width="${CW}" height="70" fill="#5A3A28"/>${[40, 160, 260].map(x => `<rect x="${x}" y="100" width="56" height="40" rx="5" fill="#8C2E2E"/><rect x="${x}" y="96" width="56" height="10" rx="4" fill="#A83A3A"/>`).join('')}<rect y="0" width="${CW}" height="14" fill="#5A3A28"/>${[60, 180, 280].map(x => `<circle cx="${x}" cy="10" r="4" fill="#FFE09A"/>`).join('')}`, gy: 172, sit: 1, slots: [90, 210], anim: `<g>${[20, 120, 220].map(x => `<clipPath id="tw${x}${P0.uid}"><rect x="${x}" y="24" width="80" height="58" rx="8"/></clipPath><g clip-path="url(#tw${x}${P0.uid})"><g>${Array.from({ length: 8 }, (_, i) => `<rect x="${x + i * 30}" y="${50 + (i % 3) * 8}" width="${8 + (i % 2) * 10}" height="40" fill="${T.night ? '#0E1426' : '#5E8A50'}"/>`).join('')}<animateTransform attributeName="transform" type="translate" from="60 0" to="-140 0" dur="1.5s" repeatCount="indefinite"/></g></g>`).join('')}</g>` }),
  wedding: (T, r, P0) => ({ bg: `${skyRect(T, 'wd' + P0.uid)}${celestial(T, r, 280)}<rect y="120" width="${CW}" height="60" fill="#8EBF6E"/><path d="M120 150 V70 Q160 34 200 70 V150" fill="none" stroke="#F2F0E6" stroke-width="6"/>${Array.from({ length: 14 }, (_, i) => { const a = Math.PI * (i / 13); return `<circle cx="${160 - Math.cos(a) * 40}" cy="${70 - Math.sin(a) * 34 + 2}" r="4" fill="${['#E8553E', '#F2F0E6', '#F4B400', '#C2577F'][i % 4]}"/>`; }).join('')}${Array.from({ length: 10 }, (_, i) => `<rect x="${i < 5 ? 20 + i * 18 : 210 + (i - 5) * 18}" y="146" width="12" height="10" fill="#F2F0E6"/>`).join('')}<path d="M150 180 L156 140 h8 L170 180Z" fill="#F2F0E6" opacity=".8"/>`, gy: 160, dress: 1, costume: 'suit', anim: `<g>${Array.from({ length: 14 }, () => `<circle cx="${r() * CW}" cy="-10" r="2" fill="${['#F2F0E6', '#F4B400', '#E8553E'][Math.floor(r() * 3)]}"><animate attributeName="cy" from="-10" to="190" dur="${3 + r() * 3}s" begin="${-r() * 4}s" repeatCount="indefinite"/></circle>`).join('')}</g>` }),
  interview: (T, r, P0) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#4A5868"/><circle cx="240" cy="70" r="80" fill="#6E86A6" opacity=".4"/><rect x="200" y="20" width="90" height="70" fill="#5A6878"/>${Array.from({ length: 6 }, (_, i) => `<rect x="${206 + (i % 3) * 28}" y="${26 + Math.floor(i / 3) * 30}" width="22" height="24" fill="#8A97AA"/>`).join('')}<rect y="150" width="${CW}" height="30" fill="#3A4656"/><rect x="0" y="136" width="${Math.max(120, (P0.lower || 'In their own words').length * 6 + 24)}" height="22" fill="#000" opacity=".55"/><text x="10" y="151" font-size="9" font-family="Barlow, sans-serif" fill="#FFFFFF" font-weight="600">${esc(P0.lower || 'In their own words')}</text>`, gy: 186, slots: [120], sit: 1 }),
  toon: (T, r, P0) => ({ bg: `<rect width="${CW}" height="${CH}" fill="${['#8FD3F4', '#FFD27A', '#B9F0C8'][Math.floor(r() * 3)]}"/><circle cx="260" cy="36" r="18" fill="#FFF07A"/>${Array.from({ length: 4 }, (_, i) => `<ellipse cx="${40 + i * 80}" cy="${40 + (i % 2) * 14}" rx="26" ry="10" fill="#FFFFFF"/>`).join('')}<path d="M0 130 Q80 100 160 126 T320 120 V180 H0Z" fill="#6ED37A"/><path d="M0 150 Q100 140 200 156 T320 150 V180 H0Z" fill="#4CB85A"/>${[60, 240].map(x => `<rect x="${x - 3}" y="100" width="6" height="30" fill="#8A5A2B"/><circle cx="${x}" cy="94" r="18" fill="#3E9A4A"/>`).join('')}`, gy: 168, toon: 1, anim: `<g>${Array.from({ length: 4 }, (_, i) => `<ellipse cx="${40 + i * 80}" cy="${40 + (i % 2) * 14}" rx="26" ry="10" fill="#FFFFFF"/>`).join('')}<animateTransform attributeName="transform" type="translate" from="0 0" to="60 0" dur="8s" repeatCount="indefinite"/></g>` }),
  club: (T, r) => ({ bg: `<rect width="${CW}" height="${CH}" fill="#1E1430"/><rect x="60" y="40" width="200" height="70" fill="#2E2048"/>${[90, 160, 230].map((x, i) => `<rect x="${x - 2}" y="70" width="4" height="40" fill="#555"/><circle cx="${x}" cy="66" r="4" fill="#333"/>`).join('')}<rect x="30" y="110" width="260" height="10" fill="#4A3A5E"/><rect y="120" width="${CW}" height="60" fill="#140E22"/>${Array.from({ length: 20 }, (_, i) => `<circle cx="${i * 17 + 8}" cy="${168 + (i % 2) * 6}" r="7" fill="#0A0612"/>`).join('')}<text x="160" y="30" text-anchor="middle" font-family="Barlow Condensed, sans-serif" font-weight="700" font-size="14" fill="#FF5AA8" letter-spacing="4">LIVE TONIGHT</text>`, gy: 112, anim: `<g>${['#FF5AA8', '#5AC8FA', '#F4B400'].map((c, i) => `<path d="M${60 + i * 100} 0 L${30 + i * 100} 120 L${110 + i * 100} 120Z" fill="${c}" opacity=".2"><animate attributeName="opacity" values=".05;.3;.05" dur="${1 + i * .3}s" repeatCount="indefinite"/></path>`).join('')}</g>` }),
  alley: (T, r, P0) => ({ bg: `<rect width="${CW}" height="${CH}" fill="${T.night ? '#2E3A55' : '#8C9AA6'}"/><path d="M0 0 h100 v180 h-100Z" fill="#8A4A35"/><path d="M220 0 h100 v180 h-100Z" fill="#7A4030"/>${Array.from({ length: 40 }, (_, i) => `<rect x="${(i % 4) * 25 + (i % 8 > 3 ? 220 : 0)}" y="${Math.floor(i / 8) * 18 + (i % 2) * 9}" width="22" height="7" fill="#000" opacity=".1"/>`).join('')}<path d="M100 30 h40 v4 h-40 M100 60 h40 v4 h-40 M104 34 v26 M136 34 v26" stroke="#2B2B2B" stroke-width="2" fill="none"/><rect x="240" y="122" width="50" height="34" fill="#3E5A3E"/><rect y="156" width="${CW}" height="24" fill="#3A3A40"/><ellipse cx="170" cy="168" rx="40" ry="5" fill="#8FA6BF" opacity=".35"/><rect x="160" y="40" width="4" height="10" fill="#2B2B2B"/><circle cx="162" cy="52" r="4" fill="#FFE09A"/>${lampGlow(162, 52, '#FFE09A', 50)}`, gy: 172, hat: P0.era < 1965 ? 'fedora' : undefined, anim: T.night || r() < .5 ? `<g opacity=".35">${Array.from({ length: 40 }, () => `<path d="M${r() * CW} ${r() * CH} l-3 9" stroke="#DCEBF5" stroke-width="1"/>`).join('')}<animateTransform attributeName="transform" type="translate" from="0 -30" to="-10 30" dur=".5s" repeatCount="indefinite"/></g>` : `<g opacity=".4"><ellipse cx="270" cy="120" rx="14" ry="20" fill="#F2F0E6"/><animateTransform attributeName="transform" type="translate" values="0 0;-6 -30" dur="3s" repeatCount="indefinite"/><animate attributeName="opacity" values=".4;0" dur="3s" repeatCount="indefinite"/></g>` })
};
const GRADES = { Horror: ['#2E6B5E', .14], Western: ['#C88A3A', .14], 'Sci-fi': ['#3AA0C8', .1], Crime: ['#2E3A55', .14], Thriller: ['#2E4A55', .1], War: ['#6B6A3A', .16], Romance: ['#E8857A', .1], Fantasy: ['#7A5AA6', .08], Musical: ['#E85A9A', .06], Superhero: ['#3A5AC8', .06], Period: ['#A8865F', .12] };
// Which frame this is: setting, time, who is in it, what they're doing. The caption says it in words.
function frameOf(f, i) {
  const SF = typeof storyFrame === 'function' ? storyFrame(f, i) : null; if (SF) return SF;
  const r = hashRand(f.id * 71 + i * 13 + 5), era = f.rel !== null ? yearOf(f.rel) : S.year;
  const G = GENRE_SETTINGS[f.genre] || GENRE_SETTINGS.Drama;
  let setting = G[(i + Math.floor(r() * G.length)) % G.length];
  if (era < 1955 && ['bridge', 'planet', 'lab'].includes(setting) && f.genre !== 'Sci-fi') setting = 'street';
  const tods = ['Horror', 'Crime'].includes(f.genre) ? [3, 3, 2, 0] : f.genre === 'Romance' ? [1, 2, 0, 3] : [0, 0, 1, 2, 3];
  const tod = tods[Math.floor(r() * tods.length)];
  const cast = f.cast || [], n = setting === 'interview' ? 1 : r() < .55 && cast.length > 1 ? 2 : r() < .25 && cast.length > 2 ? 3 : 1;
  const who = Array.from({ length: n }, (_, k) => cast[(i + k) % Math.max(1, cast.length)]).filter((x, k, A) => x !== undefined && A.indexOf(x) === k);
  const V = SC_VERBS[f.genre] || SC_VERBS.Drama, verb = (who.length > 1 ? V[0] : V[1])[Math.floor(r() * 3)];
  return { r, era, setting, tod, who, verb };
}
function stillCaption(f, i) {
  const F = frameOf(f, i), names = F.who.map(id => P(id).name), where = SC_SETTINGS[F.setting];
  if (F.cap) return names.length ? `${names.join(', ')}: ${F.cap}.`.replace(/\.\.$/, '.') : `${F.cap}.`.replace(/\.\.$/, '.');
  if (!names.length) return `The crew ${where}, between takes.`;
  const who = names.length === 1 ? names[0] : names.length === 2 ? `${names[0]} and ${names[1]}` : `${names.slice(0, -1).join(', ')} and ${names[names.length - 1]}`;
  const when = ['', ', in the golden hour', ', at dusk', ', at night'][F.tod];
  return `${who} ${F.verb} ${where}${when}.`;
}
function stillSVG(f, i, w = 320, animated = false) {
  const F = frameOf(f, i), r = F.r, T = scPal(f, r, F.tod), uid = `s${f.id}x${i}${animated ? 'a' : ''}`;
  const P0 = { era: F.era, uid, sign: null, lower: F.who.length ? P(F.who[0]).name.toUpperCase() : null };
  const D = (SC_DRAW[F.setting] || SC_DRAW.apartment)(T, r, P0);
  const slots = D.slots || (F.who.length === 1 ? [120 + r() * 80] : F.who.length === 2 ? [110, 210] : [80, 160, 240]);
  const poses = ['stand', 'point', 'reach', 'walk', 'raise'];
  const pr = { Western: 'gun', Crime: r() < .3 ? 'gun' : 'phone', Fantasy: 'sword', 'Martial arts': null, Horror: 'lantern', Musical: 'mic', Romance: 'flowers', Comedy: 'glass', Period: 'book', War: null }[f.genre];
  const actors = F.who.map((id, k) => {
    const L = scLook(id, r), face = F.who.length === 1 ? (r() < .5 ? 1 : -1) : k === 0 ? 1 : -1;
    const pose = D.sit ? 'sit' : D.fly ? 'raise' : F.genre === 'Action' ? (r() < .6 ? 'run' : 'point') : poses[Math.floor(r() * poses.length)];
    const h = D.fly ? 54 : D.toon ? 70 : F.setting === 'interview' ? 150 : 96 + r() * 12;
    const gy = D.fly ? D.gy - 30 * k : D.gy + (k % 2) * 2;
    return actor(slots[k] ?? 160, gy, h, L, { face, pose, costume: D.costume || (F.era < 1940 || F.genre === 'Period' ? 'suit' : r() < .25 ? 'suit' : null), hat: D.hat || (F.era < 1955 && r() < .4 ? 'fedora' : undefined), helmet: D.helmet, prop: k === 0 && r() < .55 ? (pr || undefined) : undefined, dress: D.dress, cape: D.fly ? ['#C62828', '#2C4F7C', '#E3B23C'][k % 3] : undefined, rim: T.night ? '#BFD8F2' : null });
  });
  const grade = GRADES[f.genre], old = F.era < 1952 && f.genre !== 'Animation';
  const vign = `<defs><radialGradient id="vg${uid}" cx=".5" cy=".5" r=".75"><stop offset=".6" stop-color="#000" stop-opacity="0"/><stop offset="1" stop-color="#000" stop-opacity="${old ? .45 : .28}"/></radialGradient></defs><rect width="${CW}" height="${CH}" fill="url(#vg${uid})"/>`;
  const wide = hashRand(f.id * 3 + 1)() < .55 ? `<rect width="${CW}" height="14" fill="#000"/><rect y="${CH - 14}" width="${CW}" height="14" fill="#000"/>` : '';
  return `<svg class="still${animated ? ' moving' : ''}" viewBox="0 0 ${CW} ${CH}" width="${w}" height="${Math.round(w * CH / CW)}" role="img" aria-label="${esc(stillCaption(f, i))}"${old ? ' style="filter:grayscale(1) contrast(1.08) brightness(1.08)"' : ''}>${D.bg}${animated && D.anim ? D.anim : ''}${actors.join('')}${D.fg || ''}${grade ? `<rect width="${CW}" height="${CH}" fill="${grade[0]}" opacity="${grade[1]}" style="mix-blend-mode:multiply"/>` : ''}${T.night ? `<rect width="${CW}" height="${CH}" fill="#2A3F6E" opacity=".12"/>` : ''}${vign}${wide}</svg>`;
}
function stillsHTML(f) {
  const r = hashRand(f.id * 19 + 3), st = typeof storyOf === 'function' ? storyOf(f) : null, n = st ? Math.min(6, st.frames.length) : 3 + Math.floor(r() * 3);
  return `<div class="stills">${Array.from({ length: n }, (_, i) => `<figure>${stillSVG(f, i, 240)}<figcaption>${esc(stillCaption(f, i))}</figcaption></figure>`).join('')}</div>`;
}
// ---- the trailer: a timeline of shots with motion, text over footage, a montage, a title slam ----
const TRAILER_KINDS = ['classic', 'quotes', 'teaser', 'cast', 'comedy', 'horror'];
const QUOTE_PRAISE = [['A triumph.', 'Unmissable.', 'The film of the year.', 'Extraordinary.', 'I laughed, I cried, I called my mother.'], ['Gripping from start to finish.', 'A real crowd-pleaser.', 'Beautifully made.', 'You won\'t forget it.'], ['Bold and strange.', 'Something different.', 'Worth the trip.']];
const MOVES = ['push', 'pull', 'panl', 'panr', 'tilt'];
function trailerKind(f) {
  const r = hashRand(f.id * 29 + 11)();
  if (f.genre === 'Horror' && r < .6) return 'horror';
  if (f.genre === 'Comedy' && r < .6) return 'comedy';
  if (f.rel === null) return r < .5 ? 'teaser' : 'classic';
  if ((f.reviews || 0) >= 72 && r < .6) return 'quotes';
  return ['classic', 'cast', 'teaser', 'classic'][Math.floor(r * 4)];
}
// Reading time: a line stays up long enough to read twice.
function readMs(t) { return t ? clamp(1800 + t.length * 75, 2600, 8000) : 0; }
// segments: { shot (frame index) | null, text, pos ('low'|'mid'|'card'), big, ms, move, cut ('fade'|'flash'|'hard') }
function trailerPlan(f) {
  const lead = f.cast[0] !== undefined ? P(f.cast[0]).name : '', co2 = f.cast[1] !== undefined ? P(f.cast[1]).name : '', co = f.co !== null ? S.companies[f.co].name : 'An independent picture';
  const dir = P(f.dir).name + (f.codir ? ' & ' + f.codir.map(i => P(i).name).join(' & ') : ''), r = hashRand(f.id * 37 + 3), mv = () => MOVES[Math.floor(r() * MOVES.length)];
  const prev = P(f.dir).credits.map(i => S.films[i]).filter(x => x && x.id !== f.id && x.rel !== null && x.rel < (f.rel ?? S.week)).sort((a, b) => b.total - a.total)[0];
  const shot = (k, text, o = {}) => ({ shot: k, text, pos: o.pos || 'low', ms: Math.max(o.ms || 3400, readMs(text)), move: o.move || mv(), cut: o.cut || 'fade' });
  const card = (text, o = {}) => ({ shot: o.under ?? null, text, pos: 'card', ms: Math.max(o.ms || 0, readMs(text)), move: 'push', cut: o.cut || 'fade', dim: 1 });
  const montage = n => Array.from({ length: n }, (_, k) => ({ shot: 10 + k, ms: 900 - k * 80, move: k % 2 ? 'panl' : 'push', cut: 'flash' }));
  const title = { shot: null, text: f.title.toUpperCase(), pos: 'card', big: 1, ms: 4200, cut: 'flash', slam: 1 };
  const end = card(f.rel !== null ? 'NOW SHOWING' : 'COMING SOON', { ms: 2800 });
  const open = { shot: null, text: co.toUpperCase() + ' PRESENTS', pos: 'card', ms: 2800, cut: 'fade', logo: 1 };
  switch (trailerKind(f)) {
    case 'quotes': { const band = (f.reviews || 0) >= 80 ? 0 : (f.reviews || 0) >= 65 ? 1 : 2, Q = QUOTE_PRAISE[band], q = k => `“${Q[Math.floor(r() * Q.length)]}”  — ${PAPERS[(f.id + k) % PAPERS.length]}`; return [open, shot(0, null, { ms: 3000 }), shot(1, q(0), { pos: 'mid' }), shot(2, null), shot(3, q(3), { pos: 'mid' }), card('★★★★' + ((f.reviews || 0) >= 82 ? '★' : ''), { under: 4 }), ...montage(5), shot(5, q(5), { pos: 'mid' }), title, end]; }
    case 'teaser': return [open, shot(0, null, { ms: 4200, move: 'push' }), shot(1, filmTagline(f), { ms: 4000 }), shot(2, null, { ms: 2600 }), ...montage(3), title, end];
    case 'cast': return [card('A FILM BY ' + dir.toUpperCase(), { under: 0 }), shot(1, lead.toUpperCase(), { pos: 'mid' }), co2 ? shot(2, co2.toUpperCase(), { pos: 'mid' }) : shot(2, null), shot(3, filmLogline(f)), ...montage(4), shot(4, filmTagline(f)), title, end];
    case 'comedy': return [card(prev ? `FROM THE DIRECTOR OF ${prev.title.toUpperCase()}` : 'FROM THE PEOPLE WHO SHOULD HAVE KNOWN BETTER', { under: 0 }), shot(1, filmLogline(f)), shot(2, null, { ms: 2200, cut: 'hard' }), card('THIS SUMMER…', { under: 3 }), shot(3, lead.toUpperCase() + (co2 ? ' AND ' + co2.toUpperCase() : ''), { pos: 'mid' }), shot(4, null, { ms: 1800, cut: 'hard' }), shot(5, filmTagline(f)), title, end];
    case 'horror': return [card('BASED ON EVENTS NOBODY WILL TALK ABOUT'), shot(0, null, { ms: 4600, move: 'push' }), shot(1, null, { ms: 1200, cut: 'hard' }), card('…', { under: 2, ms: 2000 }), shot(2, filmTagline(f), { move: 'push' }), ...montage(6), card('DON\'T WATCH ALONE.', { ms: 3000 }), title, end];
    default: return [open, card(prev ? `FROM THE DIRECTOR OF ${prev.title.toUpperCase()}` : 'A FILM BY ' + dir.toUpperCase(), { under: 0 }), shot(1, null, { ms: 3400 }), card('IN A WORLD WHERE…', { under: 2 }), shot(2, filmLogline(f)), shot(3, lead.toUpperCase(), { pos: 'mid' }), ...montage(4), shot(4, filmTagline(f)), title, end];
  }
}
// Sound: a low pad that swells, hits on the cuts, a riser before the title. WebAudio, generated, muted on request.
function trailerAudio() {
  let ctx = null, master = null, pad = [];
  const ok = () => { if (ctx) return true; try { ctx = new (window.AudioContext || window.webkitAudioContext)(); master = ctx.createGain(); master.gain.value = .14; master.connect(ctx.destination); return true; } catch (e) { return false; } };
  return {
    start(base) { if (!ok()) return; for (const fr of [base, base * 1.5, base * 2]) { const o = ctx.createOscillator(), g = ctx.createGain(); o.type = 'sawtooth'; o.frequency.value = fr; const lp = ctx.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 420; g.gain.value = 0; g.gain.linearRampToValueAtTime(.12, ctx.currentTime + 3); o.connect(lp); lp.connect(g); g.connect(master); o.start(); pad.push([o, g, lp]); } },
    hit(big) { if (!ctx) return; const o = ctx.createOscillator(), g = ctx.createGain(), t = ctx.currentTime; o.type = 'sine'; o.frequency.setValueAtTime(big ? 90 : 140, t); o.frequency.exponentialRampToValueAtTime(38, t + (big ? 1.2 : .5)); g.gain.setValueAtTime(big ? .9 : .45, t); g.gain.exponentialRampToValueAtTime(.001, t + (big ? 1.6 : .6)); o.connect(g); g.connect(master); o.start(t); o.stop(t + 1.7); },
    swell(v) { if (!ctx) return; for (const [, g, lp] of pad) { g.gain.linearRampToValueAtTime(.12 + v * .12, ctx.currentTime + .8); lp.frequency.linearRampToValueAtTime(420 + v * 1600, ctx.currentTime + .8); } },
    mute(m) { if (master) master.gain.value = m ? 0 : .14; },
    pause(p) { if (ctx) p ? ctx.suspend() : ctx.resume(); },
    stop() { if (ctx) { try { ctx.close(); } catch (e) { } ctx = null; pad = []; } }
  };
}
function playTrailer(id) {
  const f = S.films[id]; if (!f || typeof document === 'undefined') return;
  const old = document.getElementById('trailer'); if (old) old.remove();
  const c = GENRE_LOOK[f.genre] || GENRE_LOOK.Drama, plan = typeof trailerPlan2 === 'function' ? trailerPlan2(f) : trailerPlan(f), total = plan.reduce((s, x) => s + x.ms, 0);
  const el = document.createElement('div'); el.id = 'trailer'; el.style.setProperty('--tc', c[2]); el.style.setProperty('--tb', c[0]);
  const layer = (s, k) => `<div class="tv-seg" data-k="${k}">${s.shot !== null && s.shot !== undefined ? `<div class="tv-shot mv-${s.move}${s.dim ? ' dim' : ''}${s.freeze ? ' freeze' : ''}" style="animation-duration:${s.ms + 900}ms">${stillSVG(f, s.shot, 960, true)}</div>` : ''}${s.laurel && typeof laurelSVG === 'function' ? `<div class="tv-text card">${laurelSVG(s.laurel)}</div>` : ''}${s.sub ? `<div class="tv-sub">${esc(s.sub)}</div>` : ''}${s.text && s.text.trim() ? `<div class="tv-text ${s.pos}${s.vo ? ' vo' : ''}${s.big ? ' big' : ''}${s.slam ? ' slam' : ''}${s.text.length > 70 ? ' long' : ''}">${s.logo ? `<span class="tv-logo">${logoSVGFor(f)}</span>` : ''}${esc(s.text)}${s.big ? `<small>${esc(filmTagline(f))}</small>` : ''}</div>` : ''}</div>`;
  el.innerHTML = `<div class="tv"><div class="tv-screen">${plan.map(layer).join('')}<div class="tv-flash"></div><div class="tv-grain"></div></div>
   <div class="tv-bar"><button class="tv-btn tv-play" aria-label="Pause">❚❚</button><button class="tv-btn tv-again" aria-label="Replay">↺</button><span class="tv-prog"><i></i></span><span class="tv-time">0:00 / ${fmtClock(total)}</span><button class="tv-btn tv-mute" aria-label="Mute">🔊</button><button class="tv-btn tv-close" aria-label="Close">✕</button></div></div>`;
  document.body.appendChild(el);
  const segs = [...el.querySelectorAll('.tv-seg')], flash = el.querySelector('.tv-flash'), bar = el.querySelector('.tv-prog i'), clock = el.querySelector('.tv-time'), playB = el.querySelector('.tv-play'), muteB = el.querySelector('.tv-mute');
  const A = typeof trailerScore === 'function' ? trailerScore(f) : trailerAudio(), starts = []; let acc = 0; for (const s of plan) { starts.push(acc); acc += s.ms; }
  let t = 0, cur = -1, last = null, paused = false, muted = false, raf = 0, done = false;
  const enter = k => {
    const s = plan[k], prev = segs[cur];
    if (prev) { prev.classList.remove('on'); prev.classList.add('off'); setTimeout(() => prev.classList.remove('off'), 700); }
    const seg = segs[k]; seg.classList.remove('off'); void seg.offsetWidth; seg.classList.add('on');
    seg.querySelectorAll('svg').forEach(svg => { try { svg.setCurrentTime(0); svg.unpauseAnimations(); } catch (e) { } });
    if (s.cut === 'flash') { flash.classList.remove('go'); void flash.offsetWidth; flash.classList.add('go'); }
    el.classList.toggle('hardcut', s.cut === 'hard');
    if (A.hush) A.hush(!!s.hush || (!!s.freeze && plan[k - 1] && plan[k - 1].freeze));
    if (s.freeze && !(plan[k - 1] && plan[k - 1].freeze) && A.scratch) A.scratch();
    else if (s.slam) A.hit(true); else if (s.cut === 'hard' || s.vo) A.hit(false);
    A.swell(k / plan.length);
    cur = k;
  };
  const tick = now => {
    if (last === null) last = now;
    if (!paused) t += now - last;
    last = now;
    if (t >= total) { if (!done) { done = true; segs[cur] && segs[cur].classList.add('hold'); playB.textContent = '▶'; } bar.style.width = '100%'; clock.textContent = `${fmtClock(total)} / ${fmtClock(total)}`; return; }
    let k = starts.findIndex((s0, j) => t >= s0 && t < s0 + plan[j].ms);
    if (k !== cur && k >= 0) enter(k);
    bar.style.width = (t / total * 100).toFixed(2) + '%'; clock.textContent = `${fmtClock(t)} / ${fmtClock(total)}`;
    raf = requestAnimationFrame(tick);
  };
  const setPause = p => { paused = p; el.classList.toggle('paused', p); playB.textContent = p ? '▶' : '❚❚'; A.pause(p); el.querySelectorAll('svg').forEach(svg => { try { p ? svg.pauseAnimations() : svg.unpauseAnimations(); } catch (e) { } }); };
  const restart = () => { cancelAnimationFrame(raf); segs.forEach(s => s.classList.remove('on', 'off', 'hold')); t = 0; cur = -1; last = null; done = false; setPause(false); raf = requestAnimationFrame(tick); };
  const close = () => { cancelAnimationFrame(raf); A.stop(); el.remove(); document.removeEventListener('keydown', key); };
  const key = e => { if (e.key === 'Escape') close(); else if (e.key === ' ') { e.preventDefault(); e.stopPropagation(); done ? restart() : setPause(!paused); } };
  document.addEventListener('keydown', key);
  playB.onclick = () => done ? restart() : setPause(!paused);
  el.querySelector('.tv-again').onclick = restart;
  muteB.onclick = () => { muted = !muted; A.mute(muted); muteB.textContent = muted ? '🔇' : '🔊'; };
  el.querySelector('.tv-close').onclick = close;
  el.querySelector('.tv-prog').onclick = e => { const b = e.currentTarget.getBoundingClientRect(); t = clamp((e.clientX - b.left) / b.width, 0, .999) * total; segs.forEach(s => s.classList.remove('on', 'off', 'hold')); cur = -1; done = false; };
  el.onclick = e => { if (e.target === el) close(); };
  A.start({ Horror: 55, Action: 73, Comedy: 98, Romance: 87, Western: 65, 'Sci-fi': 61 }[f.genre] || 69);
  raf = requestAnimationFrame(tick);
}
function fmtClock(ms) { const s = Math.floor(ms / 1000); return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`; }
function logoSVGFor(f) { return f.co !== null && typeof logoSVG === 'function' ? logoSVG(S.companies[f.co], 54) : ''; }
