// ---------------- The curriculum, part two: producing, performance and the making departments ----------------
CURR.pro = { label: 'Producing', icon: '💼', courses: ['Development', 'Money', 'Production and delivery'], lessons: [
  [1, 'Development', 'Development turns an idea or a book into a script that can be financed: optioning rights, hiring writers, giving notes, attaching talent.', 'Option the rights cheaply with a long enough term; hire the writer who loves it; give notes in writing, grouped and prioritised.', ['You can afford one option this year.', ['A bestseller with a big price', 'fin', 'Easier to finance; less of it is yours.'], ['An obscure book you love', 'tas', 'Cheap and yours, and hard to sell.']], '{C} optioned the book behind {F} for less than the cost of the catering on its first day of shooting.'],
  [1, 'Above and below the line', 'A budget splits into above the line (rights, writer, director, producers, principal cast) and below the line (crew, equipment, locations, post, insurance). Contingency is usually 10%.', 'Build the budget from the schedule: days times crew rates, plus kit, locations, post and fringes (taxes and benefits).', ['The budget is 15% over.', ['Cut shoot days', 'bud', 'Tighter, harder days.'], ['Cut a location', 'bud', 'Less scale.'], ['Raise more money', 'fin', 'Time and dilution.']], ''],
  [1, 'The five stages', 'Development, pre-production, production, post-production, distribution. Each has its own people, money and risks.', 'Track each stage\'s exit gates: a locked script, a green light, wrap, picture lock, delivery.', ['Pre-production is short and the script isn\'t locked.', ['Delay the shoot', 'pack', 'Safer film, angrier financiers.'], ['Shoot and rewrite on the fly', 'setm', 'Fast and expensive.']], ''],
  [2, 'Packaging', 'Attaching a director and stars turns a script into something financiers can value. Agencies often package their own clients together.', 'Make a target list for each role; go out with offers in order; never go to two actors for one part at once.', ['A star says yes, but only if their friend directs.', ['Accept the package', 'pack', 'Financeable today.'], ['Hold out for your director', 'talent', 'A better film, maybe never made.']], 'The package on {F}: {D} directing and {A} starring, both from the same agency. It closed in a week.'],
  [2, 'Financing structures', 'Films are financed from equity investors, pre-sales of territories, tax credits, gap loans against unsold territories, and studio deals.', 'Stack the finance: tax credit first (cheapest), then pre-sales, gap, and equity last because it wants the most back.', ['You are 20% short.', ['Gap loan', 'fin', 'Expensive interest; you shoot this year.'], ['More equity', 'fin', 'Investors take more of the profit.'], ['Move to a better tax credit', 'bud', 'Cheaper money, a different city.']], ''],
  [2, 'The completion bond', 'A completion bond guarantees financiers the film gets finished. If you go badly over, the bond company can take over the production.', 'Budget a real contingency and keep reporting honestly; bond companies hate surprises more than overages.', ['You\'re over budget and the bond company calls.', ['Tell them everything', 'com', 'They help; you keep control.'], ['Hide it for a week', 'pack', 'If they find out, they take over.']], ''],
  [3, 'The waterfall', 'Box office flows down a "waterfall": exhibitors, distribution fees and P&A, then lenders and equity, then profit participants. Net profit points are often worth nothing.', 'Negotiate gross or "adjusted gross" points where you can; read the definitions of net profit; audit statements.', ['You\'re offered net points or a bigger fee.', ['Take the fee', 'pack', 'Money in hand.'], ['Take the points', 'fin', 'Probably nothing, maybe a fortune.']], ''],
  [3, 'Protecting the film', 'Producers protect the film from the money and the money from the film: saying no early, guarding the schedule and the director\'s time.', 'Fight the fights that change the film on screen; concede the ones that don\'t.', ['The financier wants a cameo for their nephew.', ['Give him one line', 'pack', 'Peace, and a wooden line.'], ['Say no', 'com', 'Integrity; a colder financier.']], '']
] };
CURR.dist = { label: 'Marketing and distribution', icon: '📣', courses: ['The audience', 'The campaign', 'The release'], lessons: [
  [1, 'Four quadrants', 'Studios divide audiences into four quadrants: men and women, over and under 25. A "four-quadrant" film plays to all of them.', 'Decide which quadrants are core and which are a bonus; build the trailer for the core and the TV spots for the others.', ['Your romantic thriller tests well with women over 25 only.', ['Market to them hard', 'mkt', 'A strong opening with a known audience.'], ['Recut the trailer for everyone', 'mkt', 'Wider, blander.']], ''],
  [1, 'Release windows', 'Films move through windows: theatrical, premium video on demand, streaming, TV. Each window earns differently; shorter windows trade cinema revenue for streaming value.', 'Plan windows with the distributor before release; protect the theatrical window if the film is an event.', ['A streamer offers a straight-to-platform deal.', ['Take it', 'dist', 'Guaranteed money, no box office upside.'], ['Go theatrical', 'dist', 'Risk, and the chance of a hit.']], ''],
  [2, 'Platform versus wide', 'A wide release opens everywhere at once; a platform release opens in a few cities and expands on word of mouth. Platform suits awards films and festival hits.', 'Wide needs big P&A and a strong opening; platform needs reviews and patience.', ['Your festival hit has no stars.', ['Platform it', 'dist', 'Word of mouth builds.'], ['Go wide', 'mkt', 'Fast money or a fast flop.']], '{F} opened in four cinemas and expanded to four hundred in six weeks.'],
  [2, 'P&A', 'Prints and advertising: the cost of selling the film. For a wide studio release it can match half the production budget.', 'Spend where the audience is: trailers before the right films, the right TV slots, social media for younger quadrants.', ['Tracking is soft two weeks out.', ['Spend more', 'mkt', 'Maybe a rescue; definitely a bill.'], ['Cut spending and save the money', 'bud', 'Smaller loss, smaller chance.']], ''],
  [3, 'Test screenings and tracking', 'Recruited screenings measure playability; tracking surveys measure awareness and interest before release.', 'Read the recruit ratio (how many accepted an invite) as an early sign of marketability; separate "liked it" from "would recommend it".', ['The film plays well but nobody wants to see it.', ['Rethink the campaign', 'mkt', 'Sell what people liked.'], ['Rethink the film', 'shape', 'Too late, usually.']], '']
] };
CURR.act = { label: 'Acting', icon: '🎭', courses: ['Technique', 'The instrument', 'Acting for camera'], lessons: [
  [1, 'Given circumstances and objectives', 'Stanislavski\'s foundation: know the given circumstances (who, where, when, what has just happened) and play an objective (what you want from the other person).', 'For each scene write the circumstances, your objective, the obstacle and your actions to get it.', ['A scene where your character says goodbye.', ['Play "say goodbye"', 'range', 'Generic and sad.'], ['Play "make them ask me to stay"', 'range', 'Alive, and heartbreaking.']], ''],
  [1, 'Meisner: living truthfully', 'Meisner training starts with repetition: two actors repeat an observation back and forth until they are reacting to each other rather than to their plan.', 'Listen; respond to what you actually get; let the other actor change you.', ['Your scene partner gives you something unexpected.', ['Respond to it', 'impro', 'The scene comes alive.'], ['Stick to what you rehearsed', 'eth', 'Safe and wooden.']], ''],
  [1, 'Voice and movement', 'The voice (Linklater, Fitzmaurice) and body (Laban, Alexander, Viewpoints) are the actor\'s instrument. Training frees habits so choices become possible.', 'Warm up daily: breath, release, resonance, articulation; work with Laban efforts (punch, float, glide, slash, dab, wring, press, flick) to find a character\'s physicality.', ['Find the physical life of a cruel boss.', ['Laban "press": slow, direct, heavy', 'phys', 'Menacing and still.'], ['Laban "flick": light, quick, indirect', 'phys', 'Cruelty that seems casual. Worse.']], ''],
  [2, 'Script analysis and beats', 'A beat is a unit of action: it changes when the objective or tactic changes. Marking beats keeps a performance moving.', 'Mark each beat in the script with a verb; find where the shifts happen; don\'t play the end of the scene at the start.', ['A long monologue.', ['Break it into five beats', 'range', 'A journey rather than a speech.'], ['Play it as one rising emotion', 'pres', 'Powerful, then monotonous.']], ''],
  [2, 'Acting for the camera', 'The camera sees thought. On screen, less is more: think the line rather than projecting it, and save the biggest moments for the close-up.', 'Know your frame size; hit marks without looking; keep eyelines close to the lens; repeat physical actions exactly for continuity.', ['The director says you\'re "too big".', ['Do less, think more', 'pres', 'It reads.'], ['Ask what the shot is', 'com', 'Smart: adjust to the frame size.']], 'In the close-up that made {A} a star in {F}, they barely move. Everything happens behind the eyes.'],
  [2, 'Self-tapes and auditions', 'Most auditions now start as self-tapes: eye-level camera, plain background, a reader off camera, good sound, two takes at most.', 'Make a strong, specific choice; slate cleanly; frame from the chest up; let the reader be quieter than you.', ['The sides are a comedy scene with a sad subtext.', ['Play the comedy', 'comic', 'Funny; may seem shallow.'], ['Play the sadness under it', 'range', 'Memorable if the casting director gets it.']], ''],
  [3, 'Matching and coverage', 'Scenes are shot many times from many angles. The actor must repeat movements and timing so the editor can cut, while keeping the performance alive.', 'Fix your business (when you drink, when you sit) in rehearsal; vary the inner life, not the outer moves.', ['Take twelve. You\'ve gone stale.', ['Change your objective slightly', 'range', 'Fresh again, still matching.'], ['Change the moves', 'impro', 'Fresh and uncuttable.']], ''],
  [3, 'Playing the result note', 'Directors often give result notes ("be angrier"). A great actor translates them into something playable.', 'Ask yourself what the character would do to produce that result; play that action instead.', ['"Can you make it funnier?"', ['Push the jokes', 'comic', 'Louder, rarely funnier.'], ['Play it more seriously', 'comic', 'Often much funnier.']], '']
] };
CURR.cst = { label: 'Casting', icon: '🧑‍🤝‍🧑', courses: ['Breakdowns', 'Sessions', 'Chemistry and offers'], lessons: [
  [1, 'The breakdown', 'Casting directors write a character breakdown for each role: age range, essence, key traits, what the role demands. Agents submit actors from it.', 'Write the essence, not just the look; mention the key scene; flag nudity, stunts or accents up front.', ['A role is described "beautiful, 25".', ['Rewrite it around the character', 'eye', 'Better submissions, wider range.'], ['Leave it', 'speed', 'A hundred lookalikes.']], ''],
  [1, 'Sides and pre-reads', 'Sides are short scenes used in auditions. Pre-reads with the casting director come before the director sees anyone.', 'Choose sides that show the role\'s range; keep sessions running on time; give each actor one adjustment to see if they can take direction.', ['An actor is great but wrong-looking.', ['Bring them to the director', 'eye', 'Sometimes the find of the year.'], ['Pass', 'talent', 'Safe.']], ''],
  [2, 'Callbacks and chemistry reads', 'Callbacks narrow the field; chemistry reads put potential co-stars together to see if the relationship works on screen.', 'Pair finalists in combinations; watch how they listen, not just how they speak.', ['Your favourite lead has no chemistry with the co-star.', ['Recast the co-star', 'eye', 'The relationship works.'], ['Recast the lead', 'talent', 'A safer star, a different film.']], 'The chemistry read for {F} lasted three minutes. {A} was cast before they left the room.'],
  [3, 'Offers and deals', 'Name actors are cast by offer, not audition. Deals cover fee, billing, perks and approvals.', 'Make offers in order; protect the budget with favoured-nations clauses; know your walkaway.', ['A star wants top billing and approval of the co-star.', ['Agree to billing, refuse approval', 'talent', 'A fair deal.'], ['Agree to everything', 'pack', 'You have a star and less control.']], '']
] };
CURR.des = { label: 'Production design', icon: '🏛️', courses: ['Research and concept', 'Drawing and building', 'Running the art department'], lessons: [
  [1, 'The design breakdown', 'Designers break the script into sets and locations, then decide which to build and which to find. Each space should tell the audience who lives there.', 'List every set; mark builds, locations and location-builds; attach research and a colour note to each.', ['The hero\'s flat.', ['Build it on stage', 'sets', 'Total control; costly.'], ['Find a real flat and dress it', 'sets', 'Authentic; cramped for camera.']], ''],
  [1, 'Research', 'Period and world-building live on research: photographs, catalogues, newspapers, museum archives, interviews with people who lived there.', 'Build a research bible per set; find one specific, surprising true detail per room.', ['A 1950s office.', ['Research-led and exact', 'period', 'Authentic.'], ['Stylised and heightened', 'world', 'Memorable; less real.']], ''],
  [2, 'Colour palettes', 'A colour palette per character, place or act carries story before anyone speaks. The designer, DP and costume designer agree it together.', 'Make a palette board; keep certain colours for certain story moments; avoid colours that fight skin tones.', ['Use red sparingly.', ['Only in the climax', 'world', 'When it appears, it screams.'], ['Everywhere, warmly', 'sets', 'Cosy, and nothing stands out.']], 'Red appears in {F} exactly three times. Each one is a death.'],
  [2, 'Drafting and models', 'Sets are drafted in plan and elevation, then modelled (physically or in 3D) so the director and DP can plan shots before construction.', 'Draft to scale; build a white card model or a SketchUp model; walk a virtual camera through it.', ['The director wants a wall to "fly" for a shot.', ['Build it wild (removable)', 'sets', 'Flexible and costly.'], ['Use a location', 'bud', 'Cheaper; the shot changes.']], ''],
  [3, 'Running the department', 'The production designer leads art directors, set decorators, prop masters, graphic designers, construction and the swing gang. Budgets are always tight.', 'Spend on what the camera sees most; reuse sets; cheat backgrounds with lighting; protect the hero set.', ['Construction is over budget.', ['Cut a set', 'bud', 'Money saved, story moved.'], ['Re-dress an existing set', 'sets', 'Clever, if nobody notices.']], '']
] };
CURR.cos = { label: 'Costume', icon: '👗', courses: ['Character through clothes', 'Fittings and making', 'The costume department'], lessons: [
  [1, 'The costume breakdown', 'Break the script by character, scene and story day to count every change. A character in one outfit across three story days still needs three looks if they sleep.', 'Build a costume plot: a grid of characters by scenes, with story days and changes.', ['The lead changes eleven times.', ['Keep it to five strong looks', 'wardrobe', 'Iconic.'], ['Eleven changes', 'wardrobe', 'Realistic, harder to remember.']], ''],
  [1, 'Multiples and ageing', 'Multiples are copies of a costume that will get wet, bloody or torn. Ageing and dyeing make new clothes look lived in.', 'Plan multiples for stunts and effects; age with sandpaper, dye, wax and wear; test on camera.', ['A stunt double needs a matching coat.', ['Make three multiples', 'wardrobe', 'Safe.'], ['One, and hope', 'bud', 'Cheap until it tears.']], ''],
  [2, 'Fittings', 'Fittings are where actors find the character in the clothes. The best designers listen first.', 'Bring options; photograph everything; ask the actor how the character feels in it, not just how it fits.', ['The actor hates the hero costume.', ['Listen and adapt', 'cha', 'They play it with confidence.'], ['Insist', 'wardrobe', 'A great look, an unhappy actor.']], ''],
  [3, 'The costume arc', 'A costume\'s arc tells the story: compare the first and last outfits. Colour, fit and condition change as the character does.', 'Map each character\'s arc on the plot; design the change gradually so the audience feels it.', ['A character gains power through the film.', ['Clothes sharpen and fit better', 'wardrobe', 'Subtle and readable.'], ['A dramatic makeover', 'period', 'Fun; less subtle.']], '{A}\'s coat in {F} gets a little more tailored every act. By the end it\'s the same coat their enemy wore at the start.']
] };
CURR.mkp = { label: 'Makeup and prosthetics', icon: '💄', courses: ['Beauty and continuity', 'Special effects makeup', 'Prosthetics'], lessons: [
  [1, 'Makeup for camera', 'Camera makeup must survive light, heat and close-ups in high definition. Less is usually more.', 'Match foundation in daylight; build in thin layers; keep continuity photos from every angle.', ['A 14-hour day under hot lights.', ['Setting spray and touch-ups between takes', 'mkup', 'Consistent all day.'], ['Heavier base', 'mkup', 'Cakey by lunch.']], ''],
  [2, 'Wounds and ageing', 'Special effects makeup builds cuts, bruises, burns and ageing with wax, gelatine, silicone and paint. Wounds progress through the story and must be tracked.', 'Plan a wound\'s progression by story day; mix blood for the lighting; photograph every stage.', ['A character ages 30 years.', ['Prosthetic appliances', 'mkup', 'Convincing and long in the chair.'], ['Paint and hair work', 'mkup', 'Faster; less convincing up close.']], ''],
  [3, 'Prosthetics', 'Prosthetics begin with a life cast, a sculpt, a mould and a silicone or foam latex appliance, applied and blended on the day.', 'Allow weeks for design and testing; plan application time into the schedule; test under the film\'s lighting.', ['The creature appears in four scenes.', ['Full prosthetic suit', 'mkup', 'Real presence for the actors.'], ['Partial prosthetic plus VFX', 'digi', 'Flexible and costly in post.']], '']
] };
CURR.vfx = { label: 'Visual effects', icon: '✨', courses: ['On set', 'Compositing', 'The pipeline'], lessons: [
  [1, 'Practical versus digital', 'Practical effects happen in camera; visual effects are added later. The best work blends them.', 'Shoot as much for real as is safe and affordable; use VFX to extend, clean up and do the impossible.', ['A car flips.', ['Do it practically', 'prac', 'Real weight; one take only.'], ['Do it digitally', 'digi', 'Flexible; may look weightless.']], ''],
  [1, 'On-set supervision', 'VFX supervisors on set gather what post needs: tracking markers, clean plates, lighting references (chrome and grey balls), measurements.', 'Shoot a clean plate after every VFX take; record lens and camera data; photograph the set for reconstruction.', ['The DP won\'t wait for a clean plate.', ['Insist: thirty seconds', 'com', 'Post is cheaper.'], ['Skip it', 'speed', 'Expensive paint-outs later.']], ''],
  [2, 'Compositing', 'Compositors combine layers: keying green screens, rotoscoping, tracking, colour matching and grain so elements sit in one world.', 'Match black levels, light direction and grain; add lens effects the camera would have; check edges at full resolution.', ['A green-screen shot looks pasted on.', ['Match the light and add atmosphere', 'digi', 'It sits in the scene.'], ['Blur the background more', 'digi', 'Hides it, partly.']], ''],
  [3, 'The pipeline and bidding', 'VFX work moves through previs, asset building, animation, lighting, rendering and comp. Studios bid on shots; changes cost money.', 'Lock shots before work starts; review in context; avoid "pixel-fucking" notes late in the schedule.', ['The director changes a creature design in month five.', ['Accept it and re-bid', 'pack', 'Better creature, bigger bill.'], ['Push back', 'com', 'Schedule saved, director unhappy.']], '']
] };
CURR.anim = { label: 'Animation', icon: '🖍️', courses: ['The principles', 'Story and layout', 'The animated feature'], lessons: [
  [1, 'Squash, stretch and timing', 'The twelve principles of animation (from Thomas and Johnston\'s "The Illusion of Life") begin with squash and stretch (weight and flexibility) and timing and spacing (speed and ease).', 'Animate a bouncing ball until it feels heavy; then light; then rubbery. Change only timing and squash.', ['A character falls.', ['Fast fall, big squash', 'digi', 'Comic and cartoony.'], ['Realistic timing, small squash', 'digi', 'Painful and real.']], ''],
  [1, 'Anticipation and follow-through', 'Anticipation prepares an action (a wind-up before a punch); follow-through and overlapping action let parts keep moving after the main action stops.', 'Add an opposite movement before every big action; let hair, clothes and tails drag and settle after.', ['A character jumps.', ['Big anticipation crouch', 'digi', 'Readable and fun.'], ['No anticipation', 'digi', 'Sudden and surprising.']], ''],
  [2, 'Storyboards and animatics', 'Animated films are written in storyboards and timed in animatics (boards cut with temp sound) long before animation begins.', 'Board every shot; cut an animatic; screen it; rework story there, where it\'s cheap.', ['A sequence isn\'t funny in the animatic.', ['Re-board it', 'shape', 'Cheap to fix now.'], ['Hope animation fixes it', 'speed', 'It won\'t.']], ''],
  [3, 'Appeal and acting', 'Appeal is what makes a character compelling to watch, heroes and villains alike. Animators are actors with a pencil.', 'Film yourself acting the shot; find clear silhouettes and strong poses; keep each character\'s movement consistent.', ['A villain isn\'t memorable.', ['Give them a signature move', 'world', 'Iconic.'], ['Make them scarier', 'digi', 'Generic.']], '']
] };
CURR.stn = { label: 'Stunts', icon: '🤸', courses: ['Falls and fights', 'Rigging', 'Coordinating'], lessons: [
  [1, 'Falling', 'Falls are trained for years: side falls, back falls, high falls onto airbags or boxes, ratchet-assisted falls.', 'Train progressively; rehearse with pads; know the landing better than the jump.', ['A 20-foot fall on day one.', ['Airbag and rehearsal', 'stunt', 'Safe and repeatable.'], ['Ratchet rig', 'stunt', 'More dramatic; needs riggers.']], ''],
  [1, 'Screen fighting', 'Screen fights are choreography: punches miss by inches and sell by angle, reaction and sound.', 'Fight to the camera angle; sell the hit with the reaction; rehearse at half speed until it\'s automatic.', ['The lead can\'t fight.', ['Choreograph around their strengths', 'stunt', 'They look great.'], ['Use the double for wide shots', 'stunt', 'Faster; less of the star.']], ''],
  [2, 'Wire work and fire', 'Wires fly performers; fire burns use protective gels, layers and safety teams. Both need dedicated riggers and rehearsals.', 'Rig, test with weight, rehearse cold; have fire safety on standby with extinguishers and blankets.', ['A full burn in a narrow corridor.', ['Rehearse three times, cut short', 'stunt', 'Safe; a shorter burn.'], ['One long take', 'stunt', 'Spectacular and dangerous.']], ''],
  [3, 'The stunt coordinator', 'The coordinator designs, casts and runs every risky moment. Their word on safety is final, even over the director.', 'Write a stunt breakdown; cast the right doubles; hold safety meetings; stop the stunt the moment it feels wrong.', ['The director wants it bigger on the day.', ['Say no', 'com', 'Nobody is hurt.'], ['Agree, with a new rehearsal', 'stunt', 'Bigger, and an hour lost.']], '']
] };
CURR.doc = { label: 'Documentary', icon: '🎞️', courses: ['Access and ethics', 'Shooting reality', 'Building the story'], lessons: [
  [1, 'Access and consent', 'Documentaries live on access: subjects letting you into their lives. Informed consent, and keeping it, is an ethical duty.', 'Explain what the film is and where it will be seen; get releases; revisit consent when circumstances change.', ['A subject asks you to cut a scene.', ['Cut it', 'eth', 'Trust kept; story weaker.'], ['Keep it, explaining why', 'com', 'A better film; maybe a broken relationship.']], ''],
  [1, 'Observational and vérité', 'Observational filmmaking watches without interfering; vérité and interactive styles admit the filmmaker\'s presence and provoke.', 'Choose your stance before you shoot; stay with scenes long enough for people to forget the camera.', ['A key event will happen without warning.', ['Live with the subject for weeks', 'eth', 'You are there when it happens.'], ['Reconstruct it later', 'struc', 'Controlled; less true.']], ''],
  [2, 'The interview', 'Good interviews come from listening: open questions, silences, follow-ups. Where the interviewee looks and how they\'re lit shapes how they\'re judged.', 'Prepare widely, then put the list away; ask "what happened next?"; let silences run.', ['An interviewee goes quiet at a key moment.', ['Wait', 'com', 'They say the thing.'], ['Ask the next question', 'speed', 'Moment gone.']], ''],
  [3, 'The paper edit', 'Documentaries are written in the edit. A paper edit arranges transcripts and scene descriptions into a story before cutting.', 'Transcribe; highlight; card the strongest moments; find a spine (a person, a question, a journey); cut to it.', ['You have 200 hours and no ending.', ['Follow the most changed person', 'shape', 'A story with an arc.'], ['Make it an essay', 'struc', 'Personal; risky.']], '']
] };
