// ---------------- The curriculum, part four: deeper lessons for the departments that run the machine ----------------
const CURR_MORE = {
  sup: [
    [1, 'Timings and the page count', 'Script supervisors time every rehearsal and take, and estimate screen time per scene from the page count, so producers know if the film is running long while it\'s still being shot.', 'Time the rehearsal with a stopwatch, record each take\'s length, and keep a running total of estimated screen time against the scripted total.', ['The film is timing ten minutes long by week three.', ['Warn the director and producer now', 'cont', 'Cuts happen on paper, cheaply.'], ['Say nothing; the edit will fix it', 'speed', 'Days of shooting end up on the cutting room floor.']], ''],
    [2, 'Facing pages and the editor\'s log', 'Opposite each page of the lined script, facing pages record every take: slate number, lens, timing, which takes were printed, and notes on performance and problems.', 'Write notes the editor can use: "best performance take 4, focus soft at end", "take 6 line changed", "boom dip in take 2".', ['The director circles a take with a visible boom.', ['Note it clearly on the facing page', 'cont', 'The editor knows before they fall in love with it.'], ['Ask for one more take', 'cha', 'Safer; the director may be irritated.']], ''],
    [3, 'Multiple cameras and inserts', 'With two or three cameras, the supervisor tracks each camera\'s framing and lens for every take, and lists the inserts (hands, letters, phones) still to shoot.', 'Label cameras A, B, C on every note; keep an insert list and hand it to second unit.', ['Second unit has one afternoon for inserts.', ['Prioritise story inserts', 'cont', 'The plot reads.'], ['Prioritise beauty inserts', 'tas', 'Lovely, and the plot has holes.']], '']
  ],
  mkp: [
    [1, 'Continuity of hair and makeup', 'Hair and makeup must match across scenes shot weeks apart. Sweat, tears, blood and dirt all progress through the story.', 'Photograph every character from front, profile and back at the start and end of each scene; keep a continuity bible by story day.', ['A scene is shot out of order a month later.', ['Rebuild from the photos', 'mkup', 'Seamless.'], ['Approximate it', 'speed', 'Viewers spot the different hairline.']], ''],
    [2, 'Blood', 'Film blood is mixed for the lighting and the camera: thicker for wounds, thinner for spray, darker as it dries. It also stains costumes, so multiples are planned.', 'Test blood colour under the scene\'s light; warn costume about stains; plan who resets between takes.', ['A shooting needs to be repeated six times.', ['Six costume multiples and a reset plan', 'mkup', 'Clean takes all afternoon.'], ['Clean between takes', 'speed', 'Hours lost, and stains that show.']], ''],
    [3, 'Ageing an actor across a lifetime', 'Ageing over decades combines prosthetics, wigs, contact lenses, paint and performance. Too much looks like a mask; too little looks like a young actor in grey.', 'Design ages in stages; test each under lighting; agree with the actor how the body and voice change too.', ['Four ages in one film.', ['Prosthetics for the oldest age only', 'mkup', 'Convincing where it matters.'], ['Prosthetics at every age', 'mkup', 'Consistent and exhausting for the actor.']], '']
  ],
  stage: [
    [1, 'The rehearsal room', 'Stage management runs the rehearsal room: the mark-up of the set on the floor in coloured tape, rehearsal props, the daily schedule and the rehearsal report sent to every department.', 'Tape the ground plan to scale before day one; supply rehearsal props early; list every change in the report.', ['The director adds a new prop in rehearsal.', ['Note it and tell props tonight', 'setm', 'It\'s there for tech.'], ['Wait for the production meeting', 'speed', 'It isn\'t.']], ''],
    [2, 'Calling the show', 'The stage manager calls every cue from the prompt desk: "standby lights 42", then "lights 42 go". Timing is everything; a late cue is a missed laugh.', 'Give standbys well ahead; call on the actor\'s breath, not after the line; keep the channel quiet.', ['An actor skips a page.', ['Jump the cues to match', 'setm', 'The audience never knows.'], ['Call them in order', 'com', 'The lights go mad.']], ''],
    [3, 'Producing for the stage', 'A theatre producer raises money from investors, books a theatre, hires the creative team and sells tickets. Investors are repaid only after the show recoups.', 'Budget weekly running costs against capacity; know the break-even; plan the marketing to peak at previews.', ['Previews are half-empty.', ['Spend on marketing', 'mkt', 'Possibly saves it.'], ['Announce closing', 'fin', 'Limits losses.']], '']
  ],
  col: [
    [2, 'Shot matching', 'Within a scene every shot must feel like the same moment: same brightness, same skin, same colour of shadow. Matching is most of a colourist\'s day.', 'Pick the hero shot; match others to it using the scopes and a split screen; check the cut playing in real time.', ['The wide and the close-up were shot on different days.', ['Match the close-up to the wide', 'colour', 'Invisible.'], ['Grade each beautifully on its own', 'tas', 'The scene flickers.']], ''],
    [3, 'Grading for story', 'The grade can carry story: warmer when a relationship is good, colder as it fails; a flashback can have its own look.', 'Map the emotional arc of the film; plan a gradual shift; protect skin through every change.', ['A flashback needs to read instantly.', ['A distinct look: warmer, softer, grain', 'colour', 'Clear.'], ['Same look, rely on story', 'tas', 'Elegant; some viewers get lost.']], '']
  ],
  snd: [
    [2, 'Playback and music on set', 'Musical numbers are shot to playback: the recorded track plays on set so performers can sync, with a click or thumper for dancers.', 'Agree tempo and versions with the music department; slate playback takes with the timecode of the track.', ['A singer wants to sing live.', ['Record live with hidden mics', 'sound', 'Raw and moving; hard to mix.'], ['Use playback', 'cont', 'Polished and safe.']], ''],
    [3, 'Sound reports and delivery', 'Every roll gets a sound report: takes, tracks, which mics on which channel, notes. Post depends on it.', 'Name tracks consistently (boom, each lav); note wild tracks and room tone; back up cards twice.', ['A card fails at wrap.', ['Restore from the backup', 'cont', 'Nothing lost.'], ['There was no backup', 'speed', 'A day of ADR.']], '']
  ],
  post: [
    [2, 'Music editing', 'Music editors cut the score and songs to picture, building temp scores, conforming cues after picture changes and preparing the score for the mix.', 'Cut on musical phrases, not just frames; keep alternate versions; track every cue for the cue sheet.', ['Picture changes after the score is recorded.', ['Re-edit the cue musically', 'score', 'Seamless.'], ['Ask the composer to rewrite', 'bud', 'Perfect and expensive.']], ''],
    [3, 'Mixing formats and loudness', 'Cinema mixes (stereo, 5.1, immersive formats) differ from TV and streaming mixes, each with loudness specifications. One film may need several mixes.', 'Mix the theatrical version first, then derive near-field TV and streaming mixes to spec, checking dialogue clarity on small speakers.', ['The streamer\'s spec is stricter on loudness.', ['A dedicated near-field mix', 'sound', 'Clear on every telly.'], ['Turn the cinema mix down', 'speed', 'Dialogue lost under music.']], '']
  ],
  dist: [
    [2, 'The trailer and the poster', 'Trailers and posters are made by specialist houses: the trailer sells the premise in two minutes; the poster in one image and a title.', 'Test several trailer cuts with audiences; decide whether to sell the star, the concept or the reviews; keep the twist out.', ['The best trailer gives away the twist.', ['Use it', 'mkt', 'Huge interest, angry fans.'], ['Use the second-best', 'tas', 'Less heat, more trust.']], ''],
    [3, 'Awards campaigns', 'Awards campaigns put films in front of voters: screenings, Q&As, trade ads, "for your consideration" mailings. Campaigns can cost millions.', 'Pick categories you can win; time the release for the season; get the talent to Q&As.', ['A modest film with one great performance.', ['Campaign for that performance only', 'mkt', 'Focused and effective.'], ['Campaign for everything', 'fin', 'Diluted and expensive.']], '']
  ],
  vfx: [
    [2, 'Previs and techvis', 'Previsualisation animates complex sequences roughly before the shoot; techvis works out real camera positions, lens and speeds so the shoot matches.', 'Previs the big sequences; share with every department; use techvis to plan rigs and lenses.', ['A big action sequence is unplanned.', ['Previs it', 'digi', 'The shoot is efficient.'], ['Find it on the day', 'stag', 'Exciting and expensive.']], ''],
    [3, 'Virtual production', 'LED volumes display real-time backgrounds behind actors, lit in camera; changes must be made before the shoot day, not after.', 'Build and approve the virtual sets in pre-production; match practical foreground to the screen; watch for moiré and colour shifts.', ['A desert scene in an LED volume.', ['Real sand and props in the foreground', 'prac', 'Sells the depth.'], ['Screen only', 'digi', 'Flat and fake up close.']], '']
  ],
  anim: [
    [2, 'Layout and staging', 'Layout places the camera and characters in each shot of an animated film, translating boards into space.', 'Stage for a clear silhouette; keep screen direction consistent; vary shot sizes like live action.', ['A dialogue scene between two animals.', ['Classical shot/reverse', 'vstory', 'Clear.'], ['One wide, with acting', 'digi', 'Charming; demands strong animation.']], ''],
    [3, 'The animation pipeline', 'Story, design, modelling, rigging, layout, animation, effects, lighting, rendering and compositing: an animated feature takes years and hundreds of people.', 'Lock story before animation; plan render budgets; protect the schedule from late design changes.', ['The lead character is redesigned in year two.', ['Accept it and re-rig', 'pack', 'Better character, a delayed film.'], ['Refuse', 'com', 'On time, and a weaker lead.']], '']
  ],
  stn: [
    [2, 'Precision driving', 'Car stunts are planned with stunt drivers, camera cars, closed roads and police; speeds look faster with longer lenses and lower shutter angles.', 'Rehearse slow, then build speed; use a process trailer for dialogue; cheat speed with lens and frame rate.', ['A chase on a public road.', ['Close the road and rehearse', 'stunt', 'Safe and exciting.'], ['Steal shots in traffic', 'speed', 'Illegal and dangerous.']], ''],
    [3, 'Action design', 'Modern action is designed: stunt teams shoot their own previs of fights and chases, which directors cut like a draft of the sequence.', 'Shoot a stunt-vis on phones; edit it; agree it with the director and DP before the shoot.', ['The director wants handheld chaos.', ['Design it, then shoot it handheld', 'stunt', 'Chaos you can follow.'], ['Improvise it', 'stag', 'Chaos nobody can follow.']], '']
  ],
  doc: [
    [2, 'Archive and fair use', 'Archive footage brings history to life but must be licensed or justified as fair use, with clear rules and expensive mistakes.', 'Budget archive early; keep a log of every clip, source and licence; get legal advice on fair use.', ['A key clip costs more than your edit.', ['Pay for it', 'bud', 'The scene works.'], ['Recreate it', 'struc', 'Cheaper and slightly hollow.']], ''],
    [3, 'Ethics of the edit', 'Editing can distort: compressing time, reordering events, choosing reaction shots. The documentary maker owes truth to subjects and audience.', 'Never imply a sequence that didn\'t happen; show subjects how they appear when you can; label reconstructions.', ['A reaction shot from another day would make the scene.', ['Use it, honestly labelled', 'shape', 'Effective and fair.'], ['Use it silently', 'shape', 'Powerful and dishonest.']], '']
  ],
  creator: [
    [2, 'Formats and series', 'Successful channels build repeatable formats: a recurring show, a challenge, a series. Formats make production faster and viewers loyal.', 'Design a format with a fixed structure and a variable; plan ten episodes before shooting one.', ['Your one-off video went viral.', ['Turn it into a series', 'mkt', 'Viewers come back.'], ['Make something different', 'tas', 'Creative freedom; the audience drifts.']], ''],
    [3, 'Collaborations', 'Collabs expose creators to each other\'s audiences; the best feel natural to both channels.', 'Pick partners with overlapping but not identical audiences; plan a video for each channel.', ['A huge creator offers a collab that doesn\'t fit your style.', ['Do it your way', 'cha', 'Their fans meet the real you.'], ['Do it their way', 'mkt', 'Big numbers, fewer stay.']], '']
  ],
  cst: [
    [2, 'Casting extras and day players', 'Background casting fills crowds; day players have one or two lines. Both need to look right and take direction quickly.', 'Cast background by look and reliability; give day players the full scene, not just their lines.', ['A day player is nervous and freezes.', ['Give them a simple action to play', 'talent', 'They relax and nail it.'], ['Recast on the spot', 'speed', 'Time saved, a bruised actor.']], '']
  ],
  cos: [
    [2, 'The costume budget and sourcing', 'Costumes are bought, rented from costume houses, made in workrooms or found in vintage shops. Each has cost, time and control trade-offs.', 'Build heroes in-house; rent crowd costumes by the rail; buy contemporary pieces in multiples; return everything on time.', ['A period crowd of 200.', ['Rent from a costume house', 'bud', 'Fast and good enough.'], ['Make them', 'period', 'Perfect and impossible.']], '']
  ],
  des: [
    [2, 'Graphics and props', 'Every label, newspaper and sign on screen is designed by graphic designers so nothing needs clearance; props are sourced, made or hired by the prop master.', 'Design fake brands consistent with the world; make hero props in multiples; keep a prop continuity list.', ['A real brand appears on a key prop.', ['Replace it with a fake brand', 'sets', 'No legal problems.'], ['Ask for clearance', 'pack', 'Possible; slow.']], '']
  ],
  creatorx: []
};
for (const f in CURR_MORE) if (CURR[f]) { CURR[f].lessons.push(...CURR_MORE[f]); CURR[f].lessons.sort((a, b) => a[0] - b[0]); }
