// ---------------- The curriculum, part one: the camera side of film ----------------
// Built from what the film schools actually teach (AFI's cinematography and directing disciplines, the NFTS craft
// MAs, USC's production sequence, UCLA's writing and producers programmes, the DGA assistant director training,
// script supervision courses) and from the working vocabulary of each department. Every lesson has: the idea, how
// it is done, a decision people really face (with the trade-offs), and an example from this world's own films.
// lesson: [year (1 foundation, 2 practice, 3 mastery), title, the idea, how it's done, decision, example, genre?]
// decision: [question, [option, skill it tests, what happens], ...]
// example tokens: {F} the film, {D} its director, {P} its cinematographer, {E} its editor, {A} its lead, {W} its writer, {C} its company, {Y} its year
const CURR = {};
CURR.dir = { label: 'Directing', icon: '🎬', courses: ['Visual grammar', 'Directing actors', 'The director\'s process'], lessons: [
  [1, 'The 180-degree line', 'Draw an imaginary line between two characters; keep the camera on one side and the audience always knows who is looking where. Cross it and the characters appear to swap sides.', 'Mark the line in the floor plan. To cross it legitimately, move the camera across on screen (a dolly round), cut to a neutral shot on the line, or let a character cross and carry the line with them.', ['A dinner argument escalates and you want the audience disoriented at the moment a secret comes out.', ['Keep the line rigidly', 'vstory', 'Clear and calm; the scene plays as a dialogue, the secret lands on performance alone.'], ['Jump the line on the reveal', 'tone', 'A deliberate jolt: the room seems to flip as the relationship does. Risky if any other cut also breaks it.'], ['Dolly across the line slowly', 'stag', 'The world turns with the revelation and nobody loses their bearings. Costs an hour of track-laying.']], 'In the kitchen fight of {F} ({Y}), {D} holds the line for nine minutes, then crosses it on the single word that ends the marriage. Audiences remember the cut, not why it hurt.'],
  [1, 'Shot sizes and what they mean', 'Wide shots establish place and power; mediums carry conversation; close-ups carry thought. The size of the face on screen is a statement of intimacy.', 'Design the scene from the most important moment backwards: decide where the close-up belongs, then spend wider sizes before it so it means something.', ['You have time for only three set-ups on a confession scene.', ['Wide, medium, one close-up on the confessor', 'vstory', 'Classical and safe; the edit has a shape.'], ['One unbroken medium two-shot', 'stag', 'Actors play off each other in real time; no hiding in the cut.'], ['Two close-ups and no wide', 'tone', 'Claustrophobic and intense, but the editor cannot breathe.']], '{D}\'s {F} saves its only extreme close-up for the last reel. By then the audience has been held at a distance for ninety minutes, and it feels like being let in.'],
  [1, 'Blocking for camera', 'Blocking is where the actors move. Good blocking tells the story without cuts: who enters, who sits, who stands up first and who leaves the room.', 'Block with the actors first, then place the camera to catch it. Use height, depth and distance: the person with power often moves, the person losing it is pinned.', ['Two siblings fight over a will. How do you block it?', ['Static, both seated', 'dact', 'It becomes about the words; good for a sharp script.'], ['The younger one circles while the elder stays still', 'stag', 'The power is visible without a line of dialogue.'], ['Let the actors find it', 'dact', 'Sometimes magic, sometimes chaos. Depends on the cast.']], 'In {F}, {A} never sits down in anyone else\'s house until the final scene. Nobody in the audience notices consciously; everyone feels it.'],
  [1, 'The shot list and floor plan', 'Before a shoot day every head of department needs to know what you will shoot and in what order: the shot list (what) and the floor plan (where the camera and lights go).', 'Number the shots, mark which are essential and which are "nice to have", and order them so the lighting changes as few times as possible (shoot all of one direction, then turn around).', ['You are two hours behind at lunch.', ['Drop the nice-to-haves', 'setm', 'You make the day; the edit will be leaner.'], ['Combine shots into a oner', 'stag', 'Elegant if it works, and it might; if not, you\'ve lost more time.'], ['Push for overtime', 'cha', 'You get everything, the producer remembers the bill.']], '{D} famously plans {F} to the shot but marks a third of them "if we\'re lucky". Most days they weren\'t, and the film is better for it.'],
  [2, 'Actable verbs, not results', 'Telling an actor "be angrier" asks for a result they can only fake. Give them an action they can play: to accuse, to plead, to dismiss, to seduce, to punish.', 'Break each scene into beats; give each beat a transitive verb aimed at the other character. Ask "what do you want them to do?" not "what do you feel?"', ['Take three is flat. What do you say?', ['"More energy, please."', 'dact', 'You get louder, not truer.'], ['"This time, make her apologise."', 'dact', 'The actor has something to do; the scene comes alive.'], ['Say nothing; shoot it again', 'com', 'Sometimes the actor finds it alone; sometimes they feel abandoned.']], 'The note that rescued {F}: {D} told {A} to "stop defending yourself and start interrogating him". The performance turned on that verb.'],
  [2, 'Rehearsal and the table read', 'A table read lets the whole cast hear the script; rehearsal lets the director and actors find the scenes before the clock is running.', 'Use rehearsal to agree what each scene is about and what each character wants. Don\'t over-rehearse emotional peaks; leave something to be found in front of the camera.', ['You have a week of rehearsal and a volatile lead.', ['Rehearse everything', 'dact', 'Tight and prepared; risk of a stale take one.'], ['Rehearse the relationships, not the scenes', 'tone', 'The cast arrives knowing each other; the scenes stay fresh.'], ['Skip it: shoot raw', 'tone', 'Lightning or chaos.']], 'The cast of {F} spent their rehearsal week cooking together. {D} said the meal scene was the only one that needed no direction.'],
  [2, 'Tone and the tone reel', 'Tone is the director\'s main job: is this funny, frightening, sad, or all three at once? Every department needs the same answer.', 'Build a tone reel or look book: clips, stills, music, colours. Share it with every head of department and refer back to it whenever a choice is unclear.', ['Your thriller has a darkly funny script. How do you play it?', ['Straight: let the jokes be accidental', 'tone', 'Tense and dry; the laughs come from truth.'], ['Lean into the comedy', 'tone', 'Crowd-pleasing, but the threat evaporates.'], ['Different tone per act', 'vstory', 'Bold; it works if the turns are earned.']], '{F} opens like a comedy and ends like a horror film, and {D} kept the colour palette identical throughout so the shift felt like a betrayal rather than a different film.'],
  [2, 'Coverage versus the oner', 'Coverage (master, singles, inserts) gives the editor choices. A oner (one continuous shot) gives the scene a single, unrepeatable rhythm.', 'Shoot coverage when you need control in the edit; choose the oner when the tension depends on real time and you trust the cast and crew.', ['A hostage scene: twelve minutes of dialogue and a gunshot.', ['Full coverage', 'vstory', 'The editor can tighten every beat.'], ['One handheld oner', 'stag', 'Unbearably tense, and if take nine fails, you start again.']], 'The hostage scene in {F} is a single eleven-minute take. {P} rehearsed it for two days; it was the fourteenth take.'],
  [3, 'Shooting for the edit', 'The best directors know where each shot will cut before they roll it, and give the editor exactly the overlap and options the scene needs.', 'Think in cuts: start each shot a beat before you need it and run it a beat after; repeat key actions in overlap so the editor can cut on movement.', ['The schedule allows one more set-up.', ['A reaction shot of the listener', 'vstory', 'Often the most useful shot in the scene.'], ['A beautiful wide', 'comp', 'Gorgeous, and it may end up in the trailer.'], ['An insert of the letter', 'cont', 'The plot is clearer; the emotion isn\'t.']], 'Editor {E} said {F} cut itself together: "{D} gave me the listener every time."'],
  [3, 'The director\'s cut and notes', 'Under guild rules the director gets a cut before the producers\'. Then come notes from producers, the studio and test audiences.', 'Find the note behind the note. "It\'s slow" often means "I don\'t know what she wants". Fix the cause, not the symptom.', ['The studio wants the ending changed after a poor test screening.', ['Fight for your ending', 'cha', 'If you win, it\'s your film; if you lose, you lose allies.'], ['Find a new ending that answers the note', 'struc', 'Often the best outcome, and the hardest work.'], ['Give them what they ask', 'col', 'Quick peace; you may regret it for years.']], '{F}\'s test cards hated the ending. {D} kept the ending and moved one scene earlier so the audience understood it. Scores went up twelve points.'],
  [3, 'Directing a crowd and a crew', 'A director leads a hundred people every day. How you treat the first assistant director, the actors and the runners decides how the set feels.', 'Decide fast, explain briefly, change your mind openly when someone has a better idea. Protect the actors\' concentration; let the AD run the floor.', ['A crew member suggests a better angle in front of everyone.', ['Take it and say thank you', 'col', 'The crew leans in for the rest of the shoot.'], ['Stick to your plan', 'com', 'Clear authority; the crew stops offering.'], ['Shoot both', 'setm', 'Generous and slow.']], 'Every crew who worked on {F} says the same thing about {D}: "you could tell them anything."']
] };
CURR.wri = { label: 'Screenwriting', icon: '✍️', courses: ['Story structure', 'Scene and character', 'Rewriting'], lessons: [
  [1, 'Want, need and obstacle', 'A protagonist wants something concrete and needs something deeper. The story is the obstacle between them and the want, and what they learn on the way to the need.', 'Write the want in one line ("win the championship") and the need in another ("forgive his father"). Every scene should test one of them.', ['Your hero\'s want is vague.', ['Make it concrete and visible', 'struc', 'The audience can follow and root.'], ['Keep it internal and literary', 'char', 'Subtle; the second act may drift.']], '{W} rewrote {F} for a year before landing on a want you could photograph: a trophy, a deadline, a door.'],
  [1, 'Three acts and eight sequences', 'Frank Daniel\'s sequence approach divides a feature into eight sequences of ten to fifteen minutes, each with its own goal, tension and turn: two in act one, four in act two, two in act three.', 'Card your story into eight sequences. Give each a mini-goal; end each with a turn that changes the protagonist\'s situation.', ['Your second act sags around page sixty.', ['Add a midpoint reversal', 'struc', 'The story turns; the hero wants something new.'], ['Add a subplot', 'char', 'More texture, less drive.'], ['Cut thirty pages', 'struc', 'Lean and fast; the relationships thin out.']], '{F} has a textbook midpoint: at minute 58 {A} learns the job was a set-up, and the film becomes a different chase.'],
  [1, 'Format and the page', 'A page of a properly formatted screenplay runs about a minute. Sluglines, action, character, dialogue and parentheticals each have their place.', 'Write action in the present tense, only what can be seen or heard. Keep paragraphs to three or four lines. White space reads fast; dense pages read slow.', ['Your script is 132 pages.', ['Cut to 110', 'struc', 'Readers finish it.'], ['Cheat the margins', 'dial', 'Every reader can tell.']], 'The draft of {F} that sold was 104 pages; the previous draft was 141. {W} says nothing important was lost.'],
  [1, 'Set-up and pay-off', 'Plant information early so a later moment feels inevitable rather than convenient. Pay off every set-up; cut set-ups you never pay.', 'Keep a list of plants and payoffs. The best plants are disguised as something else: a joke, a prop, a habit.', ['The climax hinges on a skill the hero has never shown.', ['Plant it in act one, disguised', 'struc', 'The ending clicks.'], ['Explain it in the moment', 'dial', 'It feels like a cheat.']], 'The pocket watch in {F} looks like set dressing for an hour. Then it saves a life.'],
  [2, 'Scene construction', 'Every scene needs a want, an obstacle and a turn. Enter late, leave early: start after the scene has begun and leave before it\'s over.', 'For each scene write: whose scene is it, what do they want, what stops them, how is the situation different at the end? Cut any scene with no turn.', ['A scene of two friends catching up has no conflict.', ['Give one friend a secret agenda', 'dial', 'The same chat becomes a duel.'], ['Cut it', 'struc', 'The film is faster; the friendship is thinner.']], '{F}\'s best scene is a breakfast where two characters say "pass the butter" eleven times. It\'s a negotiation over a divorce.'],
  [2, 'Subtext', 'People rarely say what they mean. Audiences love working out what\'s underneath; on-the-nose dialogue tells them they don\'t need to.', 'Write the scene on the nose first, then rewrite it so nobody says the thing. Let behaviour, objects and silences carry it.', ['Your lovers say "I love you" in their first big scene.', ['Keep it', 'dial', 'Clear and sincere; maybe too early.'], ['Make them argue about a parking ticket instead', 'dial', 'The love is visible in the fight.']], 'In {F}, the line everyone quotes is "you left the light on". It means everything except the light.'],
  [2, 'Character arc', 'An arc is the change in a character from beginning to end, usually from a false belief to a truer one. Flat arcs work too: the hero stays the same and changes the world.', 'Write the lie the character believes at page one and the truth they know at the end. Build scenes that challenge the lie, with the biggest challenge at the climax.', ['Your hero doesn\'t change.', ['Give them a flaw to overcome', 'char', 'A classic arc; satisfying.'], ['Let the world change around them', 'char', 'A flat arc; the supporting cast must carry the change.']], '{A} in {F} begins believing nobody can be trusted. The last shot is them handing over their keys.'],
  [2, 'Adaptation', 'Adapting a book, a play or a true story means choosing what to keep, merge and invent. The question is always: what is this story about, in film terms?', 'Read the source three times; write the one-line spine; cut every subplot that doesn\'t serve it; dramatise interior thoughts as actions.', ['The novel is 700 pages and beloved.', ['Faithful, scene by scene', 'adapt', 'The fans approve; the film runs four hours.'], ['Keep the spine, reinvent the rest', 'adapt', 'A better film, and angry letters.']], '{W} cut eleven characters from the novel behind {F} and merged three of them into one. The author sent a thank-you note.'],
  [3, 'Notes and the rewrite', 'Rewriting is writing. Notes come from producers, executives and directors; the craft is in finding the note behind the note and fixing the cause.', 'Group the notes. When three people say different things about the same scene, the scene is the problem. Rewrite in passes: structure, then character, then dialogue.', ['Two producers give you opposite notes.', ['Pick one', 'com', 'One ally, one enemy.'], ['Find the problem underneath both', 'struc', 'Both are satisfied, and the script is better.']], 'The notes on {F} said both "too dark" and "not dark enough". {W} realised the problem was the uneven ending, and fixed that.'],
  [3, 'Genre craft', 'Every genre is a promise: horror promises fear, comedy laughs, thrillers suspense. Meet the conventions, then surprise inside them.', 'List the ten scenes your genre\'s audience expects. Deliver each one, but from an angle they haven\'t seen.', ['A horror script with no scares until page 40.', ['Add a cold open scare', 'gcraft', 'The promise is made early.'], ['Keep the slow burn', 'gcraft', 'Elevated and divisive.']], 'The cold open of {F} lasts ninety seconds and features nobody we ever see again. It sold the film.', 'Horror'],
  [3, 'The writer in the business', 'Specs, pitches, option agreements, writing credits and arbitration: knowing the business protects the work.', 'Register your scripts; read your option agreement for reversion clauses; keep every draft dated in case of a credit arbitration.', ['You\'re offered a low option fee with a long term.', ['Take it: a film might get made', 'pack', 'Maybe. Or your script sits in a drawer for five years.'], ['Ask for a shorter term and a reversion clause', 'pack', 'You keep control if they stall.']], '{W}\'s first script was optioned by {C} for a pittance and sat for six years. The second option had a reversion clause.']
] };
CURR.tv = { label: 'Television writing', icon: '📺', courses: ['The pilot', 'The writers\' room', 'Running a show'], lessons: [
  [1, 'Engines, not endings', 'A film ends; a series has to keep going. A good pilot sets up an engine: a situation that can generate stories for years.', 'State your engine in one line: a doctor who can\'t lie, a family who run a crime ring, a newsroom on deadline. Every episode idea should come out of it.', ['Your pilot resolves its central mystery.', ['Keep it: a satisfying hour', 'struc', 'Great episode, no series.'], ['Open a bigger question at the end', 'struc', 'The audience comes back next week.']], '{W} pitched the series spun off {F} in one line. The network bought the line before reading the pilot.'],
  [1, 'Act breaks and cold opens', 'Broadcast episodes are built around ad breaks: each act ends on a turn or cliffhanger. The cold open hooks the audience before the titles.', 'Plan your act-outs first; write the cold open last, when you know what the episode is about.', ['A streaming platform with no ads wants your episode.', ['Keep the act structure anyway', 'struc', 'Strong rhythm; viewers press "next".'], ['Write one long movement', 'tone', 'More cinematic; harder to sustain.']], ''],
  [2, 'Breaking story on the board', 'In a writers\' room, the episode is "broken" on a whiteboard: acts, then scenes, then the turns, before anyone writes a page.', 'Pitch out loud; build the beats as a group; the writer assigned the episode takes the board and writes the outline (nine to fourteen pages), then the script.', ['The room is stuck on act three.', ['Pitch a bad idea on purpose', 'impro', 'It breaks the silence; the next pitch is the good one.'], ['Wait for the showrunner', 'com', 'Safe and slow.']], ''],
  [2, 'Writing in someone else\'s voice', 'Staff writers write in the show\'s voice, not their own. The showrunner usually rewrites every script.', 'Re-read the bible and three produced episodes before each draft. Match rhythm, jokes per page and how characters talk.', ['Your draft comes back rewritten by the showrunner.', ['Study what changed', 'dial', 'Next draft, fewer changes.'], ['Argue for your version', 'cha', 'Rarely ends well.']], ''],
  [3, 'Seasons and arcs', 'A season balances episodic stories (solved each week) with serialised arcs (paid off across the season).', 'Map the season on one page: where each character starts and ends, the midseason turn, the finale cliffhanger.', ['The network wants more standalone episodes.', ['Make the arcs lighter', 'struc', 'New viewers can jump in.'], ['Keep it serialised', 'struc', 'Devoted fans, smaller audience.']], ''],
  [3, 'The showrunner', 'The showrunner is writer, producer and manager at once: runs the room, rewrites scripts, approves casting, cuts, budgets.', 'Delegate the room to a trusted number two while you\'re on set or in the edit; protect the schedule above everything.', ['Scripts are three weeks behind production.', ['Write them yourself at night', 'eth', 'They\'re good, and you burn out.'], ['Promote your number two to run the room', 'pack', 'The machine keeps moving.']], '']
] };
CURR.cam = { label: 'Cinematography', icon: '🎥', courses: ['Camera and lens', 'Light and exposure', 'The look of a film'], lessons: [
  [1, 'Focal length and perspective', 'Wide lenses exaggerate depth and distort near the edges; long lenses compress depth and flatten faces. The lens is a point of view.', 'Choose a lens family for the film, then a "home" lens (often a 35mm or 40mm for natural perspective) and decide when you leave it.', ['A character is trapped by circumstances. Which lens?', ['Long lens, compressed background', 'comp', 'The world presses in on them.'], ['Wide lens close to the face', 'comp', 'Unsettling, intimate, slightly grotesque.'], ['Your home 35mm', 'comp', 'Honest; the performance does the work.']], '{P} shot {F} almost entirely on one 40mm lens, then switched to a 14mm for the breakdown scene. People felt it without seeing it.'],
  [1, 'Exposure: stop, shutter, ISO', 'Exposure balances aperture (which also sets depth of field), shutter (motion blur; the 180-degree shutter keeps motion natural) and ISO or EI (sensitivity and noise).', 'Set the shutter at twice the frame rate; pick the aperture for depth of field; light to that stop. Use false colour, waveform and zebras to check skin and highlights.', ['A candlelit dinner scene.', ['Open the lens wide, raise the EI', 'light', 'Real candlelight, razor-thin focus, a nervous focus puller.'], ['Add hidden lights to support the candles', 'light', 'Safer focus; it may look lit.']], 'The candlelit scenes in {F} were lit by candles alone. {P} says the focus puller aged a year.'],
  [1, 'Composition and the frame', 'Where things sit in the frame, and how much space surrounds them, tells the audience what matters and how to feel about it.', 'Use headroom and lead room deliberately; short-side framing (looking out of the frame\'s edge) creates unease; symmetry feels controlled; a dirty foreground creates intimacy.', ['An interview-style scene with a liar.', ['Short-side the liar', 'comp', 'Something feels off before they speak.'], ['Centred and symmetrical', 'comp', 'Composed, controlling, slightly menacing.']], 'The lawyer in {F} is always framed against the wall, never the window. The one time they face the window, they tell the truth.'],
  [1, 'Camera movement', 'Movement should be motivated: by a character, a revelation or a change of power. Dolly, crane, Steadicam, handheld and gimbal each feel different.', 'Ask "why does the camera move here?" Push in for realisation; pull back for isolation; handheld for instability; locked-off for observation.', ['A character realises they\'ve been betrayed.', ['Slow push in', 'move', 'Classic and effective.'], ['Lock it off and let them sit', 'tone', 'Colder and more devastating.'], ['Whip to the betrayer', 'move', 'Energetic; risks being showy.']], ''],
  [2, 'Motivated lighting', 'Every light should seem to come from something the audience can believe: a window, a lamp, a screen, the moon. Motivation keeps the image honest.', 'Find the motivating source in each set; key from its direction; add fill only as much as the mood allows; let the practicals (visible lamps) be part of the composition.', ['A night interior with one table lamp in shot.', ['Key from the lamp\'s side, little fill', 'light', 'Moody and believable.'], ['Flat overall light', 'speed', 'Fast to shoot; looks like daytime TV.']], ''],
  [2, 'Contrast ratios and mood', 'The ratio between key and fill light sets the mood: low contrast (2:1) for comedy and romance; high contrast (8:1 or more) for thrillers and noir.', 'Measure the key and fill with a meter or false colour; agree the ratio range for the film with the director; keep it consistent within scenes.', ['The film turns from romance to thriller halfway.', ['Raise the contrast as the story darkens', 'light', 'The audience feels the shift before they know it.'], ['Keep it consistent', 'colour', 'One world; the story carries the change.']], 'The first hour of {F} lives at 2:1; by the end {P} is lighting faces with a single hard source and no fill at all.'],
  [2, 'Coverage and matching', 'Coverage must cut together: matching lens heights, eyelines, lighting continuity and background between angles.', 'Shoot the master first, then move in. When you turn around, cheat the light to match, not reality. Keep eyelines close to the lens for intimacy.', ['The sun is moving and you still need the reverse.', ['Cheat it with a big bounce and silks', 'light', 'It matches; the gaffer earns their lunch.'], ['Shoot it as is', 'speed', 'Fast; the editor curses you.']], ''],
  [2, 'Leading the camera department', 'The DP leads the operator, the first AC (focus), the second AC (slate, cards, reports), the DIT, the gaffer and the key grip.', 'Prep with them, delegate clearly, protect their turnaround. Ask the gaffer and key grip for solutions, not just labour.', ['The gaffer proposes a different lighting plan.', ['Hear it out and try it', 'col', 'Often better; your crew trusts you.'], ['Stick to your plan', 'com', 'Clear, and a missed idea.']], ''],
  [3, 'Designing the look', 'The look is designed in pre-production: format, sensor or stock, aspect ratio, lens family, filtration and a show LUT, tested and signed off before day one.', 'Shoot camera tests with the actual cast, costumes and sets; grade them; agree a LUT and a language (when the camera moves, which lenses, contrast) with the director.', ['The studio wants the film bright and clean; the director wants it grainy and dark.', ['Find a middle grade and test it', 'colour', 'Everyone sees the same images and agrees.'], ['Side with the director', 'tas', 'Beautiful, and a fight later.']], '{P}\'s look for {F}, grainy and amber, was the third test. The first two looked like adverts.'],
  [3, 'Aspect ratio and format', 'Widescreen (2.39:1) suits landscapes and groups; 1.85 is the standard; 1.33 or 1.66 feels intimate and old; large format and film each have their texture.', 'Choose the ratio for the story, not for prestige. Frame for the ratio from the first scout.', ['A chamber drama in one apartment.', ['Academy 1.33', 'comp', 'Intimate and claustrophobic.'], ['Anamorphic widescreen', 'comp', 'The rooms feel lonely and vast.']], 'Shooting {F} in a square frame was {D}\'s idea; {P} hated it for a week and loved it for the rest of the shoot.']
] };
CURR.light = { label: 'Lighting and grip', icon: '💡', courses: ['Lamps and power', 'Shaping light', 'The gaffer\'s plan'], lessons: [
  [1, 'Colour temperature', 'Light has a colour measured in kelvin: tungsten around 3200K (warm), daylight around 5600K (cool). Mixing them is a choice or a mistake.', 'Gel to match (CTB to make tungsten bluer, CTO to warm daylight) or mix deliberately for contrast: warm interiors against blue windows.', ['Daylight windows and tungsten practicals in the same room.', ['Gel the windows warm', 'light', 'Unified and cosy.'], ['Leave the contrast', 'colour', 'Cold outside, warm inside: a story in itself.']], ''],
  [1, 'Hard and soft light', 'Hard light (a small source) gives crisp shadows and texture; soft light (a big source close to the subject) wraps faces and forgives skin.', 'Make light softer by making the source bigger relative to the subject: bounce it, diffuse it through silk, or build a book light (bounce, then diffuse).', ['Beauty close-up of an older lead.', ['Big soft book light', 'light', 'Flattering and warm.'], ['Single hard source', 'light', 'Every line shows; powerful if that\'s the story.']], ''],
  [1, 'Power and safety', 'Lamps draw serious power: generators, distribution, cable runs. The best boy electric manages power; HMIs and big LEDs need planning.', 'Calculate loads before the scout, keep cables tidy and flagged, never over-load a circuit; rain and electricity need a plan.', ['A location\'s house power is weak.', ['Bring a generator', 'bud', 'Reliable; costs money and noise.'], ['Use battery LEDs', 'light', 'Quiet and flexible; less punch.']], ''],
  [2, 'Negative fill and flags', 'Shaping light is as much about taking it away as adding it: black flags and floppies cut spill; negative fill (black on the shadow side) deepens contrast.', 'Before adding a light, ask whether removing some would do the job. The key grip owns this toolkit: flags, nets, silks, frames, stands.', ['A face looks flat in a white room.', ['Add a backlight', 'light', 'Separation; still flat-ish.'], ['Negative fill on the shadow side', 'light', 'Instant shape, no new lamp.']], ''],
  [2, 'Night exteriors', 'Moonlight is blue-ish and from above; streetlights are sodium orange; night needs enough light to see without looking lit.', 'Backlight wet streets for sheen; use a high, soft "moon" source on a crane; keep faces darker than you think.', ['A wide night exterior with no budget for cranes.', ['Wet the street and use the practicals', 'light', 'Cheap and gorgeous.'], ['Day for night in the grade', 'colour', 'Cheap and often fake-looking.']], ''],
  [3, 'Lighting the space, not the shot', 'Great DPs and gaffers light the whole set so actors can move and the director can find the scene; re-lighting every shot is slow.', 'Rig from above where possible; key through windows; use dimmer boards so changes are fast; pre-light tomorrow\'s sets tonight.', ['The director wants freedom to improvise blocking.', ['Light the room 360', 'light', 'Total freedom; less sculpted faces.'], ['Light each shot', 'light', 'Beautiful frames; slow and limiting.']], '']
] };
CURR.edt = { label: 'Editing', icon: '✂️', courses: ['Cutting basics', 'Story in the edit', 'The cutting room'], lessons: [
  [1, 'The assistant\'s job', 'Before anyone cuts, assistants ingest, sync sound to picture, log takes and organise footage into bins by scene. A good organisation saves weeks.', 'Name everything consistently; build a bin per scene; mark circled takes and the script supervisor\'s notes; keep backups in two places.', ['Dailies arrive late and unsynced.', ['Sync overnight', 'eth', 'The editor has them at nine. You don\'t sleep.'], ['Ask for a day', 'com', 'Calm, and a slower edit.']], ''],
  [1, 'Cutting on movement', 'A cut placed in the middle of a movement (a turn, a sit, a reach) is almost invisible because the eye follows the motion across the join.', 'Find the frame where the action is half complete; overlap a few frames; check the eye trace: where the audience is looking before and after the cut.', ['Two takes don\'t quite match.', ['Cut on the movement', 'rhythm', 'The mismatch disappears.'], ['Use a cutaway', 'shape', 'Safe and slightly evasive.']], ''],
  [1, 'J-cuts and L-cuts', 'In a J-cut the sound of the next shot arrives before its picture; in an L-cut the sound of the last shot carries over the next picture. Both smooth transitions and carry emotion.', 'Lead a scene change with sound to pull the audience forward; hold dialogue over a reaction shot to let a line land.', ['A sad scene cuts to a party.', ['J-cut: party noise first', 'sound', 'Jarring, deliberate, alive.'], ['Hard cut to both', 'rhythm', 'A slap; sometimes exactly right.'], ['L-cut: let the silence linger', 'shape', 'Gentle; the party feels hollow.']], ''],
  [2, 'The Kuleshov effect', 'An audience reads a face according to what is cut next to it: the same neutral look plus food reads as hunger, plus a coffin as grief.', 'Use reaction shots to steer meaning; the performance in the edit can differ from the one on set.', ['An actor\'s close-up is too neutral.', ['Recontextualise it with a different cutaway', 'shape', 'The emotion appears.'], ['Find another take', 'cont', 'Maybe there isn\'t one.']], 'Editor {E} built the grief in {F} out of a close-up of {A} that was originally shot for a scene about lunch.'],
  [2, 'Murch\'s rule of six', 'Walter Murch ranks what a cut must serve: emotion (51%), story (23%), rhythm (10%), eye trace (7%), two-dimensional screen plane (5%) and three-dimensional space (4%). Emotion comes first.', 'When a cut breaks continuity but works emotionally, keep it. When it\'s perfect technically and dead emotionally, lose it.', ['The best performance has a continuity error.', ['Use it', 'shape', 'Nobody notices; everybody feels it.'], ['Use the clean take', 'cont', 'Correct and lifeless.']], ''],
  [2, 'Pace and rhythm', 'Pace is how fast the story moves; rhythm is the pattern of cuts. They aren\'t the same: a slow scene can have a fast rhythm.', 'Trim the heads and tails of lines; cut at the moment a thought completes, not when the line ends; let silence breathe in the right places.', ['The first act feels slow.', ['Trim inside scenes', 'rhythm', 'Brisker, same story.'], ['Cut whole scenes', 'shape', 'Faster; something may be lost.']], ''],
  [2, 'Temp music and its trap', 'Editors cut with temporary music to judge rhythm and emotion. Directors fall in love with it ("temp love") and composers have to fight it.', 'Use temp sparingly; vary it; warn the director early that the real score will be different.', ['The director loves the temp score.', ['Keep cutting to it', 'rhythm', 'Easier now, harder later.'], ['Swap to a neutral temp', 'shape', 'The composer will thank you.']], ''],
  [3, 'Finding the film', 'The assembly is always too long and never the film. The edit rewrites the script: scenes move, characters vanish, endings change.', 'Watch the whole thing without stopping; write down where you felt something; restructure around those moments.', ['The film opens slowly; the best scene is in reel two.', ['Restructure: start with it', 'shape', 'A stronger hook; the director must agree.'], ['Tighten the opening', 'rhythm', 'Better, still slow.']], 'The cut of {F} that worked moved the ending to the beginning. Editor {E} calls it "the day the film appeared".'],
  [3, 'Test screenings', 'Recruited audiences score cards and fill focus groups. Numbers matter; silences and restlessness matter more.', 'Watch the audience, not the screen. Fix the reasons behind complaints, and resist chasing every number.', ['Scores are low on the ending.', ['Recut the ending', 'shape', 'Scores rise; the film changes.'], ['Clarify a set-up instead', 'struc', 'Often the real fix.']], ''],
  [3, 'Locking picture', 'Picture lock freezes the edit so sound, music, visual effects and the grade can finish. Changes after lock are expensive.', 'Lock only when the director, producers and studio have signed off; deliver an EDL or AAF and reference video to every department.', ['The producer wants one more change after lock.', ['Make it', 'rhythm', 'Better, and the sound team rebuilds a reel.'], ['Hold the line', 'com', 'The schedule survives.']], '']
] };
CURR.col = { label: 'Colour grading', icon: '🎨', courses: ['Correction', 'Look development', 'Colour management'], lessons: [
  [1, 'Primary correction', 'Primaries adjust the whole frame: lift (shadows), gamma (mids), gain (highlights), white balance and saturation. Correction comes before creativity.', 'Read the scopes (waveform for brightness, vectorscope for colour); balance each shot neutral, then match shots within the scene.', ['A scene was shot as the light changed.', ['Match every shot to the master', 'colour', 'Seamless.'], ['Let it drift', 'tas', 'Natural, and noticeable.']], ''],
  [1, 'Skin tones', 'On a vectorscope every human skin tone falls along the same line, the skin tone line. Faces off the line look ill or false.', 'Isolate skin with a qualifier and keep it near the line while you push the rest of the image.', ['A green-heavy look turns faces sickly.', ['Protect skin with a key', 'colour', 'Bold look, human faces.'], ['Accept it', 'tas', 'Deliberately unsettling.']], ''],
  [2, 'Secondaries and windows', 'Secondary corrections isolate parts of the image by hue, saturation or shape (power windows) and track them through the shot.', 'Darken edges to guide the eye (a vignette); brighten eyes; pull distracting colours down.', ['A red sign in the background steals focus.', ['Desaturate it with a qualifier', 'colour', 'The eye goes to the actor.'], ['Leave it', 'tas', 'Reality is messy.']], ''],
  [2, 'Building a look', 'A look is a consistent set of choices: contrast curve, colour cast in shadows and highlights, saturation, grain. It is designed with the DP in prep and refined in the grade.', 'Build the look on a hero shot; save it as a node tree or LUT; apply across the film; then adjust shot by shot.', ['The director wants "like an old photograph".', ['Warm highlights, lifted blacks, grain', 'colour', 'Nostalgic and soft.'], ['Bleach bypass contrast', 'colour', 'Harsher and metallic.']], ''],
  [3, 'Colour management and HDR', 'Cameras record in log; displays show in SDR or HDR. Colour management (ACES or a managed pipeline) keeps the image consistent from set to cinema to phone.', 'Grade in a managed space; deliver separate SDR and HDR passes; check on a phone as well as the monitor.', ['The streamer wants HDR delivery.', ['Grade HDR first, derive SDR', 'colour', 'Spectacular on good screens.'], ['Grade SDR first', 'tas', 'Safer for most viewers.']], '']
] };
CURR.snd = { label: 'Production sound', icon: '🎙️', courses: ['Microphones', 'On set', 'The sound report'], lessons: [
  [1, 'The boom is king', 'Overhead boom microphones capture the most natural dialogue; lavaliers (radio mics) are a backup or for wide shots where a boom can\'t reach.', 'Boom from above, just out of frame, aimed at the mouth; follow the dialogue between actors; agree frame lines with the camera operator.', ['A wide shot with two cameras.', ['Radio mics on everyone', 'sound', 'Usable, a little boxy.'], ['Ask to drop the wide camera for one take', 'cha', 'Better sound, a grumpy DP.']], ''],
  [1, 'Room tone and wild lines', 'Room tone is thirty seconds of a location\'s silence, recorded so editors can fill gaps. Wild lines are lines recorded without camera, right after a take.', 'Call for room tone at the end of each set-up, with everyone frozen. Grab wild lines while the actor still has the voice.', ['The AD wants to move on without room tone.', ['Insist: thirty seconds', 'com', 'The dialogue editor thanks you.'], ['Skip it', 'speed', 'Post will patch it, badly.']], ''],
  [2, 'Hiding radio mics', 'Lavalier placement fights clothing rustle, sweat and wind. Different fabrics and costumes need different tricks.', 'Tape mics with a loop to relieve strain; use furry covers outdoors; talk to the costume department early about where mics can live.', ['A silk shirt rustles on every move.', ['Move the mic to the hairline', 'sound', 'Clean, with a different tone.'], ['Ask costume for a different shirt', 'cha', 'Clean, and a costume continuity problem.']], ''],
  [2, 'Timecode and sync', 'Camera and sound record separately and are synced in post with timecode and the slate. Drift ruins a day.', 'Jam-sync timecode at call and after lunch; check the slate is in frame and audible; log every take in the sound report.', ['Timecode drifted on a multicam scene.', ['Re-sync from the slates', 'cont', 'Fixable, slowly.'], ['Use waveform sync software', 'sound', 'Fast and usually right.']], ''],
  [3, 'Fighting for sound', 'On set, sound loses most arguments to camera and schedule. The mixer\'s skill is choosing which fights to have.', 'Flag problems once and clearly (a generator, a fridge, an aircraft path); offer solutions; accept that some lines will be ADR.', ['A fridge hum ruins a key scene.', ['Unplug it (and leave your keys inside)', 'cont', 'Clean sound; never forget the fridge.'], ['Live with it', 'speed', 'ADR later.']], '']
] };
CURR.post = { label: 'Sound post-production', icon: '🔊', courses: ['Dialogue and Foley', 'Sound design', 'The mix'], lessons: [
  [1, 'Dialogue editing', 'Dialogue editors clean production sound: remove noise, fill gaps with room tone, and choose the best microphone for each line.', 'Split dialogue onto separate tracks per character or mic; crossfade every edit; patch with room tone so the background never jumps.', ['A line is noisy but the performance is perfect.', ['Clean it with restoration tools', 'sound', 'Usable; slightly processed.'], ['Send it to ADR', 'cont', 'Clean, maybe less alive.']], ''],
  [1, 'ADR', 'Automated dialogue replacement re-records lines in a studio, in sync with picture. Actors find it hard because the scene\'s energy is gone.', 'Play the original take in the actor\'s headphones; match the mic and room; record several takes; let the actor move as they did on set.', ['The actor gives a flat ADR performance.', ['Play them the scene before each take', 'sound', 'They find the energy.'], ['Accept it', 'speed', 'The scene goes flat.']], ''],
  [1, 'Foley', 'Foley artists perform everyday sounds to picture: footsteps, cloth, props. It makes a film feel physical and is needed for foreign-language versions.', 'Record footsteps on matching surfaces; perform cloth passes for every character; choose props for sound, not looks (a cabbage for a punch).', ['A fight scene sounds weak.', ['Layer Foley punches', 'sdes', 'Bone-crunching.'], ['Use library effects', 'speed', 'Generic.']], ''],
  [2, 'Sound design', 'Sound design builds the emotional world: the hum of a room, a distant train, a creature\'s breath. Often what an audience "feels" is sound they never notice.', 'Design a palette per location and character; use low frequencies for dread, silence for impact; record your own sounds.', ['A haunted house needs to feel alive.', ['Subtle room tones that breathe', 'sdes', 'Unease without knowing why.'], ['Loud stingers', 'sdes', 'Jumps, and cheap ones.']], '', 'Horror'],
  [3, 'The re-recording mix', 'The mix balances dialogue, music and effects into the final soundtrack, delivered as stems for foreign versions and to loudness specifications for cinema, TV and streaming.', 'Mix dialogue first and keep it intelligible; give music and effects room by scene; deliver stems (dialogue, music, effects) and the M&E track.', ['The director wants the music louder than the dialogue.', ['Duck the music under key lines', 'sound', 'Everyone hears the words.'], ['Do as asked', 'col', 'Emotional, and confusing.']], '']
] };
CURR.sup = { label: 'Script supervision', icon: '📋', courses: ['Continuity', 'Making it cut', 'Notes for the editor'], lessons: [
  [1, 'Continuity', 'The script supervisor tracks everything that must match between takes and shots: props, costume, hands, cigarettes, eyelines, dialogue.', 'Photograph each set-up; note which hand holds what on which line; flag deviations quietly to the AD or director.', ['An actor improvises a better line.', ['Note it and flag the change for later scenes', 'cont', 'The edit can use it.'], ['Insist on the scripted line', 'com', 'Correct and joyless.']], ''],
  [2, 'Screen direction and eyelines', 'Characters looking and moving left-to-right must stay that way across cuts, or the geography breaks. Eyelines must point where the other person is.', 'Mark screen direction on the facing pages; check eyelines against the master; warn before a set-up crosses the line.', ['The director wants a shot that crosses the line.', ['Warn them, then shoot it', 'cont', 'Their choice, made knowingly.'], ['Stay silent', 'com', 'A problem in the cutting room.']], ''],
  [3, 'The lined script', 'The lined script shows, with vertical lines on each page, which shots cover which lines. Editors use it every day.', 'Draw a line per set-up through the dialogue it covers; zig-zag where a character is off camera; note circled takes and timing.', ['Coverage of a key line is missing.', ['Ask for a pickup', 'cont', 'Ten minutes now saves a reshoot.'], ['Hope the edit hides it', 'speed', 'It won\'t.']], '']
] };
CURR.ad = { label: 'Assistant directing', icon: '📣', courses: ['Breakdown and schedule', 'Running the floor', 'Safety and people'], lessons: [
  [1, 'Breaking down the script', 'The first AD breaks the script into elements per scene: cast, extras, props, vehicles, stunts, effects, location, day or night. The breakdown feeds the schedule.', 'Number scenes; count pages in eighths; tag every element; build strips for a stripboard.', ['A scene has a horse, rain and a child.', ['Schedule it early in the day', 'setm', 'Child hours and daylight are respected.'], ['Schedule it last', 'setm', 'Everyone is tired; the horse is not.']], ''],
  [1, 'The schedule and day out of days', 'The schedule orders scenes by location, cast availability and daylight, not by story. The day-out-of-days shows when each actor works, so you can pay them less.', 'Group by location first, then cast; front-load difficult days; keep expensive actors\' days together.', ['A star is only available for four days.', ['Schedule all their scenes together', 'setm', 'Affordable; emotionally out of order.'], ['Shoot in story order', 'dact', 'Better performance, much more expensive.']], ''],
  [1, 'The call sheet', 'Sent the night before: call times, scenes, cast, locations, weather, hospital, and anything special. Every department plans from it.', 'Proof it twice; send it on time; include safety notes and nearest hospital; update it when anything changes.', ['Rain is forecast tomorrow.', ['Add a cover set', 'setm', 'The day isn\'t lost.'], ['Gamble on the weather', 'speed', 'A sunny day, or a lost day.']], ''],
  [2, 'Running the floor', 'The first AD runs the set: rehearsal, lighting, "final checks", "rolling", "background action". The director says "action" and "cut".', 'Keep the set moving; give the crew time warnings; protect the director\'s time with actors; call the shot list out loud.', ['The director wants another take; you\'re behind.', ['Give them one more, then move on', 'setm', 'Both sides feel heard.'], ['Push them to move on', 'cha', 'You make the day; the director sulks.']], ''],
  [2, 'Background action', 'Extras make the world real. The second AD and second second place them, give them business, and reset them for every take.', 'Give each extra a simple task and a path; mark first positions; vary cross traffic so it looks unplanned.', ['A crowd scene looks fake.', ['Give each extra a small story', 'cha', 'The crowd breathes.'], ['Add more extras', 'bud', 'Busier, no more real.']], ''],
  [3, 'Safety meetings', 'Before every stunt, effect, weapon or vehicle shot, the AD holds a safety meeting with everyone involved. On set, safety is the AD\'s job.', 'Walk through the action; name who can call "cut"; clear non-essential crew; confirm medics and fire.', ['The schedule doesn\'t allow a safety rehearsal.', ['Rehearse anyway', 'com', 'You lose twenty minutes; nobody gets hurt.'], ['Skip it', 'speed', 'You might get away with it.']], '']
] };
