// ---------------- The curriculum, part three: music, audio, online and stage ----------------
CURR.mus = { label: 'Film scoring', icon: '🎼', courses: ['Music and picture', 'Orchestration', 'The scoring stage'], lessons: [
  [1, 'Spotting', 'The spotting session decides where music starts and stops, and what each cue is for. Music should begin and end for a reason.', 'Watch the cut with the director; note in and out times; name each cue\'s job (tension, emotion, transition) and what it must not do.', ['The director wants music under every scene.', ['Argue for silences', 'score', 'The music that remains matters more.'], ['Score wall to wall', 'theme', 'Lush and numbing.']], ''],
  [1, 'Themes and leitmotifs', 'A theme is a short, recognisable idea that can be rearranged for any mood; a leitmotif attaches a theme to a character, place or idea.', 'Write a few notes that work sad, triumphant and frightening; vary orchestration, tempo and harmony across the film.', ['The hero needs a theme.', ['A big, hummable melody', 'theme', 'Iconic and familiar.'], ['A four-note motif', 'theme', 'Flexible and subtle.']], 'The four-note theme in {F} is first played on a toy piano. By the finale it\'s a full orchestra.'],
  [2, 'Writing to picture', 'Scores sync to picture through tempo maps and hit points; cues are written in a DAW against the locked cut with a click track.', 'Map tempo to hit key cuts; avoid hitting every action ("mickey-mousing") unless it\'s comedy.', ['A chase with forty cuts.', ['Hit the big moments only', 'score', 'Driving and clear.'], ['Hit every cut', 'score', 'Cartoonish.']], ''],
  [2, 'Orchestration', 'Orchestration assigns notes to instruments: register, colour and balance. Strings carry emotion; brass power; woodwinds character; percussion pulse.', 'Keep dialogue frequencies clear (avoid busy mid-range under speech); double melodies for weight; use mutes and extended techniques for colour.', ['A tender scene with whispered dialogue.', ['Solo piano in a high register', 'orch', 'Clear and intimate.'], ['Full strings', 'orch', 'Beautiful, and drowns the words.']], ''],
  [3, 'Mockups and the scoring session', 'Composers present MIDI mockups for approval, then record with live players. Union sessions are planned to the minute.', 'Make mockups good enough to judge; prepare parts and click; record the hardest cues first while players are fresh.', ['Budget allows one day of orchestra.', ['Record the big themes live, the rest with samples', 'orch', 'Live where it counts.'], ['Record everything with a small ensemble', 'score', 'Intimate and cohesive.']], ''],
  [3, 'Licensing and cue sheets', 'Using an existing song needs sync (composition) and master (recording) licences. Cue sheets list all music so writers are paid.', 'Clear music early; budget for options; fill in cue sheets accurately for royalties.', ['The perfect song costs a fortune.', ['Pay it', 'bud', 'The scene sings.'], ['Commission a sound-alike', 'song', 'Cheaper; a little hollow.']], '']
] };
CURR.prodm = { label: 'Music production', icon: '🎚️', courses: ['Signal and sound', 'Recording', 'Mixing and mastering'], lessons: [
  [1, 'Signal flow and gain staging', 'Sound travels from source to microphone to preamp to converter to the DAW. Gain staging keeps healthy levels at each step: not too quiet (noise), not too hot (distortion).', 'Set preamp levels so peaks hit around -10 to -6 dBFS; keep plugin chains at sensible levels; leave headroom.', ['The singer is quiet, then belts.', ['Ride the gain and compress lightly', 'sound', 'Clean recording.'], ['Set it hot for the quiet parts', 'sound', 'The chorus clips.']], ''],
  [1, 'Microphone choice and placement', 'Condensers capture detail; dynamics handle loud sources; ribbons are smooth. Distance and angle change tone as much as the mic.', 'Move the mic before reaching for EQ; use the proximity effect for warmth; check phase with multiple mics.', ['An acoustic guitar sounds boomy.', ['Move the mic towards the neck', 'sound', 'Balanced.'], ['EQ out the low end', 'sound', 'Thin.']], ''],
  [2, 'EQ and compression', 'EQ shapes tone by frequency; compression controls dynamics. Both are best used subtly and for a reason.', 'Cut before boosting; high-pass everything that doesn\'t need low end; compress for control, then for character.', ['The mix is muddy.', ['Cut 200-400 Hz on several tracks', 'sound', 'Clarity.'], ['Boost the highs', 'sound', 'Harsh and still muddy.']], ''],
  [2, 'Arrangement', 'Arrangement decides what plays when. Great productions leave space: the verse is sparse so the chorus can lift.', 'Map the energy of the song section by section; add and remove parts; give each element its own register.', ['The chorus doesn\'t lift.', ['Strip the verse back', 'song', 'The chorus explodes.'], ['Add more to the chorus', 'sound', 'Louder, not bigger.']], ''],
  [3, 'Mixing and mastering', 'Mixing balances the tracks; mastering polishes the final stereo file for loudness, tone and consistency across a record.', 'Reference commercial tracks; mix at moderate levels; master for streaming loudness targets rather than maximum loudness.', ['The label wants it louder.', ['Master hot', 'sound', 'Loud and squashed.'], ['Master to streaming targets', 'sound', 'It breathes; the platform normalises it anyway.']], '']
] };
CURR.song = { label: 'Songwriting', icon: '🎵', courses: ['Song form', 'Lyrics', 'Co-writing and the business'], lessons: [
  [1, 'Song form', 'Most popular songs use verse, pre-chorus, chorus and bridge. The verse tells; the chorus sums up; the bridge offers a new angle.', 'Write the chorus first; make the verse lower or sparser; use the bridge for contrast in melody, harmony or perspective.', ['The verse is catchier than the chorus.', ['Swap them', 'song', 'A hit, maybe.'], ['Rewrite the chorus', 'song', 'Harder, better.']], ''],
  [1, 'Hooks', 'A hook is the part people remember: a melody, a lyric, a riff, a rhythm. Many hits have several.', 'Place the title on the strongest melodic moment; repeat it; build a second instrumental hook.', ['Your title is buried in the verse.', ['Move it to the chorus downbeat', 'song', 'Unforgettable.'], ['Leave it', 'theme', 'Artful and forgettable.']], ''],
  [2, 'Prosody', 'Prosody is the fit between words and music: stressed syllables on strong beats, rising melody for rising feeling, unstable chords for unstable lyrics.', 'Speak the lyric naturally and mark the stresses; set them on downbeats; match the emotional shape of melody and words.', ['A sad lyric on a bouncy melody.', ['Make the melody fall', 'song', 'Aligned and moving.'], ['Keep the contrast', 'theme', 'Ironic; can be brilliant.']], ''],
  [2, 'Rhyme and point of view', 'Rhyme types (perfect, family, additive, assonance) give different feels; point of view (first, second, third person) changes intimacy.', 'Use perfect rhymes for resolution, looser rhymes for unease; choose the point of view that gives the listener a place to stand.', ['A breakup song.', ['Second person: "you left"', 'song', 'Direct and raw.'], ['Third person story', 'song', 'Distance and detail.']], ''],
  [3, 'Co-writing and publishing', 'Most hits are co-written. Splits are agreed in the room; publishers collect royalties and pitch songs for sync.', 'Agree splits before you leave the room; register songs with your performing rights organisation; keep work tapes.', ['Your co-writer wants 70%.', ['Negotiate to an even split', 'cha', 'Fair and lasting.'], ['Accept to keep the peace', 'col', 'Resentment later.']], '']
] };
CURR.pod = { label: 'Podcasting', icon: '🎙️', courses: ['Audio storytelling', 'Interviewing', 'Building a show'], lessons: [
  [1, 'Formats', 'Podcasts come in formats: chat, interview, narrative (reported and scripted), fiction, news. Each has different production costs and audiences.', 'Pick a format you can sustain weekly; write a one-line promise for the show.', ['You have little time and a big idea.', ['Interview show', 'cha', 'Sustainable.'], ['Narrative series', 'struc', 'Prestige; months of work.']], ''],
  [1, 'Recording and loudness', 'Good audio starts with the room: soft furnishings, close mics, consistent levels. Platforms expect around -16 LUFS for stereo.', 'Record each person on their own track; use pop filters; normalise to the target loudness in the master.', ['A guest records on a laptop mic.', ['Send them a USB mic', 'bud', 'Clean audio.'], ['Fix it in post', 'sound', 'It never sounds right.']], ''],
  [2, 'Interviewing', 'Open questions, follow-ups and silences get stories; closed questions get one-word answers.', 'Research; plan an arc; listen more than you talk; ask "how did that feel?" and "what happened next?"', ['A guest gives rehearsed answers.', ['Ask about something small and specific', 'cha', 'They forget the script.'], ['Push harder', 'com', 'They close up.']], ''],
  [2, 'Editing for story', 'Editing removes not just ums but tangents; narrative shows use tape (recorded voices) and narration in alternation.', 'Paper-edit the transcript; keep the best tape; write narration that sets up and gets out of the way.', ['A great tangent.', ['Cut it', 'shape', 'Tighter.'], ['Make it a bonus episode', 'mkt', 'More content.']], ''],
  [3, 'Growing an audience', 'Audiences grow episode by episode: consistency, show notes, guest cross-promotion, appearances on other shows.', 'Release on a fixed day; ask listeners to share; swap promos with similar shows.', ['A network offers a deal for 50% of ad revenue.', ['Sign', 'pack', 'Reach and ad sales.'], ['Stay independent', 'mkt', 'Smaller, all yours.']], '']
] };
CURR.creator = { label: 'Online video', icon: '📺', courses: ['The click', 'Retention', 'The channel'], lessons: [
  [1, 'Titles and thumbnails', 'Click-through rate is clicks divided by impressions. The title and thumbnail make a promise; the video must keep it.', 'One clear subject in the thumbnail, high contrast, three to five words maximum; the title adds what the image can\'t.', ['Your thumbnail is busy.', ['One face, one object, one word', 'mkt', 'CTR rises.'], ['Keep the detail', 'tas', 'Pretty, ignored.']], ''],
  [1, 'Hooks', 'Most viewers decide in the first seconds. The hook proves the title and promises more.', 'Start with the payoff or the question; cut the intro; show, don\'t announce.', ['Your video starts with "hey guys".', ['Open on the best moment', 'rhythm', 'Retention jumps.'], ['Keep your intro', 'cha', 'Loyal fans like it; new ones leave.']], ''],
  [2, 'The retention graph', 'Analytics show where viewers leave. Dips mark boring or confusing moments; spikes mark what people rewatch.', 'Study the graph; cut slow sections; add pattern interrupts every 30-60 seconds.', ['Viewers drop at minute three.', ['Cut that section', 'rhythm', 'The graph flattens.'], ['Add a joke', 'comic', 'Maybe.']], ''],
  [3, 'Brand deals and burnout', 'Creators earn from ads, sponsorships, merch and memberships. The schedule never stops, and burnout is common.', 'Batch-film; hire an editor early; turn down sponsors that don\'t fit; take planned breaks.', ['A sponsor pays well but doesn\'t fit.', ['Decline', 'tas', 'Trust kept.'], ['Accept', 'mkt', 'Money now; comments sour.']], '']
] };
CURR.stage = { label: 'Theatre and stage management', icon: '🎟️', courses: ['Rehearsal', 'Tech', 'Running the show'], lessons: [
  [1, 'The prompt book', 'The stage manager\'s prompt book holds the script, blocking notation, every cue and every note. It is the show\'s bible.', 'Notate blocking in pencil with standard shorthand (X for cross, DSL for downstage left); number cues; keep rehearsal reports daily.', ['Blocking changes daily.', ['Pencil and daily updates', 'setm', 'Always current.'], ['Wait until it settles', 'speed', 'You\'ll miss something.']], ''],
  [2, 'Tech week', 'Tech adds lights, sound, set and costume. Paper tech puts cues in the book; cue-to-cue skips the acting between them.', 'Run paper tech before the stage time; call cues by number and standby; record every change.', ['A cue keeps landing late.', ['Move your standby earlier', 'setm', 'Clean.'], ['Ask the operator to watch the stage', 'col', 'Inconsistent.']], ''],
  [3, 'Running the show', 'After opening, the stage manager maintains the show: calling every performance, rehearsing understudies, keeping it as the director left it.', 'Give notes after each show; schedule understudy rehearsals; track wear on set and costumes.', ['The lead is ill at the half.', ['Put the understudy on', 'setm', 'The show goes on.'], ['Cancel', 'com', 'Refunds and disappointment.']], '']
] };
