// ---------------- Famous faces, true to type ----------------
// The well-known people in the catalogue behave like their real counterparts, as far as their public reputations go,
// with a little spin. Each persona gives:
//   g: the genres they gravitate to (the films they make or star in lean this way, most of the time, not always)
//   no: genres they steer clear of; t: traits; m: nudges to the mind (vision, taste, charisma, work ethic,
//   collaboration, composure); v: temperament [warmth, intensity, control, play], each -2..2, used to pull similar
//   people together and push clashing ones apart; like: what they value in the people they hire, on your style axes
//   (generous, bold, loyal, driven, straight); tx: how they text; w: at work; o: off the clock; pals: real collaborators.
// The world never prints the real names: these people go by their in-game names.
const PERSONAS = {
  // ---- directors ----
  'Steven Spielberg': { g: ['Sci-fi', 'Action', 'Drama', 'War'], t: ['Workhorse', 'Beloved', 'Commercial'], m: { vis: 3, eth: 2, col: 2 }, v: [2, 1, 1, 1], like: { loyal: 1, gen: .5 }, tx: 'long', w: 'Shoots fast, thinks in shots, and has used the same composer for fifty years.', o: 'Plays video games, collects old props, and calls his old friends on their birthdays.', pals: ['George Lucas', 'Tom Hanks', 'Harrison Ford'] },
  'George Lucas': { g: ['Sci-fi', 'Fantasy', 'Action'], t: ['Visionary', 'Shy', 'Commercial'], m: { vis: 4, cha: -2, col: -1 }, v: [0, 0, 2, 0], like: { amb: .5, honest: .5 }, tx: 'terse', w: 'Happier in the edit and the effects shop than on set. Direction to actors: "faster, more intense".', o: 'Builds things. Archives everything. Wears the same flannel shirt to every meeting.', pals: ['Steven Spielberg', 'Francis Ford Coppola', 'Harrison Ford'] },
  'Francis Ford Coppola': { g: ['Drama', 'Crime', 'War'], t: ['Visionary', 'Spendthrift', 'Reckless'], m: { vis: 4, com: -2 }, v: [1, 2, -1, 1], like: { bold: 1, gen: .5 }, tx: 'long', w: 'Bets the house on every film, sometimes literally. Calls it "the adventure".', o: 'Makes wine, cooks for forty, and is probably remortgaging something.', pals: ['George Lucas', 'Robert Duvall'] },
  'Martin Scorsese': { g: ['Crime', 'Drama', 'Documentary'], t: ['Cinephile', 'Workhorse', 'Perfectionist'], m: { vis: 3, tas: 3, eth: 2 }, v: [1, 2, 1, 1], like: { loyal: 1, bold: .5 }, tx: 'long', w: 'Talks at the speed of a projector about films you have not seen. Has an editor for life.', o: 'Restores old films. Watches more of them than anyone alive. Loves his mother\'s cooking on camera.', pals: ['Robert De Niro', 'Leonardo DiCaprio', 'Joe Pesci'] },
  'Quentin Tarantino': { g: ['Crime', 'Action', 'Western', 'Martial arts'], no: ['Animation', 'Superhero'], t: ['Cinephile', 'Auteur', 'Showboat'], m: { tas: 3, cha: 2, col: -1 }, v: [1, 2, 1, 2], like: { bold: 1.2 }, tx: 'caps', w: 'Writes long, talks longer, shoots on film, no phones on set. Says he will stop at ten.', o: 'Runs his own cinema. Owns every VHS tape you ever rented. Will tell you about all of them.', pals: ['Samuel L. Jackson', 'Uma Thurman', 'Brad Pitt'] },
  'Christopher Nolan': { g: ['Sci-fi', 'Thriller', 'War', 'Superhero'], no: ['Comedy', 'Musical'], t: ['Perfectionist', 'Disciplined', 'Visionary'], m: { vis: 4, com: 3, eth: 2 }, v: [-1, 1, 2, -1], like: { honest: 1, amb: .5 }, tx: 'formal', w: 'Shoots it for real when he can. No chairs, no phones, tea in a flask. Wears a blazer to a war zone.', o: 'Reportedly has no email. Reads physics for fun.', pals: ['Michael Caine', 'Cillian Murphy'] },
  'David Fincher': { g: ['Thriller', 'Crime', 'Drama'], no: ['Musical', 'Animation'], t: ['Perfectionist', 'Difficult', 'Cynical'], m: { vis: 3, com: 2, col: -2 }, v: [-2, 1, 2, 0], like: { honest: 1, amb: .5 }, tx: 'terse', w: 'Take forty-seven, and he is just getting interested. The colour is always the colour of a bruise.', o: 'Spends the weekend fixing the sound mix of something that already came out.', pals: ['Brad Pitt', 'Trent Reznor'] },
  'Wes Anderson': { g: ['Comedy', 'Drama', 'Animation'], no: ['Horror', 'Superhero'], t: ['Auteur', 'Perfectionist', 'Loyal'], m: { vis: 4, tas: 3 }, v: [1, -1, 2, 2], like: { loyal: 1.2, gen: .5 }, tx: 'formal', w: 'Everything centred, everything pastel. The cast lives together in one hotel and eats together every night.', o: 'Wears corduroy in all weathers. Sends handwritten notes.', pals: ['Bill Murray', 'Owen Wilson', 'Jason Schwartzman'] },
  'Clint Eastwood': { g: ['Western', 'Drama', 'War', 'Crime'], t: ['Disciplined', 'Calm', 'Frugal'], m: { com: 4, eth: 2 }, v: [0, -1, 2, 0], like: { loyal: 1, honest: .5 }, tx: 'terse', w: 'One take, two at most. Says "okay" instead of "action". Finishes early and under budget.', o: 'Plays jazz piano, golfs, and does not do small talk.', pals: ['Morgan Freeman', 'Gene Hackman'] },
  'Spike Lee': { g: ['Drama', 'Crime', 'Documentary', 'Comedy'], t: ['Auteur', 'Volatile', 'Ambitious'], m: { vis: 3, cha: 2 }, v: [1, 2, 1, 1], like: { honest: 1, bold: 1 }, tx: 'caps', w: 'Says it to your face. Shoots with a double dolly, scores with a full band.', o: 'Courtside at every home game, heckling the opposition.', pals: ['Denzel Washington', 'Samuel L. Jackson'] },
  'Tim Burton': { g: ['Fantasy', 'Horror', 'Animation', 'Comedy'], t: ['Visionary', 'Shy', 'Loyal'], m: { vis: 4, cha: -1 }, v: [1, 0, 0, 2], like: { loyal: 1, gen: .5 }, tx: 'lower', w: 'Draws instead of explaining. Casts the same handful of oddballs every time.', o: 'Sketches in cafés. Wears black in the desert.', pals: ['Johnny Depp', 'Helena Bonham Carter', 'Danny Elfman'] },
  'James Cameron': { g: ['Sci-fi', 'Action', 'Romance'], t: ['Perfectionist', 'Difficult', 'Ambitious'], m: { vis: 4, eth: 3, col: -2, com: -1 }, v: [-1, 2, 2, 0], like: { amb: 1, honest: .5 }, tx: 'caps', w: 'Builds the technology first, then the film. Has been known to fire people with a nail gun, metaphorically.', o: 'Goes to the bottom of the ocean. Alone. For fun.', pals: ['Arnold Schwarzenegger', 'Sigourney Weaver'] },
  'Ridley Scott': { g: ['Sci-fi', 'Period', 'War', 'Thriller'], t: ['Workhorse', 'Visionary', 'Stubborn'], m: { vis: 3, eth: 3 }, v: [0, 1, 2, -1], like: { amb: 1 }, tx: 'terse', w: 'Four cameras, a storyboard he drew himself, and the next film already in prep.', o: 'Paints. Drinks good red wine. Is already shooting another film.', pals: ['Russell Crowe'] },
  'Kathryn Bigelow': { g: ['Action', 'Thriller', 'War'], t: ['Disciplined', 'Visionary', 'Discreet'], m: { vis: 3, com: 3 }, v: [0, 2, 2, -1], like: { bold: 1, honest: .5 }, tx: 'formal', w: 'Shoots like a war reporter: handheld, close, no comfort.', o: 'Trained as a painter. Says little in interviews and means all of it.', pals: [] },
  'Sofia Coppola': { g: ['Drama', 'Period', 'Romance'], no: ['Action', 'Superhero'], t: ['Auteur', 'Shy', 'Discreet'], m: { tas: 4, cha: -1 }, v: [1, -1, 1, 1], like: { honest: .5, loyal: .5 }, tx: 'lower', w: 'Quiet sets, long silences, a perfect soundtrack.', o: 'Fashion people, old music, a very small group of friends.', pals: ['Bill Murray', 'Kirsten Dunst'] },
  'Greta Gerwig': { g: ['Comedy', 'Drama', 'Period'], t: ['Gregarious', 'Bookish', 'Optimist'], m: { cha: 3, col: 3 }, v: [2, 1, 0, 2], like: { gen: 1, honest: .5 }, tx: 'emoji', w: 'Rehearses like a theatre company, dances with the crew, cries at the dailies.', o: 'Reads everything. Writes on index cards. Tells everyone they\'re doing great, and means it.', pals: ['Saoirse Ronan', 'Timothée Chalamet', 'Noah Baumbach'] },
  'Jordan Peele': { g: ['Horror', 'Comedy', 'Thriller'], t: ['Witty', 'Visionary', 'Curious'], m: { vis: 3, cha: 2 }, v: [1, 1, 1, 2], like: { bold: 1, honest: .5 }, tx: 'emoji', w: 'Treats a scare like a punchline: it\'s all timing.', o: 'Collects creepy figurines. Still does impressions at dinner.', pals: [] },
  'Steven Soderbergh': { g: ['Crime', 'Thriller', 'Drama', 'Comedy'], t: ['Workhorse', 'Curious', 'Frugal'], m: { eth: 4, vis: 2 }, v: [0, 0, 1, 1], like: { amb: .5, honest: .5 }, tx: 'terse', w: 'Shoots it, lights it and cuts it himself, under two pseudonyms. On an iPhone, sometimes.', o: 'Makes his own tequila. Posts a list of everything he watched and read that year.', pals: ['George Clooney', 'Matt Damon'] },
  'Paul Thomas Anderson': { g: ['Drama', 'Period', 'Comedy'], t: ['Auteur', 'Perfectionist', 'Loyal'], m: { vis: 3, tas: 3 }, v: [1, 1, 1, 1], like: { loyal: 1, bold: .5 }, tx: 'lower', w: 'Shoots on film, rehearses in the car park, casts his friends.', o: 'Makes music videos for bands he likes. Lives quietly in the Valley.', pals: ['Philip Seymour Hoffman', 'Daniel Day-Lewis', 'Joaquin Phoenix'] },
  'Denis Villeneuve': { g: ['Sci-fi', 'Thriller', 'Drama'], t: ['Calm', 'Visionary', 'Humble'], m: { vis: 4, com: 3 }, v: [1, 0, 2, -1], like: { honest: 1, gen: .5 }, tx: 'formal', w: 'Huge films made very quietly. Never raises his voice.', o: 'Has wanted to make one particular sci-fi book since he was a teenager. Did.', pals: [] },
  'Guillermo del Toro': { g: ['Fantasy', 'Horror', 'Animation'], t: ['Gregarious', 'Visionary', 'Kind'], m: { vis: 4, cha: 3 }, v: [2, 1, 0, 2], like: { gen: 1, loyal: .5 }, tx: 'emoji', w: 'Loves his monsters more than his heroes. Designs every creature by hand.', o: 'Lives in a house full of monsters, notebooks and rain machines. Hugs everyone.', pals: ['Ron Perlman', 'Doug Jones'] },
  'Michael Bay': { g: ['Action', 'Sci-fi'], no: ['Drama', 'Romance', 'Period'], t: ['Showboat', 'Commercial', 'Volatile'], m: { vis: 2, com: -2, eth: 2 }, v: [0, 2, 1, 1], like: { bold: 1, amb: .5 }, tx: 'caps', w: 'If it can explode, it will. The sunset is always the sunset.', o: 'Fast cars, big dogs, bigger houses.', pals: [] },
  'Ron Howard': { g: ['Drama', 'Period', 'Comedy'], t: ['Beloved', 'Humble', 'Diplomatic'], m: { cha: 2, col: 3, com: 2 }, v: [2, -1, 1, 0], like: { gen: 1, loyal: .5 }, tx: 'formal', w: 'The nicest person on any set. Brings his whole family along as extras.', o: 'Doesn\'t do scandal. Wears a cap.', pals: ['Tom Hanks'] },
  'Robert Rodriguez': { g: ['Action', 'Crime', 'Fantasy'], t: ['Frugal', 'Hustler', 'Workhorse'], m: { eth: 4 }, v: [1, 1, 0, 2], like: { amb: 1, bold: .5 }, tx: 'emoji', w: 'Writes, shoots, cuts, scores and cooks for the crew. On a budget that would make a student blush.', o: 'Teaches ten-minute cooking schools. Paid for his first film by testing medicine.', pals: ['Quentin Tarantino', 'Danny Trejo'] },
  'John Carpenter': { g: ['Horror', 'Sci-fi', 'Action'], t: ['Cynical', 'Frugal', 'Calm'], m: { vis: 2, com: 2 }, v: [0, -1, 1, 1], like: { honest: 1 }, tx: 'terse', w: 'Writes the theme music himself in an afternoon.', o: 'Plays video games all day and says so. Not interested in your opinion of it.', pals: ['Kurt Russell', 'Jamie Lee Curtis'] },
  'Sam Raimi': { g: ['Horror', 'Superhero', 'Comedy'], t: ['Witty', 'Loyal', 'Curious'], m: { vis: 2, col: 2 }, v: [1, 1, 0, 2], like: { loyal: 1.2 }, tx: 'emoji', w: 'Puts his old car in every film and his best friend through hell.', o: 'Wears a suit and tie to direct. Every day. Even in the woods.', pals: ['Bruce Campbell'] },
  'Joel Coen': { g: ['Crime', 'Comedy', 'Western', 'Drama'], t: ['Auteur', 'Discreet', 'Witty'], m: { tas: 3, com: 3 }, v: [0, -1, 2, 2], like: { honest: .5, loyal: .5 }, tx: 'terse', w: 'Storyboards every shot, finishes his brother\'s sentences.', o: 'Gives interviews like a man waiting for a bus.', pals: ['Ethan Coen', 'Frances McDormand', 'John Goodman'] },
  'Ethan Coen': { g: ['Crime', 'Comedy', 'Western'], t: ['Auteur', 'Discreet', 'Bookish'], m: { tas: 3, com: 3 }, v: [0, -1, 2, 2], like: { honest: .5, loyal: .5 }, tx: 'terse', w: 'Edits under a made-up name. Laughs at the bleak bits.', o: 'Writes plays and poems. Shrugs a lot.', pals: ['Joel Coen'] },
  'Richard Linklater': { g: ['Drama', 'Comedy', 'Romance'], t: ['Calm', 'Curious', 'Humble'], m: { col: 3, com: 2 }, v: [2, -1, -1, 1], like: { gen: .5, honest: .5 }, tx: 'lower', w: 'Shoots over twelve years if that\'s what it takes. Lets actors talk.', o: 'Runs a film society in Texas. Unbothered by Hollywood.', pals: ['Ethan Hawke', 'Matthew McConaughey'] },
  'Tim Miller': { g: ['Action', 'Sci-fi', 'Superhero'], t: ['Witty', 'Stubborn'], m: { vis: 2 }, v: [0, 1, 1, 1], like: { bold: .5 }, tx: 'lower', w: 'Came up through effects. Fights for the R rating.', o: 'Plays tabletop games.', pals: [] },
  'Ava DuVernay': { g: ['Drama', 'Documentary'], t: ['Disciplined', 'Ambitious', 'Diplomatic'], m: { cha: 2, eth: 3 }, v: [1, 1, 2, 0], like: { gen: 1, honest: 1 }, tx: 'formal', w: 'Hires crews that look like the world, and has the schedule to show it works.', o: 'Was a publicist first. Still knows everyone.', pals: ['David Oyelowo'] },
  'Damien Chazelle': { g: ['Musical', 'Drama', 'Period'], t: ['Perfectionist', 'Anxious', 'Prodigy'], m: { vis: 3, com: -1 }, v: [0, 2, 2, 0], like: { amb: 1, bold: .5 }, tx: 'long', w: 'Every film is about the cost of being great at something. Drums optional.', o: 'Was a jazz drummer. Got out. Still not over it.', pals: ['Ryan Gosling', 'Justin Hurwitz'] },
  'Barry Jenkins': { g: ['Drama', 'Romance'], t: ['Sensitive', 'Kind', 'Cinephile'], m: { tas: 3, col: 2 }, v: [2, 0, 1, 0], like: { gen: 1, honest: .5 }, tx: 'long', w: 'Faces straight to camera, colours like memory.', o: 'Writes long, loving threads about other people\'s films.', pals: [] },
  'Ryan Coogler': { g: ['Drama', 'Superhero', 'Action'], t: ['Humble', 'Loyal', 'Workhorse'], m: { col: 3, eth: 2 }, v: [2, 1, 1, 0], like: { loyal: 1.2, gen: .5 }, tx: 'formal', w: 'Brings the same crew and the same lead from film to film.', o: 'Played college football. Still trains like it.', pals: ['Michael B. Jordan'] },
  'Jon Favreau': { g: ['Comedy', 'Superhero', 'Sci-fi', 'Animation'], t: ['Gregarious', 'Commercial', 'Curious'], m: { cha: 3, col: 2 }, v: [2, 0, 0, 1], like: { gen: .5, amb: .5 }, tx: 'emoji', w: 'Improvises in the room, then builds a game engine to shoot in.', o: 'Cooks. Really cooks. Made a whole film about it.', pals: ['Robert Downey Jr.', 'Vince Vaughn'] },
  'James Gunn': { g: ['Superhero', 'Comedy', 'Horror', 'Action'], t: ['Witty', 'Loyal', 'Showboat'], m: { cha: 2 }, v: [1, 1, 0, 2], like: { loyal: 1, bold: .5 }, tx: 'emoji', w: 'Puts his brother in everything and his dog in the posters.', o: 'Posts constantly. Loves his pets more than his reviews.', pals: [] },
  'Patty Jenkins': { g: ['Superhero', 'Drama', 'Action'], t: ['Ambitious', 'Optimist'], m: { cha: 2 }, v: [1, 1, 1, 1], like: { amb: 1 }, tx: 'emoji', w: 'Sincere about heroes, at a time when nobody else was.', o: 'An air force kid. Talks like one.', pals: [] },
  'Judd Apatow': { g: ['Comedy', 'Romance'], t: ['Gregarious', 'Hustler', 'Loyal'], m: { cha: 2 }, v: [1, 0, 0, 2], like: { loyal: 1, gen: .5 }, tx: 'long', w: 'Shoots a million feet of improv and finds the film in the cut. Three hours long, at first.', o: 'Collects comedy records, interviews his heroes, casts his family.', pals: ['Seth Rogen', 'Paul Rudd', 'Steve Carell', 'Leslie Mann'] },
  'Todd Phillips': { g: ['Comedy', 'Crime', 'Drama'], t: ['Cynical', 'Commercial'], m: { cha: 1 }, v: [0, 1, 1, 1], like: { bold: 1 }, tx: 'lower', w: 'Made the biggest comedies of his day, then decided comedy was over.', o: 'Keeps it to himself.', pals: ['Bradley Cooper'] },
  'Adam McKay': { g: ['Comedy', 'Drama'], t: ['Witty', 'Curious', 'Volatile'], m: { cha: 2 }, v: [1, 1, 0, 2], like: { honest: 1, bold: .5 }, tx: 'caps', w: 'Twenty alternative jokes per line, then a lecture on the economy.', o: 'Tweets about the end of the world between takes.', pals: ['Will Ferrell', 'John C. Reilly'] },
  'Robert Zemeckis': { g: ['Sci-fi', 'Comedy', 'Drama', 'Animation'], t: ['Visionary', 'Commercial'], m: { vis: 3 }, v: [1, 0, 2, 1], like: { amb: .5 }, tx: 'formal', w: 'Always chasing the next camera trick.', o: 'Flies his own planes.', pals: ['Tom Hanks', 'Steven Spielberg'] },
  'Oliver Stone': { g: ['War', 'Drama', 'Crime'], t: ['Volatile', 'Reckless', 'Visionary'], m: { vis: 3, com: -2 }, v: [0, 2, 0, 0], like: { bold: 1.2 }, tx: 'caps', w: 'Every film is a fight, usually with history.', o: 'Has theories. Will share them.', pals: [] },
  'Kevin Smith': { g: ['Comedy'], t: ['Gregarious', 'Frugal', 'Hustler'], m: { cha: 3 }, v: [2, 0, -1, 2], like: { loyal: 1.2 }, tx: 'emoji', w: 'Made his first film on credit cards in the shop he worked at.', o: 'Talks for four hours to anyone who will listen. Hockey jerseys.', pals: [] },
  'Peter Jackson': { g: ['Fantasy', 'Horror', 'War'], t: ['Visionary', 'Workhorse', 'Humble'], m: { vis: 4, eth: 3 }, v: [2, 1, 1, 2], like: { loyal: 1 }, tx: 'long', w: 'Built a film industry in his back garden. Barefoot.', o: 'Restores old aeroplanes and war footage.', pals: ['Fran Walsh'] },
  'Bong Joon-ho': { g: ['Thriller', 'Sci-fi', 'Drama', 'Crime'], t: ['Witty', 'Auteur', 'Perfectionist'], m: { vis: 4, tas: 3 }, v: [1, 1, 2, 2], like: { honest: .5, bold: .5 }, tx: 'lower', w: 'Storyboards every frame, then cuts in camera. Nobody works overtime on his set.', o: 'Self-described film nerd. Brings a translator who becomes famous.', pals: ['Song Kang-ho'] },
  'Park Chan-wook': { g: ['Thriller', 'Crime', 'Romance'], t: ['Auteur', 'Calm', 'Perfectionist'], m: { vis: 4, com: 2 }, v: [1, 1, 2, 1], like: { bold: .5 }, tx: 'formal', w: 'Beautiful frames around very violent ideas.', o: 'Gentle, soft-spoken, takes photographs.', pals: [] },
  'Akira Kurosawa': { g: ['Period', 'Drama', 'Action', 'Crime'], t: ['Perfectionist', 'Difficult', 'Visionary'], m: { vis: 4, col: -1 }, v: [-1, 2, 2, 0], like: { amb: .5, honest: .5 }, tx: 'formal', w: 'Waits days for the right cloud. Paints every storyboard.', o: 'Paints. Eats well. Shouts.', pals: ['Toshiro Mifune'] },
  'Hayao Miyazaki': { g: ['Animation', 'Fantasy'], no: ['Superhero'], t: ['Perfectionist', 'Cynical', 'Workhorse'], m: { vis: 5, eth: 3 }, v: [0, 1, 2, 0], like: { honest: 1, gen: .5 }, tx: 'formal', w: 'Draws thousands of frames himself. Retires every few years, then doesn\'t.', o: 'Grumbles about the modern world, then plays with the children at the studio nursery.', pals: ['Joe Hisaishi'] },
  'Pedro Almodóvar': { g: ['Drama', 'Comedy', 'Romance'], t: ['Auteur', 'Gregarious', 'Loyal'], m: { tas: 4, cha: 2 }, v: [2, 1, 1, 2], like: { loyal: 1, bold: .5 }, tx: 'emoji', w: 'Red everywhere. Mothers everywhere. The same actors, for life.', o: 'Collects art, champions his actresses, gossips magnificently.', pals: ['Penélope Cruz', 'Antonio Banderas'] },
  'Ang Lee': { g: ['Drama', 'Martial arts', 'Romance', 'Period'], t: ['Humble', 'Calm', 'Curious'], m: { com: 3, col: 2 }, v: [2, 0, 1, 0], like: { gen: .5, honest: .5 }, tx: 'formal', w: 'Changes genre and country on every film, and gets it right.', o: 'Stayed home cooking for six years before anyone hired him.', pals: [] },
  'Wong Kar-wai': { g: ['Romance', 'Drama', 'Martial arts'], t: ['Auteur', 'Perfectionist', 'Spendthrift'], m: { vis: 4, tas: 4, eth: -1 }, v: [0, 0, -1, 1], like: { bold: .5 }, tx: 'terse', w: 'No script. Shoots for a year. Finds the film in the edit. Sunglasses, at night.', o: 'Nobody has seen his eyes.', pals: ['Tony Leung Chiu-wai', 'Maggie Cheung'] },
  'Satyajit Ray': { g: ['Drama', 'Period'], t: ['Bookish', 'Calm', 'Perfectionist'], m: { vis: 4, tas: 4 }, v: [1, -1, 2, 0], like: { honest: 1 }, tx: 'formal', w: 'Writes, scores, designs the posters and the titles himself.', o: 'Writes detective stories for children. Very tall. Very polite.', pals: [] },
  'Agnès Varda': { g: ['Documentary', 'Drama'], t: ['Curious', 'Kind', 'Optimist'], m: { vis: 3, cha: 2 }, v: [2, 0, 0, 2], like: { gen: 1, honest: .5 }, tx: 'emoji', w: 'A camera, a cat, and a two-tone haircut. Finds strangers more interesting than stars.', o: 'Loves potatoes, beaches and other people.', pals: [] },
  'Jean-Luc Godard': { g: ['Drama', 'Crime'], t: ['Auteur', 'Difficult', 'Cynical'], m: { vis: 4, col: -2 }, v: [-1, 1, 1, 1], like: { bold: 1.5 }, tx: 'terse', w: 'Breaks every rule, then breaks the new rules.', o: 'Doesn\'t show up to his own tributes.', pals: [] },
  'Lars von Trier': { g: ['Drama', 'Horror'], t: ['Auteur', 'Anxious', 'Difficult'], m: { vis: 3, com: -2 }, v: [-1, 2, 2, 1], like: { bold: 1.2 }, tx: 'long', w: 'Makes up rules for himself. Puts his actors through hell, on purpose.', o: 'Afraid of flying. Drives everywhere in a camper van.', pals: [] },
  'Werner Herzog': { g: ['Documentary', 'Drama', 'Period'], t: ['Reckless', 'Stubborn', 'Curious'], m: { vis: 3, com: 3 }, v: [0, 2, 1, 1], like: { bold: 1.5 }, tx: 'formal', w: 'Hauled a steamship over a mountain. Will do it again if needed.', o: 'Narrates his own life in that voice. Once ate his shoe on a bet.', pals: [] },
  'Alfonso Cuarón': { g: ['Sci-fi', 'Drama', 'Fantasy'], t: ['Visionary', 'Gregarious'], m: { vis: 4 }, v: [2, 1, 1, 1], like: { gen: .5, bold: .5 }, tx: 'emoji', w: 'Long takes that make crews weep with fear.', o: 'Calls his two best friends, both directors, every week.', pals: ['Guillermo del Toro', 'Alejandro González Iñárritu', 'Emmanuel Lubezki'] },
  'Alejandro González Iñárritu': { g: ['Drama', 'Period'], t: ['Perfectionist', 'Volatile', 'Visionary'], m: { vis: 4, col: -1 }, v: [0, 2, 2, 0], like: { amb: 1, bold: .5 }, tx: 'long', w: 'Shoots only at magic hour, in the snow, in order.', o: 'Was a radio DJ. Still talks like one.', pals: ['Alfonso Cuarón', 'Emmanuel Lubezki'] },
  'S. S. Rajamouli': { g: ['Action', 'Fantasy', 'Period'], t: ['Visionary', 'Showboat', 'Workhorse'], m: { vis: 4, eth: 3 }, v: [1, 2, 2, 1], like: { amb: 1, loyal: .5 }, tx: 'emoji', w: 'Everything bigger: the bridge, the tiger, the dance.', o: 'Family runs the crew. His father writes, his brother scores.', pals: [] },
  'Karan Johar': { g: ['Romance', 'Drama', 'Musical'], t: ['Gregarious', 'Commercial', 'Gossip'], m: { cha: 4 }, v: [2, 0, 0, 2], like: { loyal: .5, amb: .5 }, tx: 'emoji', w: 'Big families, big weddings, big tears.', o: 'Hosts the talk show where everyone spills.', pals: ['Shah Rukh Khan'] },
  // ---- actors ----
  'Tom Cruise': { g: ['Action', 'Sci-fi', 'Thriller'], no: ['Horror'], t: ['Disciplined', 'Workhorse', 'Showboat'], m: { eth: 4, com: 2, cha: 2 }, v: [1, 2, 2, 0], like: { amb: 1, bold: 1 }, tx: 'emoji', w: 'Does his own stunts: the plane, the cliff, the motorbike off the cliff. Runs in every film.', o: 'Sends everyone he\'s worked with a coconut cake at Christmas.', pals: ['Christopher McQuarrie'] },
  'Tom Hanks': { g: ['Drama', 'Comedy', 'War'], t: ['Beloved', 'Humble', 'Witty'], m: { cha: 3, col: 3 }, v: [2, 0, 0, 1], like: { gen: 1, honest: .5 }, tx: 'formal', w: 'Knows the name of every grip. America\'s dad on set.', o: 'Collects old typewriters and sends typed letters to strangers.', pals: ['Steven Spielberg', 'Robert Zemeckis', 'Ron Howard'] },
  'Meryl Streep': { g: ['Drama', 'Comedy', 'Period'], t: ['Method', 'Humble', 'Beloved'], m: { tas: 3, col: 2 }, v: [2, 0, 1, 1], like: { honest: 1, gen: .5 }, tx: 'formal', w: 'Arrives with a new accent and leaves with another nomination.', o: 'Knits on set. Refuses to call herself the best.', pals: [] },
  'Denzel Washington': { g: ['Thriller', 'Drama', 'Action', 'Crime'], t: ['Disciplined', 'Charming', 'Stubborn'], m: { cha: 4, com: 3 }, v: [1, 1, 2, 0], like: { honest: 1, loyal: .5 }, tx: 'terse', w: 'Prepares like a boxer. Tells young actors to read more.', o: 'Church on Sunday, theatre in between films.', pals: ['Spike Lee', 'Antoine Fuqua'] },
  'Leonardo DiCaprio': { g: ['Drama', 'Crime', 'Period', 'Thriller'], t: ['Ambitious', 'Discreet', 'Perfectionist'], m: { tas: 3 }, v: [1, 1, 1, 0], like: { amb: 1 }, tx: 'lower', w: 'Picks only auteurs. Suffers on camera for years until the statue arrives.', o: 'Yachts, climate summits, and the same group of friends since the nineties.', pals: ['Martin Scorsese'] },
  'Brad Pitt': { g: ['Drama', 'Action', 'Crime', 'War'], t: ['Calm', 'Photogenic', 'Curious'], m: { cha: 3, com: 2 }, v: [1, 0, 0, 1], like: { honest: .5, gen: .5 }, tx: 'lower', w: 'Eats in every scene. Produces the films nobody else will.', o: 'Makes furniture and sculpture. Grows olives in France.', pals: ['George Clooney', 'David Fincher', 'Quentin Tarantino'] },
  'George Clooney': { g: ['Drama', 'Comedy', 'Crime', 'Thriller'], t: ['Charming', 'Witty', 'Loyal'], m: { cha: 5 }, v: [2, 0, 0, 2], like: { loyal: 1, gen: .5 }, tx: 'emoji', w: 'Pulls elaborate pranks on co-stars. The best host of any set.', o: 'Once gave fourteen friends a million dollars each. Makes tequila.', pals: ['Brad Pitt', 'Steven Soderbergh', 'Matt Damon'] },
  'Keanu Reeves': { g: ['Action', 'Sci-fi', 'Martial arts', 'Thriller'], t: ['Kind', 'Humble', 'Disciplined'], m: { col: 4, eth: 3 }, v: [2, 0, 1, 0], like: { gen: 1.5 }, tx: 'formal', w: 'Trains for months, gives his stunt team gifts, gives up his pay for the crew.', o: 'Rides motorbikes, reads on the subway, gives up his seat.', pals: [] },
  'Nicolas Cage': { g: ['Action', 'Thriller', 'Horror', 'Comedy'], t: ['Volatile', 'Spendthrift', 'Curious'], m: { cha: 2, com: -2 }, v: [1, 2, -2, 2], like: { bold: 1.5 }, tx: 'caps', w: 'Calls his style "nouveau shamanic". Says yes to almost anything.', o: 'Once owned a castle, a dinosaur skull and a pyramid tomb. Has a pet crow.', pals: [] },
  'Jim Carrey': { g: ['Comedy', 'Drama', 'Fantasy'], t: ['Volatile', 'Method', 'Sensitive'], m: { cha: 3, com: -1 }, v: [1, 2, -1, 2], like: { bold: 1 }, tx: 'caps', w: 'His face is a special effect. Stays in character between takes, for months.', o: 'Paints enormous canvases and thinks hard about the self.', pals: [] },
  'Robert De Niro': { g: ['Crime', 'Drama', 'Comedy'], t: ['Method', 'Discreet', 'Stubborn'], m: { com: 3, cha: -1 }, v: [0, 2, 1, 0], like: { loyal: 1, honest: .5 }, tx: 'terse', w: 'Gains the weight, drives the cab, learns the saxophone. Then mumbles in interviews.', o: 'Restaurants and a film festival in his old neighbourhood.', pals: ['Martin Scorsese', 'Joe Pesci'] },
  'Al Pacino': { g: ['Crime', 'Drama'], t: ['Method', 'Volatile'], m: { cha: 2 }, v: [1, 2, -1, 1], like: { bold: 1 }, tx: 'caps', w: 'Quiet, quiet, quiet, then a hurricane.', o: 'Theatre, always theatre.', pals: ['Robert De Niro'] },
  'Jack Nicholson': { g: ['Drama', 'Comedy', 'Thriller'], t: ['Charming', 'Reckless', 'Gregarious'], m: { cha: 4 }, v: [1, 2, -2, 2], like: { bold: 1 }, tx: 'emoji', w: 'Raised eyebrows as a performance style.', o: 'Courtside for every home game, in sunglasses.', pals: [] },
  'Harrison Ford': { g: ['Action', 'Sci-fi', 'Thriller'], t: ['Stubborn', 'Cynical', 'Disciplined'], m: { com: 3, cha: 1 }, v: [0, 0, 1, 1], like: { honest: 1.2 }, tx: 'terse', w: 'Gruff, practical, cuts his own lines. Was a carpenter first.', o: 'Flies his own planes and helicopters. Hates talk shows.', pals: ['George Lucas', 'Steven Spielberg'] },
  'Morgan Freeman': { g: ['Drama', 'Thriller', 'Crime'], t: ['Calm', 'Charming'], m: { com: 4, cha: 3 }, v: [1, -1, 1, 1], like: { honest: 1 }, tx: 'formal', w: 'Doesn\'t rehearse, doesn\'t need to. The voice does it.', o: 'Keeps bees. Flies planes. Narrates the universe.', pals: ['Clint Eastwood'] },
  'Samuel L. Jackson': { g: ['Action', 'Crime', 'Thriller', 'Superhero'], t: ['Workhorse', 'Gregarious', 'Showboat'], m: { cha: 3, eth: 3 }, v: [1, 2, 0, 2], like: { bold: 1 }, tx: 'caps', w: 'In more films than anyone else in history. Writes golf into his contracts.', o: 'Golf. Every day off. Every one.', pals: ['Quentin Tarantino', 'Spike Lee'] },
  'Will Smith': { g: ['Action', 'Sci-fi', 'Comedy', 'Drama'], t: ['Charming', 'Ambitious', 'Commercial'], m: { cha: 4, eth: 3 }, v: [2, 1, 1, 1], like: { amb: 1.2 }, tx: 'emoji', w: 'Studied what the biggest hits had in common, then made them.', o: 'Runs on a treadmill until the other guy falls off.', pals: [] },
  'Dwayne Johnson': { g: ['Action', 'Comedy', 'Fantasy'], t: ['Workhorse', 'Charming', 'Disciplined'], m: { eth: 5, cha: 4 }, v: [2, 1, 1, 1], like: { amb: 1, gen: .5 }, tx: 'emoji', w: 'Up at four, gym, then twelve hours on set. Never loses a fight on screen.', o: 'Cheat meals photographed for millions. Tequila brand.', pals: [] },
  'Arnold Schwarzenegger': { g: ['Action', 'Sci-fi', 'Comedy'], t: ['Ambitious', 'Showboat', 'Disciplined'], m: { eth: 4, cha: 3 }, v: [1, 1, 2, 1], like: { amb: 1.5 }, tx: 'emoji', w: 'Learned his lines phonetically and made it an asset.', o: 'Cigars, a pet donkey, motivational speeches nobody asked for.', pals: ['James Cameron'] },
  'Sylvester Stallone': { g: ['Action', 'Drama'], t: ['Hustler', 'Stubborn', 'Workhorse'], m: { eth: 4 }, v: [1, 2, 1, 0], like: { amb: 1, loyal: .5 }, tx: 'caps', w: 'Wrote his own break in three days and refused to sell it unless he starred.', o: 'Paints. Still trains. Keeps turtles from 1976.', pals: [] },
  'Julia Roberts': { g: ['Romance', 'Comedy', 'Drama'], t: ['Charming', 'Photogenic'], m: { cha: 4 }, v: [2, 0, 0, 2], like: { gen: .5, loyal: .5 }, tx: 'emoji', w: 'That laugh closes a deal faster than any agent.', o: 'Lives on a farm, away from it all.', pals: ['George Clooney'] },
  'Sandra Bullock': { g: ['Comedy', 'Romance', 'Thriller', 'Action'], t: ['Witty', 'Kind', 'Workhorse'], m: { cha: 3, col: 3 }, v: [2, 0, 0, 2], like: { gen: 1, honest: .5 }, tx: 'emoji', w: 'Makes fun of herself first, so nobody else has to.', o: 'Runs a bakery and a restaurant in Texas.', pals: [] },
  'Cate Blanchett': { g: ['Drama', 'Period', 'Fantasy'], t: ['Method', 'Witty'], m: { tas: 4, com: 3 }, v: [1, 1, 2, 1], like: { bold: .5, honest: .5 }, tx: 'formal', w: 'Can play anyone, including men, including two of them in one film.', o: 'Ran a theatre company with her husband. Gardens.', pals: [] },
  'Nicole Kidman': { g: ['Drama', 'Thriller', 'Horror'], t: ['Workhorse', 'Ambitious', 'Discreet'], m: { eth: 4 }, v: [1, 1, 1, 0], like: { bold: 1 }, tx: 'formal', w: 'Works with every new director worth working with, as soon as they appear.', o: 'Lives quietly in Nashville. Has a cinema advert people quote.', pals: [] },
  'Scarlett Johansson': { g: ['Superhero', 'Sci-fi', 'Drama', 'Action'], t: ['Witty', 'Ambitious'], m: { cha: 3 }, v: [1, 1, 1, 1], like: { amb: .5 }, tx: 'lower', w: 'Indie darling turned franchise lead, without losing either.', o: 'Has a skincare brand. Married a comedian.', pals: [] },
  'Jennifer Lawrence': { g: ['Drama', 'Action', 'Comedy', 'Sci-fi'], t: ['Witty', 'Reckless', 'Gregarious'], m: { cha: 3 }, v: [2, 1, -1, 2], like: { honest: 1 }, tx: 'emoji', w: 'Trips on the way to the stage. Wins anyway.', o: 'Reality TV, junk food, no filter.', pals: ['Bradley Cooper'] },
  'Margot Robbie': { g: ['Comedy', 'Drama', 'Crime'], t: ['Ambitious', 'Hustler', 'Gregarious'], m: { cha: 3, eth: 2 }, v: [2, 1, 1, 1], like: { amb: 1, gen: .5 }, tx: 'emoji', w: 'Produces her own films with her friends, and they keep making money.', o: 'Lived in a house with her mates. Plays ice hockey.', pals: [] },
  'Timothée Chalamet': { g: ['Drama', 'Sci-fi', 'Romance', 'Musical'], t: ['Ambitious', 'Photogenic', 'Prodigy'], m: { cha: 3 }, v: [1, 1, 1, 1], like: { amb: 1, bold: .5 }, tx: 'lower', w: 'Picks auteurs. Learns the guitar for real if the part needs it.', o: 'Raps under a pseudonym. Basketball games.', pals: [] },
  'Zendaya': { g: ['Drama', 'Sci-fi', 'Romance'], t: ['Disciplined', 'Discreet'], m: { com: 3 }, v: [1, 0, 2, 0], like: { honest: 1 }, tx: 'lower', w: 'Child star who stayed sane. The red carpet looks are their own art form.', o: 'Protects her privacy with a stylist and a stare.', pals: [] },
  'Ryan Gosling': { g: ['Drama', 'Romance', 'Thriller', 'Comedy'], t: ['Shy', 'Witty', 'Curious'], m: { com: 2 }, v: [1, -1, 1, 2], like: { honest: .5, gen: .5 }, tx: 'lower', w: 'Says almost nothing, which is the performance. Learns the piano for real.', o: 'Has a band about ghosts. Restores old motorbikes.', pals: ['Damien Chazelle'] },
  'Ryan Reynolds': { g: ['Comedy', 'Action', 'Superhero'], t: ['Witty', 'Hustler', 'Commercial'], m: { cha: 4 }, v: [1, 0, 1, 2], like: { bold: .5, amb: .5 }, tx: 'emoji', w: 'Rewrites the jokes on the day. Then writes the advert for it himself.', o: 'Buys a gin company, a phone company and a football club. Trolls his best friend.', pals: [] },
  'Matt Damon': { g: ['Drama', 'Action', 'Thriller', 'Sci-fi'], t: ['Humble', 'Loyal', 'Workhorse'], m: { col: 3 }, v: [2, 0, 1, 1], like: { loyal: 1.2 }, tx: 'lower', w: 'The everyman who learns to fight, fly and grow potatoes on Mars.', o: 'Still best friends with the guy he wrote his first film with.', pals: ['Ben Affleck', 'George Clooney', 'Steven Soderbergh'] },
  'Ben Affleck': { g: ['Drama', 'Thriller', 'Crime', 'Superhero'], t: ['Ambitious', 'Sensitive'], m: { vis: 2 }, v: [1, 1, 0, 1], like: { loyal: 1 }, tx: 'lower', w: 'A better director than anyone expected. A better actor, too.', o: 'Iced coffee, very large, looking very tired, photographed.', pals: ['Matt Damon'] },
  'Joaquin Phoenix': { g: ['Drama', 'Crime', 'Thriller'], t: ['Method', 'Anxious', 'Difficult'], m: { tas: 3, com: -2 }, v: [0, 2, -1, 1], like: { honest: 1.5 }, tx: 'terse', w: 'Hates being watched while acting, which is the job.', o: 'Vegan activist. Once pretended to quit to become a rapper for a year.', pals: ['Paul Thomas Anderson'] },
  'Daniel Day-Lewis': { g: ['Drama', 'Period'], t: ['Method', 'Perfectionist', 'Discreet'], m: { tas: 4, eth: 3, col: -1 }, v: [0, 2, 2, -1], like: { honest: 1 }, tx: 'formal', w: 'Stays in character for the whole shoot. Builds a canoe if the character would.', o: 'Retires to make shoes. Then comes back. Then retires again.', pals: ['Paul Thomas Anderson'] },
  'Johnny Depp': { g: ['Fantasy', 'Comedy', 'Period', 'Crime'], t: ['Shy', 'Spendthrift', 'Loyal'], m: { cha: 2 }, v: [1, 0, -1, 2], like: { loyal: 1, bold: .5 }, tx: 'lower', w: 'Builds characters from hats, teeth and rock stars.', o: 'Plays guitar in a band with old rock stars. Owns an island.', pals: ['Tim Burton'] },
  'Bill Murray': { g: ['Comedy', 'Drama'], t: ['Witty', 'Reckless', 'Gregarious'], m: { cha: 4, eth: -1 }, v: [1, -1, -2, 2], like: { bold: .5, gen: .5 }, tx: 'terse', w: 'No agent: you leave a message on a phone line and hope. Turns up. Mostly.', o: 'Crashes strangers\' parties and karaoke nights, then leaves.', pals: ['Wes Anderson', 'Sofia Coppola'] },
  'Keira Knightley': { g: ['Period', 'Romance', 'Drama'], t: ['Witty', 'Disciplined'], m: { com: 2 }, v: [1, 0, 1, 1], like: { honest: 1 }, tx: 'lower', w: 'A corset in every film. Refuses to shoot the sex scenes with men directing.', o: 'Lives in London, takes the tube, drinks tea.', pals: [] },
  'Emma Stone': { g: ['Comedy', 'Drama', 'Musical'], t: ['Witty', 'Anxious', 'Kind'], m: { cha: 3 }, v: [2, 0, 0, 2], like: { gen: .5, honest: .5 }, tx: 'emoji', w: 'Says yes to the strangest director in the room. Usually wins.', o: 'Talks openly about anxiety. Loves a good karaoke night.', pals: ['Ryan Gosling'] },
  'Viola Davis': { g: ['Drama', 'Thriller'], t: ['Method', 'Disciplined', 'Ambitious'], m: { com: 3, tas: 3 }, v: [1, 2, 2, 0], like: { honest: 1.2 }, tx: 'formal', w: 'Every close-up is a fight for the character\'s dignity.', o: 'Grew up with nothing. Says so. Built her own company.', pals: [] },
  'Michelle Yeoh': { g: ['Martial arts', 'Action', 'Sci-fi', 'Drama'], t: ['Disciplined', 'Kind', 'Workhorse'], m: { eth: 4, com: 3 }, v: [2, 1, 2, 0], like: { loyal: .5, gen: .5 }, tx: 'formal', w: 'Was a ballet dancer, then did her own stunts in heels.', o: 'Mentors every young actor who asks.', pals: [] },
  'Jackie Chan': { g: ['Martial arts', 'Action', 'Comedy'], t: ['Workhorse', 'Reckless', 'Beloved'], m: { eth: 5, cha: 3 }, v: [2, 1, 1, 2], like: { loyal: 1, gen: .5 }, tx: 'emoji', w: 'Has broken nearly every bone. Pays his stunt team\'s hospital bills himself.', o: 'Sings. Badly. Constantly.', pals: [] },
  'Shah Rukh Khan': { g: ['Romance', 'Drama', 'Action', 'Musical'], t: ['Charming', 'Witty', 'Workhorse'], m: { cha: 5 }, v: [2, 1, 1, 2], like: { loyal: 1, amb: .5 }, tx: 'emoji', w: 'Arms wide open. Works through injuries. Remembers every crew member\'s child.', o: 'Thousands wait outside his house on his birthday. He waves.', pals: ['Karan Johar'] },
  'Amitabh Bachchan': { g: ['Action', 'Drama', 'Crime'], t: ['Disciplined', 'Workhorse'], m: { eth: 4, cha: 3 }, v: [1, 1, 2, 0], like: { loyal: 1, honest: .5 }, tx: 'formal', w: 'First on set, every day, for fifty years.', o: 'Blogs every night. Has never missed one.', pals: [] },
  'Song Kang-ho': { g: ['Drama', 'Thriller', 'Crime', 'Comedy'], t: ['Humble', 'Calm'], m: { com: 3 }, v: [2, 0, 0, 1], like: { loyal: 1 }, tx: 'formal', w: 'The everyman of a whole national cinema.', o: 'Keeps a very low profile between films.', pals: ['Bong Joon-ho'] },
  'Toshiro Mifune': { g: ['Period', 'Action', 'Drama'], t: ['Volatile', 'Charming'], m: { cha: 3 }, v: [1, 2, -1, 1], like: { bold: 1, loyal: .5 }, tx: 'terse', w: 'Moves like an animal on camera. Takes no stunt double.', o: 'Drinks hard, drives fast, apologises the next morning.', pals: ['Akira Kurosawa'] },
  'Michael Caine': { g: ['Thriller', 'Crime', 'Drama', 'Comedy'], t: ['Workhorse', 'Witty', 'Frugal'], m: { cha: 3, eth: 3 }, v: [2, 0, 0, 2], like: { honest: 1 }, tx: 'formal', w: 'Never turns a job down. Never blinks on camera, on purpose.', o: 'Cooks, gardens, tells the same stories brilliantly.', pals: ['Christopher Nolan'] },
  'Judi Dench': { g: ['Drama', 'Period', 'Comedy'], t: ['Witty', 'Beloved'], m: { cha: 3, tas: 3 }, v: [2, 0, 0, 2], like: { gen: .5, honest: .5 }, tx: 'formal', w: 'Refuses to read the script in advance. Learns it on the day.', o: 'Embroiders rude words onto cushions.', pals: [] },
  'Anthony Hopkins': { g: ['Drama', 'Thriller', 'Period'], t: ['Disciplined', 'Calm'], m: { com: 4 }, v: [1, 0, 2, 1], like: { honest: 1 }, tx: 'emoji', w: 'Reads his lines two hundred times. Arrives knowing everyone else\'s too.', o: 'Plays piano, paints, dances on social media in his eighties.', pals: [] },
  'Helen Mirren': { g: ['Drama', 'Period', 'Action'], t: ['Witty', 'Gregarious'], m: { cha: 3 }, v: [2, 0, 0, 2], like: { bold: 1 }, tx: 'emoji', w: 'Plays queens. Then fires machine guns.', o: 'Swears beautifully. Says what she thinks about everything.', pals: [] },
  'Tilda Swinton': { g: ['Drama', 'Fantasy', 'Horror'], t: ['Curious', 'Auteur'], m: { tas: 4 }, v: [1, 0, 1, 2], like: { bold: 1 }, tx: 'formal', w: 'Unrecognisable from film to film, on purpose.', o: 'Once slept in a glass box in a gallery. Raises dogs in the Highlands.', pals: ['Wes Anderson', 'Jim Jarmusch'] },
  'Adam Sandler': { g: ['Comedy'], t: ['Loyal', 'Lazy', 'Commercial'], m: { cha: 2, eth: -1 }, v: [2, -1, -1, 2], like: { loyal: 1.5 }, tx: 'lower', w: 'Shoots where his friends want a holiday, with his friends. Every so often, a masterpiece.', o: 'Basketball shorts, everywhere, always. Pick-up games with strangers.', pals: ['Rob Schneider', 'David Spade'] },
  'Will Ferrell': { g: ['Comedy'], t: ['Gregarious', 'Witty', 'Kind'], m: { cha: 3 }, v: [2, 0, -1, 2], like: { gen: .5, bold: .5 }, tx: 'emoji', w: 'Commits completely to the stupidest idea in the room.', o: 'Runs marathons. Plays the cowbell when asked.', pals: ['Adam McKay', 'John C. Reilly'] },
  'Steve Carell': { g: ['Comedy', 'Drama'], t: ['Kind', 'Humble'], m: { col: 3 }, v: [2, -1, 0, 2], like: { gen: 1 }, tx: 'formal', w: 'The kindest person in the funniest room.', o: 'Owned a general store in his home town.', pals: ['Judd Apatow'] },
  'Seth Rogen': { g: ['Comedy', 'Animation'], t: ['Gregarious', 'Loyal'], m: { cha: 2 }, v: [2, -1, -1, 2], like: { loyal: 1.2 }, tx: 'lower', w: 'Makes films with the friend he wrote them with at thirteen.', o: 'Makes pottery. Very good pottery. And laughs that laugh.', pals: ['Judd Apatow', 'Paul Rudd', 'Jonah Hill'] },
  'Paul Rudd': { g: ['Comedy', 'Superhero', 'Romance'], t: ['Charming', 'Kind'], m: { cha: 3 }, v: [2, -1, 0, 2], like: { gen: 1 }, tx: 'emoji', w: 'Shows the same clip on every talk show for twenty years.', o: 'Has not aged. Nobody knows why.', pals: ['Judd Apatow'] },
  'Eddie Murphy': { g: ['Comedy', 'Action', 'Animation'], t: ['Charming', 'Showboat', 'Discreet'], m: { cha: 5 }, v: [1, 1, 0, 2], like: { bold: .5 }, tx: 'terse', w: 'Plays five characters in one film. All of them under prosthetics.', o: 'Doesn\'t drink, doesn\'t party, lives behind high walls.', pals: [] },
  'Robert Downey Jr.': { g: ['Superhero', 'Comedy', 'Drama'], t: ['Witty', 'Charming', 'Showboat'], m: { cha: 5 }, v: [2, 1, -1, 2], like: { bold: .5, honest: .5 }, tx: 'emoji', w: 'Improvises half his lines. Hides snacks all over the set.', o: 'Martial arts, meditation, and a second act everyone roots for.', pals: ['Jon Favreau'] },
  'Chris Evans': { g: ['Superhero', 'Action', 'Comedy'], t: ['Kind', 'Anxious'], m: { cha: 3 }, v: [2, 0, 0, 1], like: { gen: 1, loyal: .5 }, tx: 'emoji', w: 'Almost turned down the shield because of nerves.', o: 'His dog is more famous than most actors.', pals: [] },
  'Pedro Pascal': { g: ['Drama', 'Action', 'Sci-fi'], t: ['Charming', 'Kind', 'Gregarious'], m: { cha: 4 }, v: [2, 0, -1, 2], like: { gen: 1 }, tx: 'emoji', w: 'Twenty years of guest spots, then everywhere at once.', o: 'Everyone\'s favourite internet dad. Hugs on red carpets.', pals: [] },
  'Lupita Nyong’o': { g: ['Drama', 'Horror', 'Superhero'], t: ['Disciplined', 'Bookish'], m: { tas: 3 }, v: [2, 0, 1, 0], like: { honest: 1 }, tx: 'formal', w: 'Yale-trained precision, effortless on screen.', o: 'Writes children\'s books. Speaks five languages.', pals: [] },
  'Jessica Chastain': { g: ['Drama', 'Thriller', 'Sci-fi'], t: ['Ambitious', 'Workhorse'], m: { eth: 3 }, v: [1, 1, 1, 0], like: { honest: 1, gen: .5 }, tx: 'formal', w: 'Insists her co-stars are paid fairly. Usually wins.', o: 'Vegan. Rescue dogs.', pals: [] },
  'Kristen Stewart': { g: ['Drama', 'Thriller', 'Romance'], t: ['Shy', 'Cynical'], m: { tas: 3, cha: -1 }, v: [0, 1, -1, 1], like: { honest: 1.2 }, tx: 'lower', w: 'Went from the biggest franchise in the world to the smallest French films. On purpose.', o: 'Skateboards, swears, writes poetry.', pals: [] },
  'Jack Black': { g: ['Comedy', 'Musical', 'Animation'], t: ['Gregarious', 'Showboat'], m: { cha: 3 }, v: [2, 1, -1, 2], like: { bold: 1 }, tx: 'caps', w: 'Rocks out in every film, even the ones without music.', o: 'Plays video games on the internet with his sons.', pals: [] },
  'Owen Wilson': { g: ['Comedy', 'Drama'], t: ['Calm', 'Charming'], m: { cha: 3 }, v: [2, -2, -1, 2], like: { loyal: 1 }, tx: 'lower', w: 'Wow.', o: 'Wow.', pals: ['Wes Anderson', 'Ben Stiller'] },
  'Ben Stiller': { g: ['Comedy'], t: ['Anxious', 'Perfectionist'], m: { vis: 2 }, v: [0, 1, 2, 1], like: { honest: .5, amb: .5 }, tx: 'long', w: 'Plays the man everything goes wrong for. Directs the hell out of it.', o: 'Famously intense about the funny stuff.', pals: ['Owen Wilson'] },
  'Matthew McConaughey': { g: ['Drama', 'Romance', 'Comedy', 'Sci-fi'], t: ['Charming', 'Optimist'], m: { cha: 4 }, v: [2, 0, -1, 2], like: { bold: .5, gen: .5 }, tx: 'emoji', w: 'Quit romantic comedies for two years to be taken seriously. It worked.', o: 'Bongos. Shirt optional. Teaches at his old university.', pals: ['Richard Linklater'] },
  'Hugh Jackman': { g: ['Musical', 'Superhero', 'Action', 'Drama'], t: ['Kind', 'Workhorse', 'Disciplined'], m: { eth: 4, col: 3 }, v: [2, 1, 1, 1], like: { gen: 1 }, tx: 'emoji', w: 'The nicest man in show business, with claws.', o: 'Has a fake feud with a fellow actor that the whole world enjoys.', pals: [] },
  'Charlize Theron': { g: ['Action', 'Drama', 'Thriller'], t: ['Stubborn', 'Witty'], m: { com: 3 }, v: [1, 1, 1, 1], like: { bold: 1, honest: .5 }, tx: 'terse', w: 'Shaves her head, gains weight, breaks her ribs. Produces the film too.', o: 'Swears at award shows, tells the truth about getting older.', pals: [] },
  'Angelina Jolie': { g: ['Action', 'Drama', 'Fantasy'], t: ['Ambitious', 'Discreet'], m: { cha: 3 }, v: [1, 1, 1, 0], like: { gen: 1 }, tx: 'formal', w: 'Does her own action, then directs war dramas.', o: 'Goes to refugee camps. Keeps her children close.', pals: [] },
  'Jodie Foster': { g: ['Drama', 'Thriller'], t: ['Bookish', 'Discreet', 'Disciplined'], m: { tas: 3, com: 3 }, v: [1, 0, 2, 0], like: { honest: 1 }, tx: 'formal', w: 'Has been working since she was three. Speaks French on set.', o: 'Very private. Very clever.', pals: [] },
  'Dolly Parton': { g: ['Comedy', 'Musical'], t: ['Beloved', 'Witty', 'Kind'], m: { cha: 5 }, v: [2, 0, 1, 2], like: { gen: 1.5 }, tx: 'emoji', w: '"It costs a lot of money to look this cheap."', o: 'Sends a free book every month to millions of children.', pals: [] },
  'Bruce Willis': { g: ['Action', 'Thriller', 'Comedy'], t: ['Witty', 'Cynical'], m: { cha: 3 }, v: [1, 0, 0, 2], like: { bold: .5 }, tx: 'terse', w: 'The smirk does the acting.', o: 'Plays harmonica in a band.', pals: [] },
  'Daniel Craig': { g: ['Action', 'Thriller', 'Drama'], t: ['Cynical', 'Disciplined'], m: { com: 3 }, v: [0, 1, 1, 1], like: { honest: 1 }, tx: 'terse', w: 'Said he would rather slash his wrists than do another one. Did another one.', o: 'Doesn\'t use social media. Dances, apparently, for vodka adverts.', pals: [] },
  'Emma Thompson': { g: ['Drama', 'Comedy', 'Period'], t: ['Witty', 'Bookish', 'Gregarious'], m: { tas: 3, cha: 3 }, v: [2, 0, 0, 2], like: { honest: 1, gen: .5 }, tx: 'emoji', w: 'Writes the adaptation, then stars in it.', o: 'Swears a great deal, campaigns a great deal, and is always very funny.', pals: [] },
  'Idris Elba': { g: ['Action', 'Thriller', 'Crime', 'Drama'], t: ['Charming', 'Hustler'], m: { cha: 4 }, v: [1, 1, 1, 1], like: { amb: 1 }, tx: 'lower', w: 'Grew up in east London, worked nights, now everyone\'s pick for the next spy.', o: 'DJs under his own name. Kickboxes.', pals: [] },
  'Cillian Murphy': { g: ['Drama', 'Thriller', 'War'], t: ['Shy', 'Discreet', 'Disciplined'], m: { com: 3 }, v: [1, 0, 1, 0], like: { honest: 1 }, tx: 'formal', w: 'Those eyes do the work. Says yes when a certain director calls.', o: 'Lives in Ireland. Listens to music. Says no to talk shows.', pals: ['Christopher Nolan'] },
  'Florence Pugh': { g: ['Drama', 'Horror', 'Period'], t: ['Witty', 'Gregarious'], m: { cha: 3 }, v: [2, 1, -1, 2], like: { honest: 1.2 }, tx: 'emoji', w: 'Cries better than anyone. Laughs louder.', o: 'Cooks on the internet with a glass of wine.', pals: [] },
  'Saoirse Ronan': { g: ['Drama', 'Period', 'Romance'], t: ['Disciplined', 'Witty'], m: { tas: 3 }, v: [1, 0, 1, 1], like: { honest: 1 }, tx: 'lower', w: 'Has been nominated since she was thirteen. Corrects your pronunciation of her name.', o: 'Goes home to Ireland between films.', pals: ['Greta Gerwig'] },
  'Adam Driver': { g: ['Drama', 'Sci-fi', 'Romance'], t: ['Method', 'Volatile', 'Disciplined'], m: { eth: 3, com: -1 }, v: [0, 2, 1, 0], like: { honest: 1 }, tx: 'terse', w: 'Was a marine. Walks out if you play his own scenes back to him.', o: 'Runs a theatre company for soldiers.', pals: [] },
  'Austin Butler': { g: ['Drama', 'Musical', 'Sci-fi'], t: ['Method', 'Anxious'], m: { eth: 3 }, v: [1, 2, 1, 0], like: { amb: 1 }, tx: 'formal', w: 'Kept the accent long after the shoot.', o: 'Says "kinda" a lot.', pals: [] },
  'Zoe Saldaña': { g: ['Sci-fi', 'Action', 'Superhero'], t: ['Workhorse'], m: { eth: 3 }, v: [1, 1, 1, 1], like: { amb: .5 }, tx: 'emoji', w: 'Blue, green, or both. In four of the biggest films ever made.', o: 'Raises three boys and teaches them to dance.', pals: [] },
  'Michael B. Jordan': { g: ['Drama', 'Action', 'Superhero'], t: ['Disciplined', 'Loyal'], m: { eth: 4 }, v: [2, 1, 1, 0], like: { loyal: 1 }, tx: 'emoji', w: 'Trains like a pro athlete for every part.', o: 'Loves anime. Has a ramen brand.', pals: ['Ryan Coogler'] },
  'Awkwafina': { g: ['Comedy', 'Drama'], t: ['Witty', 'Gregarious'], m: { cha: 3 }, v: [2, 0, -1, 2], like: { honest: .5, gen: .5 }, tx: 'emoji', w: 'Rapper turned dramatic lead, still very funny.', o: 'Grew up in Queens. Mentions it.', pals: [] },
  'Lady Gaga': { g: ['Musical', 'Drama', 'Crime'], t: ['Showboat', 'Ambitious', 'Method'], m: { cha: 4 }, v: [2, 2, 1, 1], like: { bold: 1.2 }, tx: 'caps', w: 'Throws herself into the part like a stadium show.', o: 'Plays jazz standards. Wears a meat dress, once.', pals: ['Bradley Cooper'] },
  'Bradley Cooper': { g: ['Drama', 'Comedy', 'Musical'], t: ['Perfectionist', 'Ambitious'], m: { eth: 3 }, v: [1, 2, 2, 0], like: { amb: 1, honest: .5 }, tx: 'long', w: 'Spends six years learning to conduct for one scene.', o: 'Cooks, buys groceries in a hat, has very specific opinions about sandwiches.', pals: ['Todd Phillips', 'Jennifer Lawrence'] },
  'Chris Pratt': { g: ['Action', 'Comedy', 'Sci-fi', 'Animation'], t: ['Gregarious', 'Optimist'], m: { cha: 3 }, v: [2, 0, 0, 2], like: { loyal: .5 }, tx: 'emoji', w: 'Was living in a van in Hawaii when he was discovered.', o: 'Hunts, fishes, shares his "what\'s my snack" videos.', pals: [] },
  'Melissa McCarthy': { g: ['Comedy'], t: ['Witty', 'Kind', 'Workhorse'], m: { cha: 3 }, v: [2, 0, 0, 2], like: { gen: 1, loyal: .5 }, tx: 'emoji', w: 'Throws herself across the room for a laugh. Usually her husband directs.', o: 'Designs her own clothing line.', pals: ['Paul Feig'] },
  'Kevin Hart': { g: ['Comedy', 'Action'], t: ['Hustler', 'Workhorse', 'Showboat'], m: { eth: 4, cha: 3 }, v: [2, 2, 1, 2], like: { amb: 1.5 }, tx: 'caps', w: 'Four films a year, a stand-up tour, and a business in between.', o: 'Gym at five. Posts about it at five-oh-one.', pals: ['Dwayne Johnson'] },
};

// fill out the familiar faces: everyone else with a real counterpart gets a gentle, consistent nudge from their traits
function personaOf(p) { return p && p.real ? PERSONAS[p.real] || null : null; }
function personaSim(a, b) { const A = a.v, B = b.v; let d = 0; for (let i = 0; i < 4; i++) d += Math.abs(A[i] - B[i]); return 1 - d / 8; }   // 1 = the same, around 0 = opposite
{ const _cp = catPerson;
  catPerson = function (pid, Y) {
    const known = S.cat.people[pid] !== undefined, p = _cp(pid, Y);
    if (known) return p;
    const X = personaOf(p); if (!X) return p;
    if (X.t) p.traits = X.t.filter(t => TRAITS[t]).concat(p.traits.filter(t => !X.t.includes(t))).slice(0, 4);
    for (const k in X.m || {}) if (k in p.mind) p.mind[k] = clamp(p.mind[k] + X.m[k], 1, 20);
    recalc(p);
    // like finds like: people of a similar temperament warm to each other; opposites rub
    for (const id of Object.values(S.cat.people)) {
      const q = P(id); if (!q || q === p) continue; const Y2 = personaOf(q); if (!Y2) continue;
      const pal = (X.pals || []).includes(q.real) || (Y2.pals || []).includes(p.real), s = personaSim(X, Y2);
      const v = pal ? 45 : s >= .75 ? 18 : s >= .6 ? 8 : s <= .25 ? -12 : 0;
      if (v) addTie(p, q, v);
    }
    return p;
  };
}
// The films famous people make lean towards what they love. Not every time: careers wander.
let GL_PERSONA_GENRE = null;
{ const _gl = greenlight;
  greenlight = function (hub, o = {}) {
    if (!o.genre && o.dir === undefined && !warming() && rnd() < .35) {
      const L = S.pool[hub].director.filter(id => available(id) && personaOf(P(id)));
      if (L.length) { const d = wpick(L, id => 1 + P(id).standing / 20); const X = personaOf(P(d)); o = Object.assign({}, o, { dir: d }); if (rnd() < .75) o.genre = X.g[Math.floor(rnd() * X.g.length)]; }
    }
    GL_PERSONA_GENRE = o.genre || null;
    try { return _gl(hub, o); } finally { GL_PERSONA_GENRE = null; }
  };
}
// Casting with taste: famous actors gravitate to their kind of film and dodge the kind they avoid.
{ const _pp = pickPerson;
  pickPerson = function (hub, role, score, exclude, allowForeign) {
    if (!GL_PERSONA_GENRE) return _pp(hub, role, score, exclude, allowForeign);
    const g = GL_PERSONA_GENRE;
    return _pp(hub, role, p => { const X = p.real ? PERSONAS[p.real] : null; return score(p) + (X ? (X.g.includes(g) ? 18 : 0) - ((X.no || []).includes(g) ? 25 : 0) : 0); }, exclude, allowForeign);
  };
}
// How they text.
{ const _ts = textStyle; textStyle = function (p) { const X = personaOf(p); return X && X.tx ? X.tx : _ts(p); }; }
// What they look for in the people they hire: your style, read through their temperament.
const LIKE_LABEL = { gen: 'people who help', bold: 'people with nerve', loyal: 'people who stay', amb: 'people who want it', honest: 'straight talkers' };
function personaFactors(post) {
  if (!S.me || post.head === null || post.head === undefined) return [];
  const h = P(post.head), X = personaOf(h); if (!X || !X.like) return [];
  const St = typeof styleOf === 'function' ? styleOf() : {}, out = [];
  let s = 0, top = null, tv = 0;
  for (const k in X.like) { if (!(k in St)) continue; const c = X.like[k] * clamp(St[k] / 10, -1.5, 1.5); s += c; if (Math.abs(c) > Math.abs(tv)) { tv = c; top = k; } }
  if (top && Math.abs(s) >= .1) out.push([`${h.name.split(' ')[0]} ${s > 0 ? 'likes' : 'is wary of you; they like'} ${LIKE_LABEL[top]}`, clamp(s * .45, -.9, .9)]);
  return out;
}
{ const _hf = hireFactors; hireFactors = function (post) { const F = _hf(post); F.push(...personaFactors(post)); return F; }; }
function personaHTML(p) {
  const X = personaOf(p); if (!X) return '';
  const likes = Object.entries(X.like || {}).filter(([k]) => LIKE_LABEL[k]).sort((a, b) => b[1] - a[1]).map(([k]) => LIKE_LABEL[k]);
  return `<section class="panel persona"><h3>On set and off</h3><p><b>At work:</b> ${esc(X.w)}</p><p><b>Off the clock:</b> ${esc(X.o)}</p>
   <p class="small">Drawn to ${X.g.map(g => esc(g.toLowerCase())).join(', ')}${X.no && X.no.length ? `; won't go near ${X.no.map(g => esc(g.toLowerCase())).join(' or ')}` : ''}.${likes.length ? ` Hires ${likes.join(' and ')}.` : ''}</p></section>`;
}
{ const _vp = viewPerson; viewPerson = function (id) { const h = _vp(id), x = personaHTML(P(id)); if (!x) return h; const i = h.indexOf('<div class="cols">'); return i < 0 ? h + x : h.slice(0, i) + x + h.slice(i); }; }
