// ---------------- Stories, part eleven: 2025's best, and the 86s from 1993 to 2017 ----------------
// Same shape as before: ST(id, logline, tagline, 'setting/tod/who/caption|...', 'trailer line|...'). Cast letters only
// where the catalogue has that actor in that slot. Trailer lines name characters, never the real people who made them.
ST('onebattle', "A burned-out former revolutionary living off the grid with his teenage daughter has to get back in the fight when an old enemy, a fanatical colonel, comes looking for them both.", "Some revolutions never end. They just get older.", "desert/n//a raid on a detention camp at the border; flares and gunfire|apartment/d/A/a stoned ex-radical in a bathrobe can't remember the password|street/d/B/a colonel with a ramrod walk inspects his troops|dojo/n/C/a karate sensei runs an underground railroad between lessons|desert/d//a car chase over rolling desert hills, rising and falling like waves", "He used to blow things up.|Now he can't remember the code word.|The colonel never forgot.|One battle after another.");
ST('sinners', "In 1932 Mississippi, twin brothers back from Chicago open a juke joint for one night, and the music their young cousin plays is so good it draws something out of the dark.", "Dance with the devil and the devil dances back.", "street/d/A/twin brothers in sharp suits buy a sawmill with gangland money|field/d//a preacher's son with a guitar sings in the cotton fields|bar/n//the juke joint opens; the blues raises spirits from every century|bar/n/C/an old harmonica player warns them about the music|bar/n/B/strangers at the door ask politely to be invited in", "Two brothers. One night.|The music was too good.|Something heard it.|Don't invite them in.");
ST('sentimentalvalue', "A famous, long-absent film director comes home after his ex-wife's death with a script set in the family house, and offers the lead to the actress daughter who won't forgive him.", "A family is a house you can't move out of.", "mansion/d//a red wooden house in Oslo, where three generations lived and died|theatre/n/A/an actress has a panic attack in the wings on opening night|bar/d/B/a director offers his daughter the part she was born to play|mansion/d//an American star walks through the rooms, learning the family's grief|mansion/d/C/two sisters sit on the stairs where their grandmother sat", "He left.|He came back with a script.|About the house.|About her.");
ST('secretagent', "In Brazil in 1977, during carnival, a widowed technology professor goes back to Recife hoping to collect his son and leave the country, but someone has paid to have him killed.", "Carnival hides everything.", "car/d/A/a yellow Beetle stops at a petrol station; a body lies under cardboard|apartment/d/A/a building full of refugees, run by a sharp old woman|street/n//carnival crowds flood the streets of Recife|office/d/A/a man searches the records office for his mother's file|street/d//a hairy leg in a shark's belly makes the front page", "Recife, 1977.|Carnival week.|A man who knows too much.|And a hit man who's already been paid.");
ST('justanaccident', "A mechanic in Tehran is sure the man whose car broke down outside his garage is the guard who tortured him in prison, but he was blindfolded, so he gathers other former prisoners to be sure.", "He only heard the footsteps.", "car/n//a man hits a dog on a dark road; his car breaks down|lab/d//a mechanic hears the squeak of a prosthetic leg and freezes|desert/d//he digs a grave in the desert, then stops|car/d//a van full of former prisoners argue over whether it's him|street/n//a wedding photographer in her dress joins the kidnapping", "He was blindfolded.|He remembers the sound.|Is it him?|It was just an accident.");
ST('inthenameofthefather', "A young Belfast tearaway in London is forced to confess to an IRA pub bombing he had nothing to do with, and his father is jailed with him.", "Falsely accused. Wrongly imprisoned. He fought for justice to clear his father's name.", "street/d/A/a riot in Belfast; a boy on a rooftop|bar/n//a pub bombing in Guildford|interview/d/A/police force a confession out of him|prison/d/B/a father and son share a cell|courtroom/d/A/the Court of Appeal: they walk free", "A Belfast tearaway in London.|A pub bombing he had nothing to do with.|A confession beaten out of him.|Fifteen years to clear his father's name.");
ST('ageofinnocence', "In 1870s New York, a lawyer engaged to a sweet society girl falls for her scandalous cousin, the countess, and spends his life wanting what society forbids.", "In a world of tradition. In an age of innocence. They dared to break the rules.", "theatre/n/A/the opera; a lawyer sees the countess in a box|ballroom/n/B/a scandalous countess|mansion/d/C/a wedding|apartment/n/AB/a carriage ride; a glove unbuttoned|street/d/A/an old man doesn't go up to her apartment", "New York, 1870.|A lawyer engaged to the perfect girl.|Her cousin, the scandalous countess.|A glove unbuttoned in a carriage, and a lifetime of wanting.");
ST('casino', "A professional gambler runs a Las Vegas casino for the mob, while his childhood friend becomes the mob's enforcer and his wife a hustler.", "No one stays at the top forever.", "car/n/A/a car bomb in Las Vegas|bar/n/A/a casino; the eyes in the sky|bar/n/C/a fight with a pen|apartment/n/B/a hustler|field/d/C/two men buried in the cornfield", "Las Vegas, 1973.|The mob skims the count room.|A friend who can't keep his temper.|A wife who can't keep her hands off the money.");
ST('beforesunrise', "An American boy and a French girl meet on a train and spend one night walking around Vienna, talking about everything.", "Can the greatest romance of your life last only one night?", "train/d/AB/a young man and woman meet on a train|street/d/AB/they walk around Vienna|bar/n/AB/they phone each other in a café|church/n/AB/a cemetery for the nameless|street/d/AB/they promise to meet in six months", "A train to Vienna.|A stranger with a question.|One night to walk the city.|Six months from now, same place.");
ST('titanic', "A young aristocrat engaged to a cruel rich man falls in love with a penniless artist aboard the Titanic's doomed maiden voyage.", "Nothing on Earth could come between them.", "ship/d/A/'I'm the king of the world!'|ship/n/B/draw me like one of your French girls|car/n/AB/a car in the hold|ship/n//an iceberg|ship/n/B/'I'll never let go'", "The ship of dreams.|A girl engaged to the wrong man.|A boy who won his ticket in a card game.|I'll never let go.");

